### ISSUE TITLE
Custom Channel numbers in filters

### ISSUE THREAD

**Issue by rask1toma** [xteve-project/xTeVe#10]
It would be great to have this feature included in the filter engine. 

This should work in this way:  adding an extra field in the filter definition where you can set the starting channel or you can set it to auto(default 1000)

![tempsnip](https://user-images.githubusercontent.com/47363112/63215997-1f3aa100-c0f4-11e9-824a-4647d42b6b98.png)

In the attached image, the options should be AUTO (starts with channel 1000 and so depends on availability) and CUSTOM where the user can choose a custom number.

**Comment by xteve-project** [comment]
What if filter 1 is set to 100, filter 2 is set to 150, but the first filter contains 100 channels? 
What if the provider raises the number of channels in a group? 

That would confuse the mapping of many people.

**Comment by syralk** [comment]
Let;s go with date range
Filter 1
Start: 1100
End: 1200
Only this filter will be allow to use those channels numbers
If the filter 1 go above the limit it will use any available channels

Filter 2: Cannot choose a rage that will be in conflict with filter 1. Other wise error message
Start 1201
End 1300

If Filter 1 have more then 100 channels the next one will be 1301
We will be able to correct the channels number after wise.

**Comment by mar-mei** [comment]
Sounds to me not useful and easy to understand.  95% of people disagree with the order of channels in the M3U and use the Mapping menu after filtering. The default value 1000 can be changed in the `settings.json`

**Comment by syralk** [comment]
ok but right now the channels are randomly added in the empty spot depending of what us free

**Comment by mar-mei** [comment]
Yes, the first free channel number from 1000. I have chosen with intent 1000, so everyone has the freedom to create its own order.  Everyone uses a different system (categories, countries, provider specifications).

**Comment by jaylex32** [comment]
I believe the best implementation for this is to add a feature to renumber all channels in bulk edit, you select the channels you want to change then change the first channel number and the rest of the channels will follow the first channel you change.On Aug 19, 2019 11:42 AM, marmei <notifications@github.com> wrote:Sounds to me not useful and easy to understand.  95% of people disagree with the order of channels in the M3U and use the Mapping menu after filtering. The default value 1000 can be changed in the settings.json

**Comment by syralk** [comment]
lol jaylex32 I was actually just going to say the sameting :)
I agree,
The only thing is you have to change them one by one
it will be great to have a Auto generate, Like you bulk edit them with the first one on the top at 100 then select the one you want to auto generate and they will auto-increment to 1.
so 100,101,102,103
this way you don't have to do them one by one

**Comment by jaylex32** [comment]
Let's see what the boss said's about it!

**Comment by mar-mei** [comment]
That sounds more meaningful.

**Comment by rask1toma** [comment]
That's the reason I put two options.  You could add more options as "standard" etc.  But It would be nice to have some auto way to number my channels not by hand but using the same filter.  You could put the range you want... starting with 100, next group 300 and so.

I mean, this would be useful for houses with kids when you want to put kids channels first, then sports, then movies and PPV Events at the bottom.  Also this could help a lot when you have iptv providers that change the PPV Events.  Please read my new suggestion [here](https://github.com/xteve-project/xTeVe/issues/15)
