### ISSUE TITLE
Change of tvg-name resets channel mapping number (unique mapping id should be tvg-id or url).

### ISSUE THREAD

**Issue by NvrBst** [xteve-project/xTeVe#101]
**Describe the bug**
When the tvg-name (channel name) in the m3u file changes (even though tvg-id and tvg-url remain the same), then xTeVe thinks its a new channel and will reset the channel mapping number.

**Server:**
- OS: windows
- Arch: amd64
- xTeVe Version: 2.1.2

**To Reproduce**
This issue is illustrated better with things like "NHL Center Ice". Mapping the channels to 9000,9001,9002,etc. But every day the tvg-name (channel name) is set to the game which is playing that day on that channel: ie. "[NHL-3] DUCKS @ AVALANCHE 930PM EST".  tvg-id remains the same at "NHL3", and url remains the same. Only the channel name changes.
However, when mapped to 9000, the next day, when tvg-name changes to the new game with the m3u update, xTeVe resets the mapping, and sets the channel number to "1000". Thinking it's a new channel. This messes Plex up, since it hasn't mapped any channels at "1000" and so the channel disappears.

**Expected behavior**
xTeVe should keep the mapping, even if the channel name changes (tvg-name). xTeVe should use the unique identifier for each channel as the URL... or using the tvg-id as the unique identifier. But tvg-name shouldn't be used, since this changes often with many sports channels.

**Comment by xteve-project** [comment]
The channel name is only used as a fallback. Your playlist does not contain a unique ID for the streams. If xTeVe finds such an ID, it has priority.

tvg-id are not unique and URL's can change, therefore they cannot be used for the recognition.

It is described [here](https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/configuration.md#playlist).

You can see in the overview whether your playlist uses IDs.
![cuid](https://user-images.githubusercontent.com/53275662/75998696-80e02280-5f01-11ea-94ed-4c7a5f6b2eae.png)

**Comment by NvrBst** [comment]
Ah that is exactly what I was looking for. Thanks! :) I understand all 3 can change (tvg-id/tvg-name/url). But I feel url is probably more stable than tvg-name, particularly with sports.
But yes, a unique-id (ccui, channel-id) is the best way to go if the m3u has it! Thanks for pointing me to it!
