### ISSUE TITLE
u2b support request

### ISSUE THREAD

**Issue by philboycn** [xteve-project/xTeVe#104]
vlc could play youtube live video by this kind of urls: https://youtu.be/9Auq9mYxFEE.
but xteve cannot play this url.
can add support to youtube live videos pls?

**Comment by xteve-project** [comment]
did you try VLC as a buffer in the xTeVe settings?

**Comment by philboycn** [comment]
> did you try VLC as a buffer in the xTeVe settings?

Yes,  I`m using VLC as the decoder in the settings. win 10 platform. 
VLC apps can directly play youtube live urls but xTeVe with VLC connot. 
other m3u and http urls are no problem with VLC way.

**Comment by xteve-project** [comment]
xTeVe has no influence on this. The URL is sent to VLC, VLC receives the data and forwards it to xTeVe. The stream is not changed / transcoded with the default VLC options.

**Comment by philboycn** [comment]
solved. Thank you. You can close this issue.

**Comment by MCTyler** [comment]
You can close it too :)
