### ISSUE TITLE
TV logo updates not reflected in Plex

### ISSUE THREAD

**Issue by Costin-Nox** [xteve-project/xTeVe#105]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I updated the tv logos in Mapping, i re-added the tuner in plex. It will not use the updated logos.

I checked the generated m3u and i can see it is serving it's own logos from my local ip

**Server (please complete the following information):**
- OS  Freenas 11.2 (FreeBsd)
- xTeVe Version and Build 2.1.2 Build: 0121

**To Reproduce**
1. I added the tuner initially, saw missing logos.
2. Updated logos in mapping, turned on caching
3. Removed tuner from Plex
4. Added tuner to plex again.
5. Logos i set are not being used
**Expected behavior**
Channel logos should match what i set in mapping.

**Comment by MCTyler** [comment]
@Costin-Nox xTeVe uses the Logos from the EPG first...only if none exist in the EPG, it then uses the Logos in the M3U. I need to double check if this can be over-ridden but I think not....

**Comment by Costin-Nox** [comment]
> @Costin-Nox xTeVe uses the Logos from the EPG first...only if none exist in the EPG, it then uses the Logos in the M3U. I need to double check if this can be over-ridden but I think not....

Ah, so setting custom logos in mapping does not override it. What if i were to setup a cron task to fetch the epg, strip the logos, save it and have xteve load the epg from the local file. Would that send the custom selected logos to Plex?

**Comment by MCTyler** [comment]
Custom Logos should over-ride Plex Caches a bunch of carp so change the UUID and trick Olex into thinking it's a new tuner

**Comment by Costin-Nox** [comment]
- changed uuid (confirmed it was changed by looking at the log)
- deleted tuner from plex, cleaned bundles, rebuilt db
- restarted PMS
- added new tuner (asked to select country so it seems it assumed it's new)

-- Custom Logos still not showing up in Plex, they work fine in xteve web interface. I have image caching enabled, not sure if that could mess things up.

Thanks for the help troubleshooting this by the way!

**Comment by MCTyler** [comment]
If your uploading logos, this should take precedence Join Discord ..I use Emby not Plex
https://discord.gg/UXDz8U

Lee uses Plex he's on there
