### ISSUE TITLE
XMLTV don't work with PLEX

### ISSUE THREAD

**Issue by miKL63200** [xteve-project/xTeVe#106]
Hello.

I use XTEVE in France with PLEX. The problem is that in my XMLTV file generated by XTEVE, the language is not valued in the tags.

For example :

<tv generator-info-name="xTeVe" source-info-name="xTeVe - 2.1.2">
<channel id="1">
<display-name>FR: TF1 FHD (FRANCE)</display-name>
<icon src="http://109.8.77.198:34400/images/8091c3ae45e3dd465a57e82d6564668e.png"/>
</channel>
<programme channel="1" start="20200318192000 +0100" stop="20200318195500 +0100">
<title lang="">Demain nous appartient</title>
<desc lang="">
Un appel d'Aurore redonne espoir à Rose et Souleymane et soulage tout le monde. Une erreur médicale risque de coûter cher à Leïla alors que la discorde entre Noor et Samuel ne s'apaise pas. Grâce à Amanda, Maxime décide de se montrer raisonnable.. Christophe Barraud Ingrid Chauvin Linda Hardy Samira Lachhab Franck Monsigny Audrey Looten Clément Remiens Kamel Belghazi Charlotte Valandrey.
</desc>
<category lang="en">News</category>
<episode-num system="original-air-date">2020-03-18 19:20:00</episode-num>
<video>
<quality>HDTV</quality>
</video>
<date/>

### All the tags with the language are empty (except that of the categories). However, in this configuration, no TV channel appears in my guide in PLEX and therefore no channel is available.

I have to manually modify the tags for it to work, like this : 

<tv generator-info-name="xTeVe" source-info-name="xTeVe - 2.1.2">
<channel id="1">
<display-name>FR: TF1 FHD (FRANCE)</display-name>
<icon src="http://109.8.77.198:34400/images/8091c3ae45e3dd465a57e82d6564668e.png"/>
</channel>
<programme channel="1" start="20200318192000 +0100" stop="20200318195500 +0100">
<title lang="fr">Demain nous appartient</title>
<desc lang="fr">
Un appel d'Aurore redonne espoir à Rose et Souleymane et soulage tout le monde. Une erreur médicale risque de coûter cher à Leïla alors que la discorde entre Noor et Samuel ne s'apaise pas. Grâce à Amanda, Maxime décide de se montrer raisonnable.. Christophe Barraud Ingrid Chauvin Linda Hardy Samira Lachhab Franck Monsigny Audrey Looten Clément Remiens Kamel Belghazi Charlotte Valandrey.
</desc>
<category lang="fr">News</category>
<episode-num system="original-air-date">2020-03-18 19:20:00</episode-num>
<video>
<quality>HDTV</quality>
</video>
<date/>

### Can you help me ?
Is it a BUG, or just something I don't understand?

Thanks !

My config 👍 
- NAS QNAP (linux)
- amd64
- xTeVe V2.1.2

**Comment by xteve-project** [comment]
xTeVe copies the content from the XMLTV source into the xteve.xml file. If the language is already missing in the source, this is also missing in the xteve.xml file.
