### ISSUE TITLE
Loadbalance the same but serperate accounts

### ISSUE THREAD

**Issue by solipsist01** [xteve-project/xTeVe#107]
Most iptv providers don't allow for more than 1 concurrent stream. Imagine i would buy 3 of the same accounts.

Wouldn't it be nice to loadbalance these accounts (they get the same m3u, except for the login + pass)

that way i could provide 3 tuners to plex. Xteve would take care of which account is has to pick.

Or, does anyone know of a software solution, which can load balance the accounts to provide Xteve a unified / virtual m3u

**Comment by xteve-project** [comment]
The topic has already been discussed here.
https://github.com/xteve-project/xTeVe/issues/12
Short answer, it is currently not possible to implement this too sensibly.

**Comment by solipsist01** [comment]
I want to think with you guys. Perhaps this is a solution to the changing ID's / names.

Isn't this  the same as with the XMLTV mapping. If the m3u changes, you have to manually change those mappings as well i think. I had this in the past when the m3u changed (they added channels, and changed channels)

so

Somewhere you would be able to configure you want to provide 3 tuners / streams.
If that is configured it would be **mandatory** to select 2 extra slave streams per channel in the mapping section.

If the id's and/or m3u changes, it's not the problem of the software, but of the user. Since it's impossible to 100% automate this due to changing content, human interaction is required.

**Comment by MCTyler** [comment]
> Most iptv providers don't allow for more than 1 concurrent stream.

Not Sure where you been looking at IPTV, My Offers 5 as do "Most"

**Comment by solipsist01** [comment]
Ive found one indeed. I will close this ticket

Op zo 22 mrt. 2020 11:57 schreef Steve <notifications@github.com>:
