### ISSUE TITLE
Option to run as m3u editor only 

### ISSUE THREAD

**Issue by braccamontes** [xteve-project/xTeVe#108]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Option to run xTeVe simply as a m3u editor with all the current features except for hdhomerun proxy. 

when writing m3u, xTeVe would use IPTV urls and not xTeVe “stream” links to where xTeVe doesn’t have to be running in order for iptv player to play stream.

**Comment by xteve-project** [comment]
The URLs must all point to xTeVe so that the buffer settings can be changed without constantly reloading the M3U. If you are looking for an editor, take a look at this:
https://m3u4u.com/
