### ISSUE TITLE
Check Enabled Streams on update

### ISSUE THREAD

**Issue by jscottdouglas** [xteve-project/xTeVe#109]
**Is your feature request related to a problem? Please describe.**
Finding streams that are no longer working that are enabled still so when i go into plex i just get errors when trying a stream, i want to limit this

**Describe the solution you'd like**
I'd like xteve to check that the streams are valid on update and auto disable channels that do longer work and enable channels that may work now, not just new channels

**Comment by MCTyler** [comment]
What if they are just temporarily down due to a Provider glitch? I wouldn't want them disabled...

**Comment by xteve-project** [comment]
Yes, it doesn't make any sense.
xTeVe does not solve the problems of your provider.
Some providers have load balancing and switch the streams automatically.

I also don't know what a provider does when xTeVe makes several hundred requests to the provider in a second to see if the stream is available.

**Comment by jscottdouglas** [comment]
I am not expecting it to run hundreds all at once I am asking it to check
them all you need is 1 sec on each stream and re-enable/disable them if
they are back online or offline, it solve the issue of adding streams that
dont function and also allows the user to be able to report them to their
provider, my provider is pretty good but I still run into issues random
streams that are no longer valid

**Comment by mar-mei** [comment]
Waiting for 1 second to check a stream would take 7.5 minutes for 450 streams. Your provider sees that you automatically establish several 100 connections in the shortest possible time and end them again immediately. I could imagine that some suspect this as a DDOS attack and block your account or IP address. If you absolutely need this, write a script what it does and save all available streams in a separate M3U.
