### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by moonman** [xteve-project/xTeVe#11]
First of all I would like to thank you for this software. None of the plugins works for plex anymore and this is a genius solution.

I have created an AUR [package](https://aur.archlinux.org/packages/xteve/) for xTeVe for ArchLinux, however there are a couple of things I would like to request, if possible:

* Please have full version in the release file name to avoid confusion
* Ability to change tmp dir via command line
* XMLTV autochannel mapping with name matching. Doesn't have to be perfect, as long as one needs to only edit several channels instead of 200

**Comment by mar-mei** [comment]
- Which release file name?
- Why in the CLI? The tmp folder can be changed in the settings.
- There are many channels in several countries, the hit rate would be so bad that there would be only unnecessary support requests.

**Comment by moonman** [comment]
* Be it [here](https://github.com/xteve-project/xTeVe-Downloads) xteve_linux_amd64.zip -> xteve_2.0.1_linux_amd64.zip or on your main website xteve_2_linux_amd64.zip -->  xteve_2.0.1_linux_amd64.zip
* When xteve starts as a non-root user on linux it can't create the folder as it doesn't have permission
* Fair enough. Altough Plex does it, I guess it have a lot of code dedicated to it.

**Comment by mar-mei** [comment]
I can not change the file name, otherwise Docker would not work anymore and I would have to change the xTeVe binary update function. The current version is in info.json
