### ISSUE TITLE
tvg-id fallback

### ISSUE THREAD

**Issue by aaomidi** [xteve-project/xTeVe#110]
When xTeVe isn't able to match a tvg-id, for example if tvg-id is empty, it should try to opportunistically fall back onto name matching.

Some [string distance algorithm](https://en.wikipedia.org/wiki/String_metric) can be used with a configurable threshold. 

This would allow for a greater number of streams to be matched to guides.

**Comment by xteve-project** [comment]
Unfortunately, the hit rate is too low. There are channels with the same name in different countries. The people from Plex already had your idea, in my experience the hit rate is around 30% with one XMLTV file. Using multiple XMLTV files would result in fewer hits.
