### ISSUE TITLE
Plex reporting only 1 tuner - 6 tuners configured

### ISSUE THREAD

**Issue by stevehop** [xteve-project/xTeVe#111]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Plex reporting my Xteve DVR as having only 1 tuner when 6 have been configured (4 for my Vu+Duo2 receiver playlist and 2 for my IPTV provider playlist). Plex was previously reporting all 6 tuners and I'm not sure when this problem arose but I only noticed by chance yesterday so is confirmed to be a problem in Plex versions: 1.18.9.2571 and 1.18.9.2578. Have attempted deleting and re-adding the Xteve tuner after restarting both apps. Also if I add my Vu+Duo2 tuner directly to Plex it recognises all 4 tuners 

**Server (please complete the following information):**
- OS Windows Server 2012 R2
- Arch Intel 64 bit
- xTeVe Version and Build 2.1.2 Build: 0121

**To Reproduce**
1. Go to Plex - Live TV & DVR
2. Click on 'Add device'
3. Choose Xteve device and map channels and EPG
4. Plex shows the device shows as only 1 tuner and won't allow more than one channel to be watched or recorded

**Expected behavior**
Plex to show device as having 6 tuners and allow watching of multiple channels

**Screenshots**
![image](https://user-images.githubusercontent.com/52283434/78023843-4d04eb00-734f-11ea-8496-121b59d362b8.png)
![image](https://user-images.githubusercontent.com/52283434/78024013-92c1b380-734f-11ea-8e70-afff0715f1b0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 74.0

**Additional context**

**Comment by xteve-project** [comment]
This is a plex problem, plex remembers the serial number of each tuner. When setting up a new DVR tuner, the number of tuners (connections) is saved in the Plex database.

In the xTeVe settings.json [/home/user/.xteve/] you will find the serial number (uuid) that xTeVe uses for Plex.
```
"uuid": "2019-10-HTJ9-GG946T",
```

Delete the xTeVe in Plex.
Change a letter in the serial number (settings.json)
Set up xTeVe in Plex.

With this URL you can check which data xTeVe sends to Plex.
```
http://xteve.ip:34400/discover.json
```

**Comment by stevehop** [comment]
That fixed it , thanks
