### ISSUE TITLE
Rewrite/Override XMLTV Timezones

### ISSUE THREAD

**Issue by MisterC925** [xteve-project/xTeVe#114]
I know it's the provider's responsibility to provide timezone info in their XMLTV feeds but with the conflicting start dates of summertime in different countries, etc, the provided timezone can cause listings to show up an hour off.

Since my server runs more than Xteve and Plex. I would prefer not to have change the system time.

Would it be possible to get a setting in each XMLTV feed for an offset?  That would allow feeds from multiple providers to be corrected individually as well.

Thanks!

**Comment by MCTyler** [comment]
Why doesn't your EPG Provider offer a TZ setting is the real issue....
`zap2xml uses your system's time and timezone so make sure your system clock is correct. Set your TZ environment variable before running zap2xml if you want to change the timezone of scheduled programs (ie: export TZ=GMT).`

**Comment by xteve-project** [comment]
Your provider does not have to take summer time into account, it is sufficient if it uses UTC for all channels. Your server / client does the conversion of the time zones including summer time. Assuming the time and time zone on your server is correct.

I use Schedules Direct, all times of the channels are in UTC (+0000) and I live in +0200. My EPG data is displayed correctly.

**Comment by mbartsch** [comment]
I would like to see this feature, as I have channels from two countries, which don't agree on the timezone, so now, UTC on my playlist, but time is off by 1 hour. maybe a bug in the xmltv provider, but would be nice to have this option.

**Comment by xteve-project** [comment]
Such a function is not planned. If the provider specifies the wrong time zone, he should fix it.
