### ISSUE TITLE
Unable to run arm64 binary on Pi4 Rasbian Buster

### ISSUE THREAD

**Issue by mkopnsrc** [xteve-project/xTeVe#116]
**Describe the bug**
When downloading arm64 released binary on Pi4 and then running it after, getting following error:

root@Host1:/opt/xteve # ./xteve
-bash: ./xteve: cannot execute binary file: Exec format error

root@Host1:/opt/xteve # file ./xteve
./xteve: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=XQh93hOKc9kzT4fj4Ske/ZxxCM-QMUClrWB2wEp_S/B94ToTQyHwGUOR8LHIH8/WvLcXQsIzo9lDHRShx5v, stripped

**Server (please complete the following information):**
- OS: Rasbian Buster
- Arch: ARMv7 Processor rev 3 (v7l)
- xTeVe Version: xteve_linux_arm64.tar.gz | v2.1.2.0121

**Expected behavior**
Expecting to run this binary and preset default running config.

**Comment by xteve-project** [comment]
Is your OS also 64 bit?
