### ISSUE TITLE
Allow duplication of a channel in different groups. 

### ISSUE THREAD

**Issue by antro31** [xteve-project/xTeVe#118]
**Is your feature request related to a problem? Please describe.**
I have created several groups to organize all my channels. 
For different reasons, I would like to have the same channel in different groups. (ex: Disney Cinema in "Cinema" but also in "Kids" group. This is not possible so far. Only one group is authorized. 

**Describe the solution you'd like**
Maybe we can have a way to duplicate a channel in several groups ?
Ex: Having a channel calle "Disney Cinema" in channel 40 in group "CINEMA", but also a channel "Disney Cinema" on channel 140 in group "KIDS". Of course, both these two channels refering to the same flow. 

This could be feasible for example by clicking a "duplicate" button in mapping, on a given channel.  This would then duplicate all the characteristics, but with another channel number.

**Comment by xteve-project** [comment]
I guess you don't use Plex or Emby. Duplicate channels behave very strange in Plex, especially when recording. xTeVe is not an M3U editor. The M3U export function was only created to debug xTeVe with VLC. If you need an M3U editor, there are other alternatives, e.g. [M3U4U](https://m3u4u.com/)

**Comment by antro31** [comment]
Right, I am using Kodi with M3U lists. 
I must admit that I am not a big fan of putting my playlists into a web server. No one knows what they do with it. And I don't want my username/password to be given to someone else.
That's why xTeVe was really helpful for me. It ticks all the boxes of a playlist manager I was looking for.  It runs on Linux locally, has a web interface, a filters playlist, generates M3U, is compatible with multiple EPG... So very nice. 
Then, if you don't want to consider the channel duplication feature, never mind. I think I can accommodate with it. But please, please, keep the M3U generation in place !

**Comment by mar-mei** [comment]
Don't worry, the M3U export function will remain.
