### ISSUE TITLE
Running on MacOS with Plex server Installation UDP Problem

### ISSUE THREAD

**Issue by Schosch83** [xteve-project/xTeVe#119]
Hallo, My Problem is how can I change the UDP4 Port, get a Error.
Plex Use already UDP Port 1900?

> 2020/04/17 14:47:31 [xTeVe] [ERROR] listen udp4 224.0.0.0:1900: bind: address already in use () - EC: 0

**Comment by xteve-project** [comment]
The port is for UPnP / DLNA and cannot be changed. Two programs with the same port cannot run together on one system.
Yes Plex use port 1900 for DLNA, deactivate DLNA in Plex or install xTeVe on another computer in the same network.

If you are using a VPN, some VPN clients block requests on port 1900.

**Comment by arabesc** [comment]
I have the same issue, it conflicts with the MiniSSDPd service.
Can you please add support for the [MiniSSDPd](http://miniupnp.free.fr/minissdpd.html)?
