### ISSUE TITLE
Merge same M3u Playlist and auto go to the next steam if Tuner / Streams if full

### ISSUE THREAD

**Issue by syralk** [xteve-project/xTeVe#12]
Hi will it be possible to have the 2 streams let say Vaders1 Vaders2
then enable buffering
and if the Buffer/Tuner of Vaders1 is full auto jump to Vaders2
thanks

**Comment by mar-mei** [comment]
Worthwhile only if the provider uses IDs for their streams. Then one could implement a stacking function. As often as the channel names change, there are currently only problems.

**Comment by syralk** [comment]
Yes the ID is the same.
I know right now it doesn't work :( I test it and I got the Xteve max stream when I was maxing out the vaders1

**Comment by mar-mei** [comment]
And what if I have two different providers?  Nice would be if you could then say, if Channel 1 HD fails from Provider 1, then take channel 1 SD from Provider 2. But only if each stream has a unique ID

**Comment by syralk** [comment]
That will be awesome :)

**Comment by mar-mei** [comment]
xTeVe already supports the IDs, unfortunately most providers can not or do not want to implement this. It is best to ask the providers for the ID function, would have many other advantages.

**Comment by syralk** [comment]
I was able to do it with TVHeadEnd but the system do not work as well as this one

**Comment by mar-mei** [comment]
Yes, TVHeadEnd can do that, but I think it only works until the M3U changes.

**Comment by syralk** [comment]
uf the M3U ID changes the ID will change for both of them
but its really rare that the M3U ID change

**Comment by mar-mei** [comment]
You probably mean the tvg-id. I mean another. I will not spend time on features that only work if two playlists come from the same provider. Maybe it has to work with different providers to 100% or I'll let it be the same. 

Unique ID:
https://media.discordapp.net/attachments/484099914574462977/525051040739885077/cuid.mp4

**Comment by syralk** [comment]
It would be great if it could work with different provider :)
let say we have the same channels name "US: ABC New York" and a other provider have it too it could merge them and we could decide to put a priority on witch one should come first,

**Comment by xteve-project** [comment]
Yes, I would like that too. Only I would have to rely on the fact that the channel name never changes. Unfortunately, my experiences are a bit different. There are providers who additionally have a unique ID for each stream that never changes. xTeVe uses this ID to map the stream after updating the playlist in the mapping.
When the providers start to allocate an ID for their streams, I start to implement a stacking function in xTeVe. Before that makes no sense. 
I have a $ 60 TV tuner that exports an M3U, which itself assigns IDs for the streams.

**Comment by buroa** [comment]
Hi. I hope someone finds this. I wrote up a dirty script to do a 307 REDIRECT with SiliconDust tuners. This will detect the /tuners.html page for "not in use" or "none" in any of the text, meaning there is an available tuner. Just set the environmental variables to your tuners IPs. I also created a docker container for folks wanting to deploy in Kubernetes or something like I did.

https://hub.docker.com/r/akreii/tuner-lb

```#----------------------------------------------------------------------------#
# Imports
#----------------------------------------------------------------------------#

from flask import Flask, redirect, abort
import logging
from logging import Formatter, FileHandler
import os
import requests
from bs4 import BeautifulSoup

#----------------------------------------------------------------------------#
# App Config.
#----------------------------------------------------------------------------#

app = Flask(__name__)

@app.route('/ping')
def home():
    return 'pong'

@app.route('/auto/v<channel>.ts')
def tune(channel):
    tuner = available(app)
    if tuner:
        print('> Redirecting request to tuner {} ...'.format(tuner))
        url = 'http://{}:5004/auto/v{}.ts'.format(tuner, channel)
        return redirect(url, code = 307)
    else:
        abort(504)

def available(app):
    tuners = app.config['TUNERS'].split(',')
    for tuner in tuners:
        print('> Testing tuner {} ...'.format(tuner))
        try:
            r = requests.get('http://{}/tuners.html'.format(tuner))
            if r.status_code == 200:
                soup = BeautifulSoup(r.text, 'html.parser')
                data = soup.find('table')
                if data:
                    if "none" in data.text or \
                       "not in use" in data.text:
                       return tuner
        except Exception as e:
            logging.exception(e)



if not app.debug:
    file_handler = FileHandler('error.log')
    file_handler.setFormatter(
        Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')
    )
    app.logger.setLevel(logging.INFO)
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)
    app.logger.info('errors')

#----------------------------------------------------------------------------#
# Launch.
#----------------------------------------------------------------------------#

# Default port:
if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.config['TUNERS'] = os.environ.get('TUNERS')
    app.run(host='0.0.0.0', port=port)

**Comment by syralk** [comment]
> Hi. I hope someone finds this. I wrote up a dirty script to do a 307 REDIRECT with SiliconDust tuners. This will detect the /tuners.html page for "not in use" or "none" in any of the text, meaning there is an available tuner. Just set the "TUNERS" environmental variables to your tuners IPs, comma separated (EX: 10.10.0.6,10.10.0.7). I also created a docker container for folks wanting to deploy in Kubernetes or something like I did. You can then use this service to create one M3U playlist with. xTeVe will follow the 307 redirects (for URL /auto/v{channel}.ts) giving the first tuner, then second tuner after all filled up. Hope this helps.
> 
> https://hub.docker.com/r/akreii/tuner-lb
> 
> ```
> #----------------------------------------------------------------------------#
> # Imports
> #----------------------------------------------------------------------------#
> 
> from flask import Flask, redirect, abort
> import logging
> from logging import Formatter, FileHandler
> import os
> import requests
> from bs4 import BeautifulSoup
> 
> #----------------------------------------------------------------------------#
> # App Config.
> #----------------------------------------------------------------------------#
> 
> app = Flask(__name__)
> 
> @app.route('/ping')
> def home():
>     return 'pong'
> 
> @app.route('/auto/v<channel>.ts')
> def tune(channel):
>     tuner = available(app)
>     if tuner:
>         print('> Redirecting request to tuner {} ...'.format(tuner))
>         url = 'http://{}:5004/auto/v{}.ts'.format(tuner, channel)
>         return redirect(url, code = 307)
>     else:
>         abort(504)
> 
> def available(app):
>     tuners = app.config['TUNERS'].split(',')
>     for tuner in tuners:
>         print('> Testing tuner {} ...'.format(tuner))
>         try:
>             r = requests.get('http://{}/tuners.html'.format(tuner))
>             if r.status_code == 200:
>                 soup = BeautifulSoup(r.text, 'html.parser')
>                 data = soup.find('table')
>                 if data:
>                     if "none" in data.text or \
>                        "not in use" in data.text:
>                        return tuner
>         except Exception as e:
>             logging.exception(e)
> 
> 
> 
> if not app.debug:
>     file_handler = FileHandler('error.log')
>     file_handler.setFormatter(
>         Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')
>     )
>     app.logger.setLevel(logging.INFO)
>     file_handler.setLevel(logging.INFO)
>     app.logger.addHandler(file_handler)
>     app.logger.info('errors')
> 
> #----------------------------------------------------------------------------#
> # Launch.
> #----------------------------------------------------------------------------#
> 
> # Default port:
> if __name__ == '__main__':
>     port = int(os.environ.get('PORT', 5000))
>     app.config['TUNERS'] = os.environ.get('TUNERS')
>     app.run(host='0.0.0.0', port=port)
> ```
> 
> Here is an example line from my M3U playlist
> 
> ```
> #EXTM3U
> #EXTINF:-1 tvg-id="guide2go.90555.schedulesdirect.org" tvg-name="WMDEDT (WMDE-DT)" tvg-chno="2" channelID="x-ID.2" group-title="HDHomerun",2,WMDEDT (WMDE-DT)
> http://tuner-lb/auto/v2.ts
> ```

This look great.
can you put more details on the docker page how to use it or set it up.
Thanks

**Comment by buroa** [comment]
> > Hi. I hope someone finds this. I wrote up a dirty script to do a 307 REDIRECT with SiliconDust tuners. This will detect the /tuners.html page for "not in use" or "none" in any of the text, meaning there is an available tuner. Just set the "TUNERS" environmental variables to your tuners IPs, comma separated (EX: 10.10.0.6,10.10.0.7). I also created a docker container for folks wanting to deploy in Kubernetes or something like I did. You can then use this service to create one M3U playlist with. xTeVe will follow the 307 redirects (for URL /auto/v{channel}.ts) giving the first tuner, then second tuner after all filled up. Hope this helps.
> > https://hub.docker.com/r/akreii/tuner-lb
> > ```
> > #----------------------------------------------------------------------------#
> > # Imports
> > #----------------------------------------------------------------------------#
> > 
> > from flask import Flask, redirect, abort
> > import logging
> > from logging import Formatter, FileHandler
> > import os
> > import requests
> > from bs4 import BeautifulSoup
> > 
> > #----------------------------------------------------------------------------#
> > # App Config.
> > #----------------------------------------------------------------------------#
> > 
> > app = Flask(__name__)
> > 
> > @app.route('/ping')
> > def home():
> >     return 'pong'
> > 
> > @app.route('/auto/v<channel>.ts')
> > def tune(channel):
> >     tuner = available(app)
> >     if tuner:
> >         print('> Redirecting request to tuner {} ...'.format(tuner))
> >         url = 'http://{}:5004/auto/v{}.ts'.format(tuner, channel)
> >         return redirect(url, code = 307)
> >     else:
> >         abort(504)
> > 
> > def available(app):
> >     tuners = app.config['TUNERS'].split(',')
> >     for tuner in tuners:
> >         print('> Testing tuner {} ...'.format(tuner))
> >         try:
> >             r = requests.get('http://{}/tuners.html'.format(tuner))
> >             if r.status_code == 200:
> >                 soup = BeautifulSoup(r.text, 'html.parser')
> >                 data = soup.find('table')
> >                 if data:
> >                     if "none" in data.text or \
> >                        "not in use" in data.text:
> >                        return tuner
> >         except Exception as e:
> >             logging.exception(e)
> > 
> > 
> > 
> > if not app.debug:
> >     file_handler = FileHandler('error.log')
> >     file_handler.setFormatter(
> >         Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')
> >     )
> >     app.logger.setLevel(logging.INFO)
> >     file_handler.setLevel(logging.INFO)
> >     app.logger.addHandler(file_handler)
> >     app.logger.info('errors')
> > 
> > #----------------------------------------------------------------------------#
> > # Launch.
> > #----------------------------------------------------------------------------#
> > 
> > # Default port:
> > if __name__ == '__main__':
> >     port = int(os.environ.get('PORT', 5000))
> >     app.config['TUNERS'] = os.environ.get('TUNERS')
> >     app.run(host='0.0.0.0', port=port)
> > ```
> > 
> > 
> > Here is an example line from my M3U playlist
> > ```
> > #EXTM3U
> > #EXTINF:-1 tvg-id="guide2go.90555.schedulesdirect.org" tvg-name="WMDEDT (WMDE-DT)" tvg-chno="2" channelID="x-ID.2" group-title="HDHomerun",2,WMDEDT (WMDE-DT)
> > http://tuner-lb/auto/v2.ts
> > ```
> 
> This look great.
> can you put more details on the docker page how to use it or set it up.
> Thanks

Want to be as helpful as I can here. I deploy it into Kubernetes so here is my deployment spec:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tuner-lb
  name: tuner-lb
  namespace: plex
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      service: tuner-lb
  strategy:
    type: Recreate
  template:
      labels:
        service: tuner-lb
    spec:
      containers:
      - env:
        - name: TUNERS
          value: 10.10.0.6,10.10.0.7
        image: akreii/tuner-lb:latest
        imagePullPolicy: Always
        name: tuner-lb
        ports:
        - containerPort: 5000
          protocol: TCP
```

And my service spec

```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: tuner-lb
  name: tuner-lb
  namespace: plex
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    service: tuner-lb
  type: ClusterIP
```

I then rewrite my M3U playlist to use the service endpoint, here it will be http://tuner-lb.plex (plex being my namespace). xTeVe will connect to that and the tuner-lb service will 307 redirect to the tuners defined in the environmental variable "TUNERS". It is a VERY basic basic basic service, there is really 0 configuration done here. Just pull in the container, set your TUNERS environmental variable and rewrite your M3U playlist to use that to proxy to your SiliconDust tuners. Done!
