### ISSUE TITLE
Loops live tv on  xteve+plex

### ISSUE THREAD

**Issue by minerpool** [xteve-project/xTeVe#120]
I've recently setup xTEVE with my IPTV provider in plex and it's worked great. i ever have and have an issue where it "loops" several times then sometimes goes back to normal sometimes it doesn't until i exit the stream and restart.

Other ppl with same problem in reddit:
[Reddit](https://www.reddit.com/r/PleX/comments/fq2b04/iptv_with_xteve_looping_every_once_in_a_while)

**Server**
- OS WIN-10 last update
-CPU 8350
-GPU Crosfire RX580
- Arch 64bit
- xTeVe Version installed windows services
16GBRAM CPU USAGE 25% RAM USAGE 30%.

I have tried removing the buffer, resizing size buffer but same loops on streamings..

**Comment by mar-mei** [comment]
You answered the question yourself. Without buffer, xTeVe is not involved, you can exclude Plex if you test the streams with VLC.  If this is the case, only your provider remains as a source of errors.

**Comment by minerpool** [comment]
xDD, thanks works changeing streaming buffer with VLC in xteve options 👍
