### ISSUE TITLE
parsing issue

### ISSUE THREAD

**Issue by Soldize** [xteve-project/xTeVe#123]
**Describe the bug**

xteve work fine but since yesterday i have an error:
         
          2020-04-21 11:08:34 [xTeVe] [ERROR] strconv.Atoi: parsing "": invalid syntax () - EC: 0

and i set the tuner for this Playlist to 5 but in the log write 1

**Server (please complete the following information):**

Linux ubuntu 18.04
Version of Xteve is 2.1.2

**To Reproduce**

i changed nothing. i reboot the machine but the issue comes again!

best regards Chris

**Comment by xteve-project** [comment]
One line from the log is not enough.
Did you change any files with an editor?

Restore an older backup and then it should work again.
