### ISSUE TITLE
Export channels of a specific group:

### ISSUE THREAD

**Issue by illskillz24** [xteve-project/xTeVe#128]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
- Arch [e.g. Intel 64 Bit]
- xTeVe Version and Build [to be found in the xTeVe log]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

This wasn't explained good enough, it seems as if the export by group only works if the group name is simple like "US" but all my group names are more complicated like "Live: USA & Canada","ONE - [US] (01-01)".

Is there a way to make this work without making generic groups like "US","UK","CA"?

**Comment by illskillz24** [comment]
It's all of a sudden working now.

**Comment by illskillz24** [comment]
It's not working again, I'm using the user authentication link to send to my device.

It work for a second after taking off the user authentication part of the link manually on the device, then adding the user authentication bacc on then and changing the group.

The links do go through when sending but it say that it's empty.

Now it worked with no problem using generic group like "US"

**Comment by illskillz24** [comment]
It's working again, I don't know why it's doing this but it do work just not all the time.

**Comment by mar-mei** [comment]
A URL is composed from a limited set of characters belonging to the US-ASCII character set. These characters include digits (0-9), letters(A-Z, a-z), and a few special characters ("-", ".", "_", "~").

ASCII control characters (e.g. backspace, vertical tab, horizontal tab, line feed etc), unsafe characters like space, \, <, >, {, } etc, and any character outside the ASCII charset is not allowed to be placed directly within URLs.

**Comment by illskillz24** [comment]
I thought that was the case but why do it work sometimes, it would seems as
if it should either work or not, also I thought improper characters are
converted.


Like I said it works so thanks for the response anyways.

**Comment by illskillz24** [comment]
Is there away to sort/export by m3u or sort by user to export?

Using group is making a very long link.

**Comment by mar-mei** [comment]
I don't quite understand what exactly are you going to do?

**Comment by illskillz24** [comment]
Lets say I have a custom playlist with 10 groups I want to sent it to 3
people but not the whole playlist.

Users 1: sending Group 1,2,5, and 7
Users 2: sending Group 1,2,3,4,6,8, and 10
Users 3: sending Group 1,2,4,6, and 9

I thought about break them down into 3 m3u's that wont work either because
they are joined to one and exported as one.

The exception was they ability to send as groups but the group names are
kind of long and adding multiple groups makes the links very long.

**Comment by xteve-project** [comment]
In this case, xTeVe is not intended. All users have access to the entire M3U.
An extended user administration with authorizations would be necessary for this.

**Comment by illskillz24** [comment]
Now I know.

Thanks,

**Comment by illskillz24** [comment]
Lastly is it away to make it pull logos from the channel tvg-logo and not
the xmltv or do I have to manually renter all the logos?

**Comment by xteve-project** [comment]
The logos from the XMLTV file have priority. The logo from the M3U is only used if there is none in the XMLTV.

**Comment by illskillz24** [comment]
Yea I noticed that, I was just wondering if there was an option to choose.

Thanks!
