### ISSUE TITLE
[ERROR] XML syntax error on line 6215: invalid UTF-8 () - EC: 0

### ISSUE THREAD

**Issue by Mibo5354** [xteve-project/xTeVe#129]
**Describe the bug**
The generated epg xml has invalid UTF-8 characters, and I can't add it to xteve.

**Server**
- OS Linux - Ubuntu 20.04 Minimal
- Arch Intel 64 Bit
- xTeVe Version and Build 2.1.2

**To Reproduce**
1. Go to initial setup xteve web ui
2. Add playlist
3. Try to add xmltv

**Expected behavior**
Epg xmltv added with invalid UTF-8 characters stripped.

**Additional context**
The epg I used was http://42.98.109.147:9981/xmltv/channels

**Comment by mar-mei** [comment]
This is not a valid UTF8 XML file. The file is also recognized as invalid in my browser.

**Comment by Mibo5354** [comment]
> This is not a valid UTF8 XML file. The file is also recognized as invalid in my browser.

If you looked at the line that was recognized as invalid you can see it has one invalid character. If you removed that character then it works fine.

**Comment by xteve-project** [comment]
These are not valid characters within an XML file. This must be reported to the person who created this file.
![Auswahl_004](https://user-images.githubusercontent.com/53275662/80917385-d2b8f380-8d5e-11ea-93a5-54f7283d1a5c.png)
