### ISSUE TITLE
[Feature] PMS Active Channels

### ISSUE THREAD

**Issue by nichcuta** [xteve-project/xTeVe#133]
I think this would be a very neat workaround for Plex only accepting 480 channels without limiting the m3u playlist generated.

So basically what if there is a radio button like "Active" button named ex: "Active for PMS". If enabled it would add the channel to the channels that will be served to the DVR ie Plex.

So the end result would be having more than 480 channels in your m3u file but limiting the DVR to the selected channels via this radio button.

Current Active button:
![image](https://user-images.githubusercontent.com/25469431/81786497-097dcf00-9500-11ea-8a88-6fcbb63c7815.png)

I think it would be a sleek feature.

**Comment by mar-mei** [comment]
The limit is just a warning, you can use several thousand channels. I just don't know how many table entries your browser can handle in the mapping.

**Comment by nichcuta** [comment]
Understood, thanks
