### ISSUE TITLE
[Feature Request] Backup epg assignment for channels

### ISSUE THREAD

**Issue by NH-Networks** [xteve-project/xTeVe#135]
is it possible to make backup epg assignment for channels ?

if for example the main epg has no data that day for the channel during the update scheduler set times, 
the data of the second assigned epg will be used.

Hope it's a option you will consider, would be great!

thanks in advanced.

**Comment by mar-mei** [comment]
No, only one EPG source is possible per channel. There are enough options for reliable EPG:
- Schedules Direct
- zap2it
- WebGrab+Plus
