### ISSUE TITLE
[BUG] IP given instead of FQDN in xteve.m3u

### ISSUE THREAD

**Issue by nichcuta** [xteve-project/xTeVe#137]
Hi,

I just found out an interesting behaviour. When i start the xteve service "service xteve start" and after some time check the xteve.m3u file, i see the below ("Updates all files at startup" is ticked under settings):

	#EXTINF:0` channelID="x-ID.5954" tvg-chno="1" tvg-name="XX: CHANNEL (FHD)" tvg-id="1" tvg-logo="http://192.168.80.XX:8444/images/80b4396bc6913b5c8140d2a4fd7010c1.png" group-title="GRP Entertainment",XX: CHANNEL (FHD)
	http://192.168.80.XX:8444/stream/f1a191c90490f1cb69229f43f7c4cc91

Upon manually trigering an update by going to playlist and click "Update" under the playlist the proper FQDN is placed in the xteve.m3u rather than the IP Address as shown below:

	#EXTINF:0` channelID="x-ID.5954" tvg-chno="1" tvg-name="XX: CHANNEL (FHD)" tvg-id="1" tvg-logo="http://192.168.80.XX:8444/images/80b4396bc6913b5c8140d2a4fd7010c1.png" group-title="GRP Entertainment",XX: CHANNEL (FHD)
	http://tv.EXAMPLE.com:8444/stream/f1a191c90490f1cb69229f43f7c4cc91

**- OS:** Ubuntu Server 18.04
**- Arch:** Intel 64 Bit
**- xTeve Version:** 2.1.2

Any idea what could trigger such behaviour?

**Comment by mar-mei** [comment]
That is supposed to be like that.
With any HTTP request, xTeVe recognizes via which IP or FQDN the request was made. Except for downloading the xteve.xml, the URLs are generated immediately. (M3U, DVR lineup).

**Comment by nichcuta** [comment]
Thanks for the clarification of how the generation of URLs is done
