### ISSUE TITLE
[ISSUE] Audio out of Sync on Channel

### ISSUE THREAD

**Issue by nichcuta** [xteve-project/xTeVe#138]
So basically i have a strange issue i cannot get my head around. I noticed this behaviour on one channel, not sure if there are others but not all channels for sure.

If i play the stream directly from the provider, the video and audio match perfectly, but if i play the channel via the xTeve generated m3u with either xTeve, VLC, or FFmpeg Buffering (FFMPEG/VLC with default options) the stream plays but the audio is about 2200ms out of sync.

I started off by disabling the buffer and trying again but surprisingly the audio issue is still present even with the no buffer which is strange since xTeve should be passing the stream directly to the client. Multiple clients were also tested to rule out that.

**- OS:** Ubuntu Server 18.04
**- Arch:** Intel 64 Bit
**- xTeve Version:** 2.1.2

The only explanation is that something is causing a delay when passing the stream from xTeve. Anyone has any additional tests i could perform to narrow the issue out?

Any help is appreciated.

**Comment by mar-mei** [comment]
In the temp folder you will find the individual streaming segments, which you can open with VLC to check.
Linux:
```
/tmp/xteve/
```

With the xTeVe Buffer I cannot imagine that, since no streaming data is changed, only the bytes are buffered and then passed on to the client.

**Comment by nichcuta** [comment]
issue resolved without changes to xTeve. Guess it was a false positive
