### ISSUE TITLE
Image Caching URL Generation Bugs

### ISSUE THREAD

**Issue by andrewkhunn** [xteve-project/xTeVe#139]
I run xTeVe in a Docker container on a custom Docker network for all my related services. There are 2 bugs I've run into that are show-stoppers for using image caching for my setup:

1. I am accessing the xTeVe web portal by reverse proxy at a url like `https://xteve.example.com/web/`, but image urls manually regenerated via the GUI show up in `xteve.xml` as: `http://xteve.example.com/images/08996f8b767efb120c146f734c0af8ff.png`. I have a redirect setup for http > https, but xTeVe should reflect the correct protocol. This bug doesn't actually break anything in Plex because of the rewrite rule.

2. When the nightly cron runs inside the Docker container to update the XEPG, it generates links in the following format: `http://localhost:34400/images/08996f8b767efb120c146f734c0af8ff.png`, which obviously breaks images in Plex because the Docker container doesn't respond to requests at that address. I'm not sure of the most ideal solution to ensuring xTeVe knows what the correct external address should be. Maybe cached in `settings.json` from the last web portal login?

3. I'm also guessing that the way image urls are constructed for channel icons uploaded via the web portal (even when image caching is disabled) may need to be looked at as well. This seems to be the case for the custom icons I have in my epg.

I'm running the latest master branch of xTeVe: `[xTeVe] Version: 2.1.2 Build: 0121`

I'd be happy to provide further information to get these issues sorted out. I need some image caching!

Thanks!

**Comment by mar-mei** [comment]
Take a look here:
https://github.com/xteve-project/xTeVe/issues/130

**Comment by andrewkhunn** [comment]
Sorry for the duplicate!

I'd just like to voice support for a longer-term fix for this, though. I don't have anything mis-confiogured and am accessing xTeVe via the correct portal address, but yet urls are still broken. Would be great if there was a solution besides timing a cronjob via the API to right before whenever Plex updates the tuner (which is what seems to me like the fix for me will end up being?).

Thanks for the quick repsonse!
