### ISSUE TITLE
ARM Memory Usage - PID Killed

### ISSUE THREAD

**Issue by mmendenhall** [xteve-project/xTeVe#140]
On occasion, I'm seeing the xteve service killed by the system kernel. Checking the system log, it appears xteve has consumed all the memory. 

- OS: Ubuntu Linux on Raspberry Pi
- Arch ARM 64bit
- xTeVe Version and Build: 2.1.2 Build 0121

Simply starting xteve and playing back a stream; you can see the xteve memory usage climb. Let this go long enough and you'll notice the system will eventually run out of memory and the system kernel will kill xteve. 

Below is the most recent messages from the system log. 

May 19 15:49:30 ubuntuxteve kernel: [156894.468387] xteve invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
May 19 15:49:30 ubuntuxteve kernel: [156894.468404] CPU: 0 PID: 2794 Comm: xteve Tainted: G         C  E     5.4.0-1008-raspi #8-Ubuntu
May 19 15:49:30 ubuntuxteve kernel: [156894.468407] Hardware name: Raspberry Pi 3 Model B Rev 1.2 (DT)
May 19 15:49:30 ubuntuxteve kernel: [156894.468410] Call trace:
May 19 15:49:30 ubuntuxteve kernel: [156894.468422]  dump_backtrace+0x0/0x190
May 19 15:49:30 ubuntuxteve kernel: [156894.468427]  show_stack+0x24/0x30
May 19 15:49:30 ubuntuxteve kernel: [156894.468434]  dump_stack+0xd8/0x124
May 19 15:49:30 ubuntuxteve kernel: [156894.468440]  dump_header+0x48/0x1ec
May 19 15:49:30 ubuntuxteve kernel: [156894.468444]  oom_kill_process+0x19c/0x1a0
May 19 15:49:30 ubuntuxteve kernel: [156894.468449]  out_of_memory+0x1a4/0x2b8
May 19 15:49:30 ubuntuxteve kernel: [156894.468455]  __alloc_pages_slowpath+0xad0/0xb80
May 19 15:49:30 ubuntuxteve kernel: [156894.468460]  __alloc_pages_nodemask+0x27c/0x2d8
May 19 15:49:30 ubuntuxteve kernel: [156894.468468]  pagecache_get_page+0x130/0x310
May 19 15:49:30 ubuntuxteve kernel: [156894.468471]  filemap_fault+0x4a4/0x970
May 19 15:49:30 ubuntuxteve kernel: [156894.468479]  ext4_filemap_fault+0x38/0x58
May 19 15:49:30 ubuntuxteve kernel: [156894.468484]  __do_fault+0x54/0x128
May 19 15:49:30 ubuntuxteve kernel: [156894.468488]  do_fault+0x1fc/0x548
May 19 15:49:30 ubuntuxteve kernel: [156894.468493]  __handle_mm_fault+0x154/0x2f8
May 19 15:49:30 ubuntuxteve kernel: [156894.468497]  handle_mm_fault+0x12c/0x188
May 19 15:49:30 ubuntuxteve kernel: [156894.468503]  do_page_fault+0x154/0x488
May 19 15:49:30 ubuntuxteve kernel: [156894.468507]  do_translation_fault+0xb0/0xc0
May 19 15:49:30 ubuntuxteve kernel: [156894.468511]  do_mem_abort+0x50/0xb0
May 19 15:49:30 ubuntuxteve kernel: [156894.468515]  do_el0_ia_bp_hardening+0x8c/0xd8
May 19 15:49:30 ubuntuxteve kernel: [156894.468520]  el0_ia+0x24/0x28
May 19 15:49:30 ubuntuxteve kernel: [156894.468568] Mem-Info:
May 19 15:49:30 ubuntuxteve kernel: [156894.468583] active_anon:187795 inactive_anon:40 isolated_anon:0
May 19 15:49:30 ubuntuxteve kernel: [156894.468583]  active_file:30 inactive_file:36 isolated_file:0
May 19 15:49:30 ubuntuxteve kernel: [156894.468583]  unevictable:4278 dirty:0 writeback:0 unstable:0
May 19 15:49:30 ubuntuxteve kernel: [156894.468583]  slab_reclaimable:8566 slab_unreclaimable:12006
May 19 15:49:30 ubuntuxteve kernel: [156894.468583]  mapped:2066 shmem:969 pagetables:783 bounce:0
May 19 15:49:30 ubuntuxteve kernel: [156894.468583]  free:851 free_pcp:182 free_cma:0
May 19 15:49:30 ubuntuxteve kernel: [156894.468594] Node 0 active_anon:751180kB inactive_anon:160kB active_file:120kB inactive_file:144kB unevictable:17112kB isolated(anon):0kB isolated(file):0kB mapped:8264kB dirty:0kB writeback:0kB shmem:3876kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
May 19 15:49:30 ubuntuxteve kernel: [156894.468608] DMA free:3404kB min:3764kB low:4704kB high:5644kB active_anon:751180kB inactive_anon:160kB active_file:84kB inactive_file:0kB unevictable:17112kB writepending:0kB present:970752kB managed:930008kB mlocked:17112kB kernel_stack:2896kB pagetables:3132kB bounce:0kB free_pcp:728kB local_pcp:236kB free_cma:0kB
May 19 15:49:30 ubuntuxteve kernel: [156894.468612] lowmem_reserve[]: 0 0 0 0
May 19 15:49:30 ubuntuxteve kernel: [156894.468626] DMA: 444*4kB (UME) 64*8kB (UM) 38*16kB (UM) 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 2896kB
May 19 15:49:30 ubuntuxteve kernel: [156894.468678] 2623 total pagecache pages
May 19 15:49:30 ubuntuxteve kernel: [156894.468684] 0 pages in swap cache
May 19 15:49:30 ubuntuxteve kernel: [156894.468689] Swap cache stats: add 0, delete 0, find 0/0
May 19 15:49:30 ubuntuxteve kernel: [156894.468694] Free swap  = 0kB
May 19 15:49:30 ubuntuxteve kernel: [156894.468698] Total swap = 0kB
May 19 15:49:30 ubuntuxteve kernel: [156894.468703] 242688 pages RAM
May 19 15:49:30 ubuntuxteve kernel: [156894.468707] 0 pages HighMem/MovableOnly
May 19 15:49:30 ubuntuxteve kernel: [156894.468712] 10186 pages reserved
May 19 15:49:30 ubuntuxteve kernel: [156894.468716] 2048 pages cma reserved
May 19 15:49:30 ubuntuxteve kernel: [156894.468721] Tasks state (memory values in pages):
May 19 15:49:30 ubuntuxteve kernel: [156894.468726] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
May 19 15:49:30 ubuntuxteve kernel: [156894.468759] [    698]     0   698    12807      813   106496        0          -250 systemd-journal
May 19 15:49:30 ubuntuxteve kernel: [156894.468768] [    723]     0   723     5087      596    61440        0         -1000 systemd-udevd
May 19 15:49:30 ubuntuxteve kernel: [156894.468780] [   1060]     0  1060    70053     4148    94208        0         -1000 multipathd
May 19 15:49:30 ubuntuxteve kernel: [156894.468792] [   1101]   102  1101    22530      629    77824        0             0 systemd-timesyn
May 19 15:49:30 ubuntuxteve kernel: [156894.468801] [   1145]   100  1145     6611      720    77824        0             0 systemd-network
May 19 15:49:30 ubuntuxteve kernel: [156894.468810] [   1147]   101  1147     6016     1571    86016        0             0 systemd-resolve
May 19 15:49:30 ubuntuxteve kernel: [156894.468819] [   1186]     0  1186    59371      530    90112        0             0 accounts-daemon
May 19 15:49:30 ubuntuxteve kernel: [156894.468828] [   1187]   103  1187     2036      817    53248        0          -900 dbus-daemon
May 19 15:49:30 ubuntuxteve kernel: [156894.468837] [   1190]     0  1190    20194      512    57344        0             0 irqbalance
May 19 15:49:30 ubuntuxteve kernel: [156894.468846] [   1191]     0  1191     7267     2452    90112        0             0 networkd-dispat
May 19 15:49:30 ubuntuxteve kernel: [156894.468854] [   1193]   104  1193    55290      683    73728        0             0 rsyslogd
May 19 15:49:30 ubuntuxteve kernel: [156894.469046] [   1194]     0  1194   290207     3437   253952        0          -900 snapd
May 19 15:49:30 ubuntuxteve kernel: [156894.469055] [   1196]     0  1196     4162      569    73728        0             0 systemd-logind
May 19 15:49:30 ubuntuxteve kernel: [156894.469064] [   1197]     0  1197     3088      369    57344        0             0 wpa_supplicant
May 19 15:49:30 ubuntuxteve kernel: [156894.469073] [   1220]     0  1220     2082      438    53248        0             0 cron
May 19 15:49:30 ubuntuxteve kernel: [156894.469082] [   1241]     0  1241      896      403    45056        0             0 atd
May 19 15:49:30 ubuntuxteve kernel: [156894.469091] [   1244]     0  1244    26946     2451   102400        0             0 unattended-upgr
May 19 15:49:30 ubuntuxteve kernel: [156894.469100] [   1249]     0  1249     1707      348    53248        0             0 agetty
May 19 15:49:30 ubuntuxteve kernel: [156894.469109] [   1254]     0  1254     1326      273    40960        0             0 agetty
May 19 15:49:30 ubuntuxteve kernel: [156894.469118] [   1275]     0  1275     3045      804    61440        0         -1000 sshd
May 19 15:49:30 ubuntuxteve kernel: [156894.469127] [   1280]     0  1280    58229      169    81920        0             0 polkitd
May 19 15:49:30 ubuntuxteve kernel: [156894.469135] [   1502]     0  1502     3897      688    69632        0             0 sshd
May 19 15:49:30 ubuntuxteve kernel: [156894.469145] [   1505]  1001  1505     4891     1266    73728        0             0 systemd
May 19 15:49:30 ubuntuxteve kernel: [156894.469154] [   1506]  1001  1506    42425     1108   102400        0             0 (sd-pam)
May 19 15:49:30 ubuntuxteve kernel: [156894.469163] [   1604]  1001  1604     3897      527    69632        0             0 sshd
May 19 15:49:30 ubuntuxteve kernel: [156894.469172] [   1605]  1001  1605     2414      708    53248        0             0 bash
May 19 15:49:30 ubuntuxteve kernel: [156894.469180] [   1630]     0  1630     3896      660    77824        0             0 sshd
May 19 15:49:30 ubuntuxteve kernel: [156894.469189] [   1700]  1001  1700     3896      498    77824        0             0 sshd
May 19 15:49:30 ubuntuxteve kernel: [156894.469198] [   1701]  1001  1701     2414      794    57344        0             0 bash
May 19 15:49:30 ubuntuxteve kernel: [156894.469207] [   1710]     0  1710     3175      543    57344        0             0 sudo
May 19 15:49:30 ubuntuxteve kernel: [156894.469216] [   1711]     0  1711    58057      722    86016        0             0 iftop
May 19 15:49:30 ubuntuxteve kernel: [156894.469224] [   2778]  1001  2778   199860   171621  1445888        0             0 xteve
May 19 15:49:30 ubuntuxteve kernel: [156894.469240] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=xteve,pid=2778,uid=1001
May 19 15:49:30 ubuntuxteve kernel: [156894.469520] Out of memory: Killed process 2778 (xteve) total-vm:799440kB, anon-rss:686484kB, file-rss:0kB, shmem-rss:0kB, UID:1001 pgtables:1412kB oom_score_adj:0
May 19 15:49:30 ubuntuxteve kernel: [156894.677247] oom_reaper: reaped process 2778 (xteve), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by mar-mei** [comment]
What says (Terminal):
```
swapon -s
```

**Comment by mmendenhall** [comment]
That command does not return on the Pi but I understand what you're looking for I think.

/var/log# free -h
              total        used        free      shared  buff/cache   available
Mem:          908Mi       841Mi       6.0Mi       3.0Mi        60Mi        41Mi
Swap:            0B          0B          0B
root@ubuntuxteve:/var/log#

I'll do some research and get the swap configured and see if that helps.

**Comment by mmendenhall** [comment]
Swap file has been configured for 2GB. 

swapon -s now returns details so I will keep an eye on it for a while and report back.

**Comment by mmendenhall** [comment]
Creating and enabling the swap seems to have addressed the issue I was having. I have not had any issues since enabling yesterday afternoon and usually by now I would have had to start it back up twice.
