### ISSUE TITLE
Use the EPG from HDHomeRun

### ISSUE THREAD

**Issue by smurfster** [xteve-project/xTeVe#143]
Hi,

1. I have a HDHomerun and a IPTV subscription. 
2. I have a url for xmltv for my IPTV subscription.
3. They both have completely different channels

Is there a way of using the HDHomerun as a epg source?

Regards

**Comment by mar-mei** [comment]
No, only XMLTV files can be used as EPG sources. Maybe there is a tool somewhere that creates an XMLTV file from the HDHomeRun EPG.
