### ISSUE TITLE
API responds with xml

### ISSUE THREAD

**Issue by MrSco** [xteve-project/xTeVe#144]
I'm trying to use the API per the documentation (https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/configuration.md) and it keeps returning 200 OK with XML no matter what I POST.

- OS: windows 10 x64
- Arch: intel x64
- xTeVe Version: 2.2.2

![Zbw6zne 1](https://user-images.githubusercontent.com/11297411/82836830-5c0ea200-9e95-11ea-9bf0-054e1019e419.png)

**Comment by mar-mei** [comment]
The URL was missing in the documentation:
```
http://xteve.ip:port/api/
```
