### ISSUE TITLE
Ability to add-in local TV tuner feed

### ISSUE THREAD

**Issue by derekcentrico** [xteve-project/xTeVe#149]
**Is your feature request related to a problem? 

It's not related to a problem with Xteve.  Rather, Plex has a limitation where we cannot use a cable and antenna tuner at the same time.  This eliminates my ability to have a local tuner with my antenna and my internet tv feed in Plex.  If there's an internet outage I'm dead in the water unless I reconfigure Plex by removing xTeve's feed.

**Describe the solution you'd like**

It would be wonderful if the software could link into a local USB tuner for a feed as well to be added to the mapping to pass onto Plex.  For instance, in South Florida there are 30 antenna channels I can pick up with my WinTV-HVR-950Q USB TV Tuner.  I'd love to inject those into xTeve to show up within Plex.

**Describe alternatives you've considered**

The only one I found was to delete whatever instance of LiveTV/DVR is setup, reboot, and add the other one should an outage occur.

**Additional context**

Not really.

**Comment by mar-mei** [comment]
Support of hardware tuners is not planned. The development would be very expensive. The most popular tuners would have to be bought for development. See if your tuner can also export an M3U.
