### ISSUE TITLE
Feature request: filter log

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#155]
**Is your feature request related to a problem? Please describe.**
Not a problem, but this would be a nice addition.

**Describe the solution you'd like**
Add a filter for the log so you can see just warnings, or just errors.

**Describe alternatives you've considered**
Open log in Notepad++ and use Find function

**Comment by MCTyler** [comment]
FWIW....Seems simple enough but not too practical when your alternative solution fills the gap. I think Marmei has always left the log file usage up to each of us to decide whats best.

**Comment by mar-mei** [comment]
Why don't you use the search function from your browser? Ctrl + F warning

For reasons of privacy, no logs are saved on the disk. The console output can be saved with a command in a file for every OS, then you can open it with any editor. Just googling
