### ISSUE TITLE
Feature Request: Validation (or automatic selection) of concurrent streams allowed for a playlist

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#156]
**Is your feature request related to a problem? Please describe.**
My provider says that 1 stream is allowed; however I've had success with at least 3 simultaneous streams. I'm not sure what my real limit is.

**Describe the solution you'd like**
xTeVe could test running multiple streams from the playlist until an error is returned from the provider.

**Describe alternatives you've considered**
Testing on multiple clients at once for different channels. This gets challenging to test more than 3 streams.

**Comment by mar-mei** [comment]
It's not that easy to test, every provider behaves differently:
- Some end an older stream if you exceed the limit
- Others block your account for several hours
- Or do not allow new streams

**Comment by MCTyler** [comment]
Most Apps Like Smarters allow you to see your "Lines"...Use it.
