### ISSUE TITLE
Feature request: access streams through a proxy server

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#157]
**Is your feature request related to a problem? Please describe.**
Not a problem. It would be nice to use a proxy to access the stream urls for privacy reasons.

**Describe the solution you'd like**
Use a proxy to access the streams. Additionally, it would be nice to have a default proxy, and then an individual playlist override.

**Describe alternatives you've considered**
Using VLC media player with proxy setup there, as the buffer agent. Problem is some of my URLs are hosted on the same server (localhost) from NextPVR (they are OTA channels) and VLC cannot access them when using a proxy.

**Comment by Daniel15** [comment]
FWIW, if you have a proxy server you control, you could probably accomplish this by running xTeVe on the proxy server itself? Otherwise I've had good luck using [hls-proxy](https://github.com/warren-bank/HLS-Proxy).

**Comment by ReenigneArcher** [comment]
Not a proxy I control, but would like to use my NordVPN account (they have proxy servers). Also would like the option to use it for specific m3us, not all.

**Comment by Daniel15** [comment]
Oh cool, I didn't realise that NordVPN has proxy servers! That makes it much easier to proxy just a single app through it, which is something I was wondering about.

One approach that might work would be to figure out the command-line arguments to enable SOCKS proxying for VLC, and then configure xTeVe to buffer via VLC. However, that'd apply the proxy to all the M3Us, not just specific ones, so it doesn't fully suit your use case.

**Comment by alturismo** [comment]
may start by looking at a local reverse proxy for your usecase, bind port, backend(s) are then your iptv source(s), controlled by ports u use or bind addresse if u have some local addresses, then route your wished vpn connections through your proxy ... ;)

i never tested it this way and its a overkill, but ... could work ;) if thats your intention ;)

a bit more simple setup, sep xteve instances in dockers, and the vpn instance running through a vpn docker, and u done ... may even as chain, also not tested but probably pretty straight forward and easy.

**Comment by ReenigneArcher** [comment]
Closing this as it appears proxy support may be added in this pull request (https://github.com/xteve-project/xTeVe/pull/134)

Also using streamlink as a buffer agent (https://github.com/xteve-project/xTeVe/issues/198) gives multiple options for using a proxy.

Would be fairly simple to write a script to parse the stream url and determine whether or not use a proxy.

**Comment by beardypig** [comment]
@ReenigneArcher you can already do this if you use the xTeVe buffer, it will work with `ffmpeg` except on https URLs (this is a limitation of `ffmpeg`). All you need to do is set the environment variables `HTTP_PROXY` and `HTTPS_PROXY` to the proxy URL. 
I am using this method to proxy all of xTeVe's requests, but if you set up a local proxy server you could configure it to forward only some URLs to your proxy and other not. I have use Privoxy to do this in the past.
