### ISSUE TITLE
xTeVe won't start if GitHub reports HTTP 500

### ISSUE THREAD

**Issue by klatka** [xteve-project/xTeVe#159]
Today GitHub has reported incidents: [GitHub Status](https://www.githubstatus.com/)

Anyway, today I restarted the server running the docker container with xTeVe and it didn't start. See logs below:

![500](https://user-images.githubusercontent.com/42534401/87280237-37789300-c4f2-11ea-8c16-4a03569af90f.PNG)

Neither the xTeVe site nor the stream in plex worked (connection refused).

So i couldn't use IPTV because GitHub is currently not available...

Please fix this.

**Comment by MCTyler** [comment]
Which Docker Version are you using? `dnsforge`, `Alturismo`? Marmei doesn't have anything to do with Dockers.
See `Docker Hub`, search `xTeVe` for further info.

**Comment by mar-mei** [comment]
Is fixed in the current beta.
The error message no longer leads to xTeVe being closed.

**Comment by klatka** [comment]
Thank you!
