### ISSUE TITLE
xteve v2.0.2 crash

### ISSUE THREAD

**Issue by shocker2** [xteve-project/xTeVe#16]
Hello,
  Since the v2.0 upgrade I'm encountering a daily crash on CentOS v7.6.x.
  Now I'm with 2.0.2 build 0020; database version 2.0.0 and the problem still occurs.
Log attached

**Comment by xteve-project** [comment]
Strange, you're the first one with this error.
I think I have found the error. Please test this with the beta 2.0.2.0021
https://github.com/xteve-project/xTeVe#xteve-beta-branch

**Comment by shocker2** [comment]
Thank you for the feedback. Two out of three servers are generating this issue on my side after the v2.0 upgrade. Never got any issues before :)
Running the beta on all of them now: [xTeVe] Version:               2.0.2 Build: 0021, I'll come back with feedback if the issue is solved or not.
Thanks once again!

**Comment by shocker2** [comment]
Got another one today. Log attached
[log.txt](https://github.com/xteve-project/xTeVe/files/3560903/log.txt)

**Comment by xteve-project** [comment]
The log is not from the beta version.
Current beta version is 2.0.2.0023

You also recognize it when beta is displayed in the top left corner of the web interface.

This is your version:
```
2019/08/27 17:05:28 [xTeVe] Version:               2.0.2 Build: 0020
...
2019/08/27 17:05:28 [xTeVe] GitHub:                https://github.com/xteve-project
2019/08/27 17:05:28 [xTeVe] Git Branch:            master [xteve-project]
```

**Comment by shocker2** [comment]
Indeed, but I'm starting it with -branch beta. Do I need to do something else to run in?

**Comment by shocker2** [comment]
> The log is not from the beta version.
> Current beta version is 2.0.2.0023
> 
> You also recognize it when beta is displayed in the top left corner of the web interface.
> 
> This is your version:
> 
> ```
> 2019/08/27 17:05:28 [xTeVe] Version:               2.0.2 Build: 0020
> ...
> 2019/08/27 17:05:28 [xTeVe] GitHub:                https://github.com/xteve-project
> 2019/08/27 17:05:28 [xTeVe] Git Branch:            master [xteve-project]
> ```

Hi, seems that the log is correct, it's the beta version. I've provided a full log and it started as normal and then app upgrated it self as beta. If you scroll below you will see that it's running as beta.

**Comment by mar-mei** [comment]
Update to Beta 2.0.2.0024
I found something else.

If the error still occurs now, I have no idea.
The buffer consists of two processes that access an object. One is reading, the other is writing.

The error states that both happen simultaneously. That's why it crashes. I've created a third process for testing that writes several thousand times a second into the same object. xTeVe does not crash in my tests.

**Comment by shocker2** [comment]
[log.txt](https://github.com/xteve-project/xTeVe/files/3590164/log.txt)
It's still crashing. No idea :)

**Comment by shocker2** [comment]
I'm running 3 instances on a VM with 10GB of RAM. I've seen that the entire RAM is used.
It might be due to the new feature "stream buffer with 1MB buffer size" that I'm using with v2? I've just set 24GB on the VM to see if the behavior is improving.

**Comment by shocker2** [comment]
> I'm running 3 instances on a VM with 10GB of RAM. I've seen that the entire RAM is used.
> It might be due to the new feature "stream buffer with 1MB buffer size" that I'm using with v2? I've just set 24GB on the VM to see if the behavior is improving.

It might be due to the RAM. Killing all xteve instances reduces the ram usage to 400MB instead of 10GB.

I have attached a graph.

![Screenshot 2019-09-09 at 14 43 47](https://user-images.githubusercontent.com/24977727/64528061-3f830780-d310-11e9-8c1d-69a251f895f8.png)

**Comment by mar-mei** [comment]
I can not adjust the error.

xTeVe is written in Go and Go uses garbage collection for memory management.
Here it is very well described:
https://povilasv.me/go-memory-management/

To create the xteve.xml, all XMLTV files are loaded into memory. Then the memory is marked for release. Whether the memory is then released is decided by the operating system. Memory is only released by the OS if other programs need it.

**Comment by shocker2** [comment]
I've created a new environment with KVM VM, 128GB of RAM, 2GB/s write speed with intel Optane 900p, Ubuntu OS, just to ensure that there is no system IO limitation.
I migrated my xteve folder and run it from there.

One more thing, not sure if the issue if from xteve latest version or Emby, but if you run 2 xteve sessions on different ports with the same channel id, Emby is not doing anymore the load balancing between the available tuners. I'm using Emby v4.3.0.8.

No idea what to do next :)


[xteve.log](https://github.com/xteve-project/xTeVe/files/3625414/xteve.log)

**Comment by shocker2** [comment]
I found something interesting.
Only one stream on xteve with 2mb buffer enabled is using the entire ram.
I can see this error: [xTeVe] [ERROR] Service Unavailable (This error message comes from the provider) - EC: 4004

**Comment by mar-mei** [comment]
I have no idea how Emby's load balancing works. I also do not know what that has to do with xTeVe.
xTeVe is written in Go, memory management is garbage collection. 90% of your RAM will be the XMLTV files. Memory management is handled by your operating system. If no other program requires memory, there is no reason for the OS to release the memory.

Service Unavailable: Is an HTTP status, all connections to the server are HTTP connections, if the status is not OK, the connection is closed and status is in the log. So far, I was able to reproduce any HTTP error / status in VLC as well.

**Comment by shocker2** [comment]
> I have no idea how Emby's load balancing works. I also do not know what that has to do with xTeVe.
> xTeVe is written in Go, memory management is garbage collection. 90% of your RAM will be the XMLTV files. Memory management is handled by your operating system. If no other program requires memory, there is no reason for the OS to release the memory.
> 
> Service Unavailable: Is an HTTP status, all connections to the server are HTTP connections, if the status is not OK, the connection is closed and status is in the log. So far, I was able to reproduce any HTTP error / status in VLC as well.

I'm running 3 xteve on different ports on a single machine. Before one of xteve crash that process is eating up the entire OS ram. Killing the xteve process is freeing up the RAM. I think this has to do with the streaming buffer. I'll try to disable this functionality to see if that's the cause of the crash.

**Comment by mar-mei** [comment]
Did you activate Linux swap?

**Comment by shocker2** [comment]
Yes, it’s activated

**Comment by shocker2** [comment]
I have disabled the new v2 feature streaming buffer and everything is back to normal. Xteve is stable for the latest days, no more crash. I think the new functionality is heaving and issue. I'm using it with Emby latest beta version.

**Comment by mar-mei** [comment]
In a few days there will be an update for the buffer. Then FFmpeg and VLC can be selected.
![image](https://user-images.githubusercontent.com/43099631/66593594-94c46a00-eb97-11e9-89ef-93d98f9f096a.png)

**Comment by merrychrishna** [comment]
this is happening to me too with the newest version. how can i fix it please? i have 2 instances of xteve on different ports . its fixed if i remove the m3u file. but then i cant add the m3u back to xteve after.

**Comment by merrychrishna** [comment]
![image](https://user-images.githubusercontent.com/59185469/175752115-484e0334-1521-467a-9f4b-a672764ea35e.png)
