### ISSUE TITLE
xTeVe does not recognize tvg-chno attribute

### ISSUE THREAD

**Issue by rpelletierrefocus** [xteve-project/xTeVe#162]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). 
Emby, using tvheadend as the playlist source

**Describe the bug**
Maybe not a bug, but xTeve just numbers all channels starting from 1000. I expected it to use the tvg-chno attribute of available. If xTeve does not recognize this attribute can this be changed to a feature request?

**Server (please complete the following information):**
- Ubuntu
- Intel 64 Bit
- latest

**Comment by mar-mei** [comment]
That's right, it's not a bug.
With multiple playlists, channel numbers may be duplicated. Then what would be the right one?
xTeVe uses the order of the channels in the M3U. The filter also has an influence on the import of the channels. Every new channel from a new filter gets the first free channel number from 1000. The channel numbers can be edited in the mapping menu, so everyone can create their own order.

**Comment by grbharati** [comment]
Is it possible to start the channel number from user input, such as starting from 3000 or so. In emby, the channel number gets priority instead of tvg-name when mapping the channels to use with emby guide and creates an issue if there are channels in that 1000 range.

**Comment by army1349** [comment]
> 
> 
> That's right, it's not a bug.
> With multiple playlists, channel numbers may be duplicated. Then what would be the right one?

Please reconsider. Relative order could still be based on tvg-chno.
> The channel numbers can be edited in the mapping menu, so everyone can create their own order.

This is not suitable for highly dynamic playlists.
