### ISSUE TITLE
Server retured 404 not found

### ISSUE THREAD

**Issue by Djskynet9** [xteve-project/xTeVe#167]
Have been facing some issues over the past few days and not sure what settings I can change to fix that. I have used the same playlist for some time so this is odd. Some streams return a 404 error while run thru Xteve. If I run the playlist directly to the client, whether live channel (via tvirl) or tivimate, the same streams run perfectly. 

Current settings are as follows
Stream buffer - no buffer
Buffer size - 2m
Timeout for new clients - 500

**Comment by MCTyler** [comment]
Some Providers Block xTeVe as a user-agent. Play around with that setting...They will also block some Server Instances if your using that. In other words, they don't want you re-streaming their streams. 404 is not an xTeVe issue, it's your provider this can be closed.

**Comment by Djskynet9** [comment]
The issue is limited to specific channel, not the whole line up from the provider though (half of the US line up but the rest of international and US channels work fine so this seems off

**Comment by MCTyler** [comment]
https://en.m.wikipedia.org/wiki/HTTP_404

**Comment by mar-mei** [comment]
@Djskynet9 You can find the streaming URL with the 404 status in the xTeVe log. With Curl you can check every HTTP connection, including your streaming URLs. Curl should be run on the same PC that xTeVe is running on.
https://linuxize.com/post/curl-command-examples/
```
curl http://some.url --output some.file
```

**Comment by merrychrishna** [comment]
im having the same problem. what exactly could they be blocking? my mac address? i dont know what you mean by server instances @mar-mei
