### ISSUE TITLE
Expiration date

### ISSUE THREAD

**Issue by jeromim** [xteve-project/xTeVe#168]
1- It would be possible to add in the USERS part, when adding new user an expiration date. Give access to the USER with a predefined access time. after the end of the date access will be revoked

2 - within the user limit the maximum number of connections for the user. If I pass the list to someone only 1 user will have access. I can define the number of connections

thank you

**Comment by MCTyler** [comment]
xTeVe is not intended to be used as a Media Server

**Comment by mar-mei** [comment]
If you want to start a business this is the wrong software ;)

**Comment by jeromim** [comment]
it is not to earn money, from time to time I send the list to some friends to use to watch different channels like soccer, I want to limit my list to only one, they can pass this list to other users of the family for example. my intention is not to make money, it never was. just limit access to those who pass a list of my VU + UNO 4K.

**Comment by MCTyler** [comment]
See my Comment....

**Comment by jeromim** [comment]
i have a VU + uno 4k with support for 8 demodulators, ie 8 list (m3u8) i share with friends and family, i use xteve as m3u8 manager and program for my plex. I would like to know if they are sharing my m3u8 to others, as there are only 8 channels that my device supports. As much as I trust my friends and family I want to be sure heheh
If it were possible to identify it would be of great help, or even in the option users to have an option of how many connections per users.
