### ISSUE TITLE
Support for "tvg-shift" attribute in channel list

### ISSUE THREAD

**Issue by bradsjm** [xteve-project/xTeVe#17]
Is it possible to get support for the "tvg-shift" in m3u files, which clients use to shift EPG data by a certain number of hours for a given channel.

I'm using iptv-epg for my guide data, and they've got the ability to shift individual channels if the data is off for those channels only... But instead of updating the guide itself, they just add it to the m3u file in the form of a new element. Example:

#EXTINF:-1 tvg-id="RTEOne.ie" tvg-name="RTE One IE" tvg-logo="http://static.iptv-e.../RTEOne.ie.png"tvg-chno="112" __tvg-shift="-1"__ group-title="Ireland",RTE One 

Today xTeVe ignores this parameter and does not pass it through so even apps that support it like Tivimate do not show the time shift.

Ideally, xTeVe would process the shift internally and shift the time in the EPG so that it works with all clients regardless of their support. It should also expose this setting in the UI for manual adjustment.

**Comment by xteve-project** [comment]
No, this is not possible.  xTeVe allows XMLTV files from different providers to use, so the time shift in the M3U is no longer valid.  An XMLTV file also includes the value of the time shift, if the time is correct on the client, the time shift is also calculated.

XMLTV File:
```XML
<programme channel="1" start="20190608004300 +0200" stop="20190608004500 +0200">
    ...
</programme>

```

**Comment by GroupMaster** [comment]
This is a serious issue that I am running into and there doesn't seem to be a simple or realistic fix. According to other sources I have read recently, the time shift should be done in the m3u **ONLY** and never in the XML. For server overhead reasons, this is very agreeable. To change 1 static entry is fine opposed to potentially thousands, even hundreds of thousands of XML entries on EVERY update, which is insane, even programmatically!! 

The start/stop times in the XML area indeed correct but these times are for the area the channel is designated for. So if I want an ABC station from California but I am in NY, the guide is 3 hours off. There is no adjustment in xteve and xteve ignores the tvg-shift directives in the initial m3u. So my guide is wrong and there is nothing I can currently do about it besides editing the xteve playlist before plex gets it, which is unrealistic. 

Why can't this option for the shift be used? It is a per channel setting. If you get epg from provider "A" or "B", the start/stop times for that channel should be the same regardless. And it's not like the XML is going to be from 1 provider one minute and then another the next without the user changing it. Simply put, the m3u shouldn't have anything to do with the XML data besides each channel's m3u's tvg-id.

So right now it seems that tvg-shift is required if a lineup covers channels from more than 1 time zone. Maybe someone has something to add or suggest?

**Comment by niallobr** [comment]
Would be great if this could be reviewed again. What @GroupMaster said seems to make sense. I just need to shift a couple of channels and tvg-shift seems to be the most common/supported way of doing this among the various clients/providers.
