### ISSUE TITLE
Reading large XMLEPG file uses multiple GB of memory. 

### ISSUE THREAD

**Issue by Masssssy** [xteve-project/xTeVe#170]
**Describe the bug**
xTeVe uses ridiculous amounts of memory when parsing large XMLTV files causing the following error randomly if there is not many gigabytes of memory to spare. Crashes both xTeVe and anything else that might be running on the same server. It should be possible to parse the file without putting gigabytes of data in memory. Currently the following file would have to be preprocessed by a "smarter" parser. 

2020/08/28 14:01:02 [xTeVe] All streams:           21289
2020/08/28 14:01:02 [xTeVe] Active streams:        220
2020/08/28 14:01:02 [xTeVe] Filter:                2
2020/08/28 14:01:02 [xTeVe] XEPG:                  Parse XMLTV file: XMLTV
fatal error: runtime: out of memory

**Server (please complete the following information):**
- Linux Ubuntu
- 64 bit
- xTeVe 2.1.2 Build 0121

**To Reproduce**
Add a large epg.xml into the available XMLTV sources. Watch the memory eat away using e.g command "free". 

**Expected behavior**
xTeVe will use very much memory, possibly crashing xTeVe itself and other things running on the server,

**Additional context**

**Comment by mar-mei** [comment]
xTeVe is written in Go. Go uses garbage collection for memory management. Means the OS manages the memory. The important thing is that the OS must support garbage collection and swap must be activated.

Files that are processed in Go require about 3 times as much memory as the file size.
```
ls  -lh | grep xml
-rw-r--r--  1 xteve nobody   119M Aug 29 04:03 guide2go_deu.xml
-rw-r--r--  1 xteve nobody    69M Aug 29 04:47 guide2go_deu2.xml
-rw-r--r--  1 xteve nobody   131M Aug 29 04:35 guide2go_uk.xml
-rw-r--r--  1 xteve nobody   198M Aug 29 04:23 guide2go_us.xml

```
Top memory: 1752M
```
last pid: 56225;  load averages:  0.59,  0.48,  0.41                                          up 89+20:10:34  10:13:01
18 processes:  1 running, 17 sleeping
CPU:  0.4% user,  0.0% nice,  0.2% system,  0.1% interrupt, 99.3% idle
Mem: 1465M Active, 598M Inact, 171M Laundry, 27G Wired, 2361M Free
ARC: 23G Total, 3595M MFU, 18G MRU, 4480K Anon, 393M Header, 1108M Other
     20G Compressed, 29G Uncompressed, 1.43:1 Ratio
Swap: 4096M Total, 1139M Used, 2957M Free, 27% Inuse

  PID USERNAME    THR PRI NICE   SIZE    RES STATE  C    TIME   WCPU COMMAND
56142 xteve       14  52     0  2391M  1752M uwait  2  203:41  0.00% xteve

```

**Comment by MCTyler** [comment]
FWIW, I have 3 HUGE XML's loaded in xTeVe and it has never crashed, but Memory is Cheap, I have 32Gb.

**Comment by Masssssy** [comment]
Ok, it seems this is a feature rather than a bug then. It's a bit annoying to not be able to load large XML guides on servers with smaller amounts of memory installed. There are ways to parse XML that does not need to put the entire file in memory, not sure about how well that would work in Go though.

**Comment by MCTyler** [comment]
Go uses Memory the same as Java...

**Comment by genu** [comment]
> There are ways to parse XML that does not need to put the entire file in memory, not sure about how well that would work in Go though.

I think this part is key here. Even with Java, loading XML in memory has limitations. 

Rather than loading large XML files in memory, buffering can used to not exhausted available memory. There are strategies for this, i'm sure there are some examples for Go as well.
