### ISSUE TITLE
Got ffmpeg errors and Plex stream recording fails

### ISSUE THREAD

**Issue by SuberSeb** [xteve-project/xTeVe#173]
I'm using xteve in docker container on my unraid server. When I'm trying to record any of tv shows in Plex, after some time I got this error:
[xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204
After this error iptv stream fails and recording stops. How can I manage this error?

**Comment by MCTyler** [comment]
Change the Buffer to xTeVe Buffer.

**Comment by mar-mei** [comment]
@SuberSeb The error message comes when FFmpeg terminates the connection to the streaming server. Maybe it helps to look at the FFmpeg log. If you start xTeVe in debug mode 3, you can see what FFmpeg does.
