### ISSUE TITLE
m3u8 Stream does not work

### ISSUE THREAD

**Issue by defuuss** [xteve-project/xTeVe#177]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

I try to add this free stream

https://live-edge.rtl.lu/channel1/smil:channel1/1080p.m3u

I don't get an error message but i get no streams. 

I don't know where the problem is 

In vlc the stream works without a problem

xTeVe: | 2.1.2

**Comment by mar-mei** [comment]
M3U8/HLS streams only works with buffer.
The URL doesn't work for me with VLC
![grafik](https://user-images.githubusercontent.com/43099631/95505381-89746c00-09ae-11eb-8042-4c27f9e11599.png)

**Comment by defuuss** [comment]
Sorry , my bad copy paste error 
https://live-edge.rtl.lu/channel1/smil:channel1/1080p.m3u8

**Comment by mar-mei** [comment]
Where exactly did you enter the link, the stream works for me.
![grafik](https://user-images.githubusercontent.com/43099631/95565042-ea885800-0a1f-11eb-85d5-c071c5f1689b.png)

**Comment by defuuss** [comment]
I just add it here 
![1](https://user-images.githubusercontent.com/4477023/95566808-5d92ce00-0a22-11eb-80a2-338b0dd07e16.jpg)

![2](https://user-images.githubusercontent.com/4477023/95566841-671c3600-0a22-11eb-881e-70c8796b57f3.jpg)

**Comment by mar-mei** [comment]
Only M3U playlists can be entered there. M3U is not the same as M3U8. M3U8 are playlists for single streams. M3U playlists contain several streams, which can then also be M3U8 streams.

**Comment by defuuss** [comment]
Ah ok , that does explain why i don't work , where do I have to enter then the single stream maybe stupid question :-/ sorry for that

**Comment by mar-mei** [comment]
You have to create your own M3U playlist.

**Comment by defuuss** [comment]
Ok thank you so much for the support , my bad 
Read the fuc****ing manual .....

Thank you
