### ISSUE TITLE
DVR shows up in Plex for a few seconds then disappears.

### ISSUE THREAD

**Issue by chukaism** [xteve-project/xTeVe#18]
Not sure what's going on, and the logs aren't giving any feedback. During setup in Plex, the xTeVe DVR shows up for a second on the selection screen, then promptly disappears. Even a manual address add does not work.

**Comment by mar-mei** [comment]
I can not help you, that's a Plex problem. Look in the Plex Log, maybe you'll find the reason there.

**Comment by chukaism** [comment]
Sorry about that. I figured it out anyway just in case anyone else has this problem. If you have a tuner already connected it'll override your xTeVe DVR. Unplug/turn it off and everything should work.

**Comment by chinochao** [comment]
Do you have commands you ran? Your solution isn't very helpful. I am having the same issue and I get this on the logs.


Oct 23, 2019 03:20:37.577 [0x7f25fb7fe700] DEBUG - DVR:Device: Testing grabber HDHomerun device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST at http://192.168.2.21:34400
Oct 23, 2019 03:20:37.577 [0x7f25fb7fe700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST was already known, refreshing database info
Oct 23, 2019 03:20:37.578 [0x7f25fb7fe700] DEBUG - DVR:Device: Testing grabber HDHomerun device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST:2 at http://localhost:34400
Oct 23, 2019 03:20:37.578 [0x7f25fb7fe700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST:2 was already known, refreshing database info
Oct 23, 2019 03:20:37.578 [0x7f25fb7fe700] DEBUG - DVR:Device: Testing grabber HDHomerun device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST:5 at http://localhost:34400
Oct 23, 2019 03:20:37.578 [0x7f25fb7fe700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST:5 was already known, refreshing database info
Oct 23, 2019 03:20:37.580 [0x7f25fb7fe700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST died
Oct 23, 2019 03:20:37.583 [0x7f25fb7fe700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST:2 died
Oct 23, 2019 03:20:37.585 [0x7f25fb7fe700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/2019-10-AW01-T5G6ST:5 died

**Comment by chinochao** [comment]
I was able to find a solution. 

Stop plexmediaserver
Remove all the .db-shm and .db-wal from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases
Start plexmediaserver, the db files removed will be recreated and the DVR will be discovered
