### ISSUE TITLE
Unable to configure protocol

### ISSUE THREAD

**Issue by troykelly** [xteve-project/xTeVe#183]
**Is your feature request related to a problem? Please describe.**
All output is forced to be insecure HTTP protocol rather than configurable as HTTP/HTTPS

**Describe the solution you'd like**
I'm unfamiliar with GO - but it appears that the protocol is partially configurable at design time - but not once compiled.
https://github.com/xteve-project/xTeVe/blob/71dfe912722f3aa7cf10a3764bcd86867ee32fa4/src/config.go#L44

**Describe alternatives you've considered**
I've looked at the configuration files - but none appear to support the definition of the protocol

**Additional context**
When serving xTeVe content from a secure proxy, PLEX will not follow HTTP -> HTTPS redirects.

**Comment by mar-mei** [comment]
There was once the consideration to implement TLS. Since only a few clients still accept self-signed certificates, one would also have to implement Letsencrypt into xTeVe to enable TSL without pain.
Sorry, too much effort for me.

**Comment by troykelly** [comment]
It's already implemented with Caddy.
I'm using TLS now with no effort - I just need a way to remove the hard coded http.
