### ISSUE TITLE
ffmpeg subtitle option

### ISSUE THREAD

**Issue by thenamelessthing** [xteve-project/xTeVe#184]
Hi, sorry to ask here but I doesn't found any other how to maybe get some help about this specific use case.

I'm under Ubuntu 20.04, when I watch channel from xteve (with ffmpeg) to subtitle are by defaulyt enable and this cause transcoding. I have to set none for subtitle manually each time to direct play.  Is there an option to select by default no subtitle or completly disable sub stream?

When I keep subtitle the stream stop after 1-2 min, If I chose "none" for subtitle the stream play fine.

Any ideas?

Thank you !

**Comment by stevehop** [comment]
You can use the following ffmpeg options with Xteve to only keep video and audio:
-hide_banner -loglevel error -i [URL] -map :v -map :a -ignore_unknown -c copy -f mpegts pipe:1

**Comment by thenamelessthing** [comment]
That's seems to do it! Thank you!
