### ISSUE TITLE
xTeVe + Plex rtp stream

### ISSUE THREAD

**Issue by crazylenni** [xteve-project/xTeVe#19]
**Describe the bug**
When clicking play in Plex i receive an error that there will be no playback. In XTeVe i get error: 2004 that rtp streams are not supported.

**Server (please complete the following information):**
- Synology with Docker
- XTeVe 2.0.2

2019-08-28 10:44:33 [xTeVe] [ERROR] RTSP and RTP streams are not supported (Buffer is disabled for this stream.) - EC: 2004
2019-08-28 10:44:33 [xTeVe] Streaming URL:         rtp://@239.35.20.38:10000
2019-08-28 10:44:33 [xTeVe] Streaming Info:        URL was passed to the client

**Comment by mar-mei** [comment]
I do not understand. The log says that RTP streams are not supported.

**Comment by keisersuze** [comment]
I have the same problem too.
When xTeve create the M3U file, why xTeve rewrite the RTP source ? For exemple, in my original M3U file, i have this for a channel:
`#EXTINF:-1 tvg-id="RTS1.ch" tvg-name="RTS un CH" tvg-logo="http://static.iptv-epg.com/ch/RTS1.ch.png" tvg-chno="92" channel-id="92",RTS1 HD
rtp://239.186.68.3:10000`

And after xTeve compilation, i have this:
`#EXTINF:0 channelID="x-ID.1" tvg-chno="1001" tvg-name="RTS1 HD" tvg-id="1001" tvg-logo="//i.imgur.com/dVkikAF.png" group-title="",RTS1 HD
http://192.168.1.133:34400/stream/34b944eaeb4cb499ff6858ebc6c42f6e`

I tried xTeve version with VLC and it doesn't work.
There is my M3U file: https://iptv-ch.github.io/swisscom-hd.m3u

**Comment by mar-mei** [comment]
Update to version 2.1.0 and select VLC or FFmpeg as the buffer.

**Comment by keisersuze** [comment]
Is it possible to push this version on Docker ? Thank you!

**Comment by mar-mei** [comment]
https://github.com/xteve-project/xTeVe#recommended-docker-image-linux-64-bit
