### ISSUE TITLE
Channel number by user instead of 1000

### ISSUE THREAD

**Issue by grbharati** [xteve-project/xTeVe#192]
Can we provide users a choice to have a channel start number instead of 1000.

The issue with 1000 is that the EMBY prioritizes channel number instead of the channel name when using the EMBY guide. In that case, we have to manually change all the channel numbers in the xteve (i.e unused in the guide) like 3000+. In GUI, I am not able to figure out the process of automating the channel numbers. If that is already there, please let me know, else it would be a nice feature to have. I hope EMBY team is also working on this issue to have a fix.

**Comment by mar-mei** [comment]
The value can be changed in the settings.json.
```
"mapping.first.channel": 1000,
```

**Comment by grbharati** [comment]
I was able to change it and it got reflected in all my channels after I re-added the playlist.
Thankyou mar-mei
