### ISSUE TITLE
updating XMLTV after the playlist update doesn't activate the channels

### ISSUE THREAD

**Issue by grbharati** [xteve-project/xTeVe#193]
Hi,
My plan is to use GUIDE from EMBY. I cannot use PMS because I also want to use the m3u groupings. Hence, I am creating my own dummy XML file for the XMLTV so that the channels remain active(I don't have the actual EPG data from the provider), which is autogenerated based on the channels. I understand I can use dummy EPG from xTeVe, but it had some limitations ( I actually forgot, it has been a while that I haven't used the dummy guide). Anyway, my main focus is on channels that are not available regularly, like live games.

Let me provide a scenario and I guess it will be easier for me to explain the issue:
Channel 1, Channel 2, Channel 3 are providing live games on day 1. On day 2, there are different games on those channels and the provider will change the name, because of which xTeVe will deactivate the channel. It makes sense because there is no guide data for those channels.
To circumvent that, I edit my m3u file before importing it in xTeVe. In the m3u file, I edit "tvg-id" and "channel-id" and create a corresponding XML file, which is just dummy data. Unlike the xTeVe dummy guide, it has preconfigured ids so that xTeVe should automap it.

The issue I am having is:
If I first update the XMLTV file before the playlist, the mapping is done and the channels are active
but if I update the playlist before updating the XMLTV, the mapping is not done and hence the channels are not active for those changed channels. If I delete the playlist and add it, then the channels are mapped and active. I also delete the channels that are not showing any live matches, in that case, if those channels reappear next time they are also not mapped properly. But if I follow the order: update XMLTV and then playlist, they are mapped and active.

Is this a bug or is expected?

when auto-updating, what is the order, does xmltv updates first or the playlist?

Thank you,

**Comment by grbharati** [comment]
With quick tests, the automatic update of playlist and XMLTV does update playlist first. Is there a way to reverse it?

**Comment by grbharati** [comment]
I can find cron job to download the xmltv and playlist but not able to figure out the cron job to actually update them in xteve. Where is the location of cron job for actual update?

**Comment by mar-mei** [comment]
Within xTeVe there are three functions to update everything:
1. Update M3U / HDHomeRun files
2. Update xmltv files
3. Put data together and generate the lineup for Plex, xteve.m3u, xteve.xml

As long as no IDs change with the M3U and XMLTV sources, the order does not matter.
If the channel names change again and again, it is recommended that each stream in the M3U has a unique ID that never changes. Without this ID, the channel name is always used for the xTeVe mapping. With this ID, xTeVe can also take over the changed channel name and adapt it for Plex, xteve.m3u, xteve.xml.

xTeVe does not use cron jobs. The schedule for updating the data can be changed in the xTeVe settings.

If it should be more flexible, you can use the xteve API. With the API sources can be updated in any order and then the Plex, M3U lineup can be generated.

API:
https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/configuration.md#api

**Comment by grbharati** [comment]
Thank you mar-mei: For the live channels, I want the name to change as it is provided by the providers, as it provides the game time and teams playing. 
I think I have more control over the order in the API. I will give that a try. Never used one before, but documentation is good so I hope I can make it.
