### ISSUE TITLE
Feature request: Update plex channels and guide

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#195]
**Is your feature request related to a problem? Please describe.**
Some m3u list are more dynamic, such as when sports streams are live or about to go live (more channels can be present). These get added to xteve fine when it updates the m3u and even ties it to the correct epg information (as long as it's present); however Plex isn't "smart" enough to automatically enable to the new channels.

**Describe the solution you'd like**
I believe it's possible to use plex's api to trigger channel and guide updates. It seems that dizquetv (https://github.com/vexorian/dizquetv)is doing this. I have it disabled in this screenshot because I'm feeding the m3u and xml into xteve to create a combined m3u and xml.
![image](https://user-images.githubusercontent.com/42013603/102634392-c469ed00-411f-11eb-8bfc-ad02d6ec60ff.png)

**Describe alternatives you've considered**
Triggering the xml could be accomplished in the DVR settings by changing the update interval to every 15 minutes or so. Not sure how to go about the channel update in an automated way.

**Additional context**
Here is the javascript code that I believe connects to and updates plex.
https://github.com/vexorian/dizquetv/blob/main/src/plex.js

**Comment by mar-mei** [comment]
It is not planned that xTeVe will communicate with other programs or services via API interfaces. It would be too much effort to adapt every API change in xTeVe in the future.

Therefore xTeVe does not support any other "helpful" APIs from Emby, XC or Schedules Direct.

**Comment by ReenigneArcher** [comment]
I understand. I'll try to adapt the dizquetv script in python.
