### ISSUE TITLE
Feature request: channel numbers

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#196]
**Is your feature request related to a problem? Please describe.**
I'd like a way to give channel numbers the same (or very close) to the original numbering method. I know we can add a decimal to the channel numbers which is great. One problem is that when you add a number like 1.1, 1.01, and 1.001. In xTeve this is sorted corrrectly (smallest to largest); however in Plex it get sorted differently.

**Describe the solution you'd like**
Three ideas. Not sure if they're possible.

Idea1 - add the ability to prefix the channel with a letter. This would allow to sort of group channels. "b" could be for broadcast, "d" could be dizquetv, "L" could be for local, etc. Of course give the user the option to select whatever prefix they want for a given channel.

Idea2 - add the ability to enter a channel name like 1.100 (keeping the trailing zeroes)

Idea3 - add the ability to enter 2 decimal places in a number. i.e. 2.5.8 (combine with Idea2 to keep trailing zeroes)

**Describe alternatives you've considered**
none

**Additional context**
Correct order in xteve
![image](https://user-images.githubusercontent.com/42013603/102640715-ec118300-4128-11eb-8cd0-4be62d867843.png)

Incorrect order in plex
![image](https://user-images.githubusercontent.com/42013603/102640830-106d5f80-4129-11eb-950c-3c3f2f28a85b.png)

**Comment by mar-mei** [comment]
To me, this looks like a bug in Plex.

xTeVe uses the sorting function of Javascript in the web interface and Golang in the backend.

The channel numbers are interpreted as floating numbers, so they cannot contain letters or multiple dots.
If the number of numbers after the point were always 4 digits, the UI would be broken in many Plex clients.

![grafik](https://user-images.githubusercontent.com/43099631/102690740-be4f3b80-4207-11eb-9f8f-7f79be4f10ef.png)

**Comment by ReenigneArcher** [comment]
I see... So what happens with trailing zeros? I'm not familiar with javascript floating numbers. It would be nice to be able to have 1.100 for example.

**Comment by ReenigneArcher** [comment]
Alternatively would it be possible to make xteve obey the `tvg-chno=""` tag from the m3u (assuming the channel number specified is free?

**Comment by mar-mei** [comment]
That just makes things more complicated. When using several playlists, the channel number can appear twice. Which channel is then the correct "100"

**Comment by ReenigneArcher** [comment]
Maybe it's possible to handle it the same way as when you manually enter a channel number that's already used.

If 100 is already used, and 100 is entered again... it uses 101 (and if 101 is already used it will use the next available number).

If 101.1 is already used and 101.1 is entered again it used 101.2 (or the next available).
