### ISSUE TITLE
Feature request: Add streamlink as a buffer agent

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#198]
**Is your feature request related to a problem? Please describe.**
Some types of streams do not play well in xteve, ffmpeg or vlc. For example some streams have problems when commercials start as the bitrate, resolution, etc. are changed. There are reports like this everywhere on the internet. (example: https://emby.media/community/index.php?/topic/87992-pluto-tv-xml-guide-resource/&do=findComment&comment=900232)

**Describe the solution you'd like**
Streamlink (https://github.com/streamlink/streamlink) offers many plugins for various types of input streams and pipes the video to other player applications.

In addition to adding Streamlink as a buffer agent, it would be nice to select a buffer agent for each playlist or even individual channels.

There could be a global buffer setting, playlist buffer setting, individual buffer setting. If the lower level setting is blank it could use the next level up. Possibly rules could be set for the buffer similar to filtering the m3u channels. For example if the url contains a certain string.

**Describe alternatives you've considered**
Trying to build a 2 year old version of ffmpeg from source that apparently handles discontinuous streams better. (https://emby.media/community/index.php?/topic/87992-pluto-tv-xml-guide-resource/&do=findComment&comment=904049)

**Additional context**

**Comment by ReenigneArcher** [comment]
I tried to add the streamlink buffer agent portion of this in a fork. I am missing something. The new settings appear in the settings.json and applies the default settings as well. I'm missing something with getting the settings ui updated. The new buffer doesn't appear in the drop down list, and the new buffer path and options also don't show in the ui.

Happy to push the commits once I get that final part figured out. Any idea?

https://github.com/ReenigneArcher/xTeVe/commits/master

Also found that I can just specify the streamlink.exe path instead of ffmpeg or vlc, and use this as the command. `--stdout [URL] --default-stream best` ... but would be nice to have a separate section for it to make testing different buffers easier. I believe it's sending the stream in mpegts as I'm able to play the streams in Plex which I cannot play when no buffer is used.

**Comment by mar-mei** [comment]
![grafik](https://user-images.githubusercontent.com/43099631/102935419-65510300-44a6-11eb-8d70-eb7145493383.png)
I implemented it quickly. With Streamlink there is also the possibility to set a user agent?

**Comment by ReenigneArcher** [comment]
Awesome! And yes you can in the command line. https://streamlink.github.io/cli.html
![image](https://user-images.githubusercontent.com/42013603/102936554-5ce0d400-4476-11eb-9b68-3117d10d37c1.png)

So would add --http-header "User-Agent=Chome" for example.

Stream urls may need to be modified to work with streamlink.
For example... for my NextPVR and DizqueTV streams I had to prepend the urls with "httpstream://" + original url (including http://)
For some playlists I had to prepend the urls with "hls://"

And for others plugins the url needs to be in the convention they require. I couldn't find the url conventions in the documentation, but looking into the source it's not too difficult to figure out. (https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins)... Pluto.tv links need to be in the format `pluto.tv/live-tv/<channelSlug>` just as an example.

![image](https://user-images.githubusercontent.com/42013603/102937155-83ebd580-4477-11eb-9eb6-f126c8e3face.png)
Streamlink supports these protocols (plus all their plugins).
![image](https://user-images.githubusercontent.com/42013603/102937222-a978df00-4477-11eb-9e45-b9f6e8b4543c.png)

**Comment by ReenigneArcher** [comment]
And some more info:

This is what I'm using for the command... `--stdout --loglevel debug [URL] --default-stream best`
"Valid levels are: none, error, warning, info, debug, trace"

And I've had the best luck with a 0.5mb buffer.

**Comment by mar-mei** [comment]
I have bad news. TS streams do not work with Streamlink. You would have to change the URL for TS Streams. However, the URL does not indicate which video format it is. If the links are not handle same, this cannot be implemented.

Working TS stream:
```
streamlink "httpstream://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4?ch=1000" best
```

Working HLS stream:
```
streamlink "https://mcdn.daserste.de/daserste/de/master.m3u8" best
```

**Comment by ReenigneArcher** [comment]
The user just needs to prepend the playlist stream urls with the protocol if it's not there already.

I am going to write a python script that does this automatically and takes a couple of arguments.

-originalM3Uurl
-outputFile
-protocol (enter the protocol, applies to entire list)
-automatic (find the protocol for each stream automatically, slower)

Your second link would be better like this (assuming there is no plugin for mcdn.daserste.de):

streamlink "hls://https://mcdn.daserste.de/daserste/de/master.m3u8" best
