### ISSUE TITLE
cvlc not working for plex, defaults selected

### ISSUE THREAD

**Issue by syadnom** [xteve-project/xTeVe#199]
This is with plex client.  xteve works perfectly with xteve and ffmpeg, but cvlc fails, showing a 'fail to tune channel' in plex.

- xTeVe Version and Build [to be found in the xTeVe log]
ubuntu 20.04
intel 64 / 10th gen
xteve 2.1.2

Set stream buffer to cvlc
**Expected behavior**
behave just like ffmpeg as far as plex is concerned.

vlc / cvlc IS installed.  path matches default at /usr/bin/cvlc

**Comment by mar-mei** [comment]
Probably the stream is not compatible with Plex. Take a look at the Plex log.

**Comment by syadnom** [comment]
I found that cvlc didn't like the options so I changed those up and got it kind of working, but vlc-wrapper does take the same switches so back to default options but /usr/bin/vlc-wrapper and that works properly.   

btw, plex log gave me nothing but xteve's own log showed cvlc bailing out.
