### ISSUE TITLE
Catch-up support?

### ISSUE THREAD

**Issue by Radix93** [xteve-project/xTeVe#20]
If an IPTV provider supports catch-up, should this work via xteve assuming the player supports it?  I've been unable to get it working so far.

**Comment by mar-mei** [comment]
catch-up is read by xTeVe, but not written to xteve.m3u. Which client supports that?

**Comment by Radix93** [comment]
I've been using xteve with Tivimate on an Nvidia Shield, and it works great except for catchup.  xteve is a great alternative to something like xtream-editor, but this is the only thing I've found that doesn't work as of now.  If you would like, I can provide wireshark traces of the http requests from a player, both failing against xteve and working against the provider natively.

**Comment by mar-mei** [comment]
That can not be implemented, Plex does not support that.
