### ISSUE TITLE
ISSUE: xteve.xml missing original xml details

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#204]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
keys from the original xml are not included in the xteve.xml

For example, I have this in my original xml in the programs.
```
		<rating system="TV Parental Guidelines">
			<value>TV-14</value>
			<icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/TV-14_icon.svg/240px-TV-14_icon.svg.png" />
		</rating>
```

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]: Win 10 Pro
- Arch [e.g. Intel 64 Bit]: 64 bit
- xTeVe Version and Build [to be found in the xTeVe log]: 2.1.2

**To Reproduce**
1. Add xml epg with rating key and map channels to it.
2. Wait for xteve to produce merged xml.

**Expected behavior**
All original details of programs should be included in xteve.xml.

**Screenshots**
1-Original (rating not added)
![image](https://user-images.githubusercontent.com/42013603/103374268-1fe39580-4aa5-11eb-9ffe-bfd38868e517.png)
1-Xteve version
![image](https://user-images.githubusercontent.com/42013603/103374399-810b6900-4aa5-11eb-8fda-879f426375b4.png)

2-Original (length not added... possibly redundant with start and stop times, but thought I'd point it out)
![image](https://user-images.githubusercontent.com/42013603/103374952-cf6d3780-4aa6-11eb-8104-da3037898a4f.png)
2-Xteve
![image](https://user-images.githubusercontent.com/42013603/103375078-34289200-4aa7-11eb-8a46-d05c897352bd.png)

**Desktop (please complete the following information):**

**Additional context**
XMLTV standard is here (https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd)

Also missing subtitles key (don't think there's anyway to access subtitles when playing through xteve though)... Could be others missing as well, this is just what I noticed.

**Comment by mar-mei** [comment]
Is already fixed in the beta
https://github.com/xteve-project/xTeVe#xteve-beta-branch
