### ISSUE TITLE
Category is not unset correctly in XMLTV output

### ISSUE THREAD

**Issue by beardypig** [xteve-project/xTeVe#209]
**Describe the bug**
If no category is set for a channel there is no `category` tag set in the `programmes` in the XMLTV output. However, if a category is set for a channel and later removed, the generate XMLTV file will have the category `"-"` instead of being omitted.

**Server (please complete the following information):**
OS: Linux
Arch: amd_x64
xTeVe: 2.1.2

**To Reproduce**
1. Set EPG source to XEPG.
2. Set a category for a channel in Mapping and Save
3. Save the XMLTV output
4. Unset the category (set to -) for that channel in Mapping and Save
5. Compare the previous XMLTV programmes output to the new one

**Expected behavior**
The category should be unset, and in both cases there should be no `category` or `episode-num` tags generated. The output should match the output before the category had been set. 

**Screenshots**

Before setting a category
```xml
<programme channel="666" start="20210114063000 +0100" stop="20210114070000 +0100">
  <title lang="en">News</title>
  <icon height="" src="http://192.168.1.9:34400/images/625c14fdee99a166fe03b9e4c8951fb8.png" width=""></icon>
  <video></video>
  <date></date>
</programme>
```

After setting a category
```xml
<programme channel="666" start="20210114063000 +0100" stop="20210114070000 +0100">
  <title lang="en">News</title>
  <category lang="en">News</category>
  <episode-num system="original-air-date">2021-01-14 06:30:00</episode-num>
  <icon height="" src="http://192.168.1.9:34400/images/625c14fdee99a166fe03b9e4c8951fb8.png" width=""></icon>
  <video></video>
  <date></date>
</programme>
```

After unsetting the category
```xml
<programme channel="666" start="20210114063000 +0100" stop="20210114070000 +0100">
  <title lang="en">News</title>
  <category lang="en">-</category>
  <episode-num system="original-air-date">2021-01-14 06:30:00</episode-num>
  <icon height="" src="http://192.168.1.9:34400/images/625c14fdee99a166fe03b9e4c8951fb8.png" width=""></icon>
  <video></video>
  <date></date>
</programme>
```

---

Keep up the good work, loving xTeVe!

**Comment by mar-mei** [comment]
Thanks, looks like a bug.
