### ISSUE TITLE
403 Forbidden Error when adding m3u playlist

### ISSUE THREAD

**Issue by jiggamaine** [xteve-project/xTeVe#212]
I keep getting "403: http://xxxxxx:80/xmltv.php? username=xxxxxxx&password=xxxxxx&type=m3u_plus&output=mpegts Forbidden when trying to add http: link for my playlist. I've deleted and reinstalled xteve on the machine and I still get the same error. I installed xteve on another virtual pc and Im still getting the same error. I've checked firewall and anti-virus settings. I then deleted the folder to start over and when I add the remote link for the m3u file, the web page spins and no error is displayed at the cmd line.

**Comment by mar-mei** [comment]
M3U or XMLTV? Your link looks like an XMLTV file. The M3U menu is for M3U files, the XMLTV menu for xmltv files. All status codes come from the server from which you want to download the file. xTeVe has no influence on this.
Here is an overview:
https://httpstatuses.com/

**Comment by beardypig** [comment]
Looks like an XC API call to me, you probably need `get.php` instead of `xmltv.php`. If that doesn't work then your provider uses a different XC API (XC Login perhaps) which doesn't allow m3u playlists.

**Comment by jiggamaine** [comment]
My apologies for not disclosing the entirety of the error. On a windows 10 PC, I receive this error when trying to add http: link for my playlist. "403: http://xxxxxx:80/get.php? username=xxxxxxx&password=xxxxxx&type=m3u_plus&output=mpegts Forbidden. so I downloaded a local copy and it accepted the local playlist. I don't know a way to download the xmltv file so I receive the same error: "403: http://xxxxxx:80/xmltv.php? username=xxxxxxx&password=xxxxxx&type=m3u_plus&output=mpegts Forbidden when I insert the http: link. I have deleted the 2.1.2 version and tried the 2.1.3 beta version and still receive the same error. I have tried this on a linux pc and still receive the same error.

**Comment by jiggamaine** [comment]
> Looks like an XC API call to me, you probably need `get.php` instead of `xmltv.php`. If that doesn't work then your provider uses a different XC API (XC Login perhaps) which doesn't allow m3u playlists.

**Comment by merrychrishna** [comment]
why did you close this? how did you fix it?

**Comment by MCTyler** [comment]
Use Pierre's IPTV Proxy for Xtream Login.
