### ISSUE TITLE
Xteve mapping not working with 2 playlists for local stations in different cities

### ISSUE THREAD

**Issue by eqpaisley** [xteve-project/xTeVe#216]
**Describe the bug**
xteve will not show local networks from multiple cities in the mapping interface when running locast2dvr. this is not a locast2dvr issue as I can directly import both M3Us into Jellyfin and see the local network are there and working fine.  Xteve 'sees' the channels and on the FILTER interface they appear, but they do not appear when mapping.

**Server (please complete the following information):**
Ubuntu 20  
64bit
2.1.2 Build: 0121

**To Reproduce**
add M3U with Los Angeles local networks (ABC, CBS, etc)
add M3U with New York local networks (ABC, CBS, etc)
go to FILTER to make sure you're filtered to use the networks
go to MAPPING 
either LA or NY stations will appear but not both

**Expected behavior**
Should be able to see BOTH sets of local networks.

**Screenshots**
2 playlists for local channels with 100% availability
![image](https://user-images.githubusercontent.com/5481431/107379519-00378800-6abb-11eb-9a0f-5729d2f75ff0.png)

Filtering for New York and Los Angeles NETWORK groups, you can see that Xteve sees networks for both cities
![image](https://user-images.githubusercontent.com/5481431/107379768-3ecd4280-6abb-11eb-8d00-5ab9ec4c2be5.png)

Mapping interface shows ONLY the Los Angeles stations
![image](https://user-images.githubusercontent.com/5481431/107379953-6fad7780-6abb-11eb-8147-473dbb95c6fc.png)

When you try to filter for New York stations, nothing appears:
![image](https://user-images.githubusercontent.com/5481431/107380267-b9965d80-6abb-11eb-99d3-dbd67d26f27a.png)

When ONLY the New York stations are loaded in:
![image](https://user-images.githubusercontent.com/5481431/107380516-ef3b4680-6abb-11eb-974a-550c8d7e02e2.png)

The New York networks show up just fine:
![image](https://user-images.githubusercontent.com/5481431/107380683-16921380-6abc-11eb-85f3-02eb983560af.png)

**Additional context**
Tried with LA and Chicago as well, whatever playlist is added 2nd, the networks for that playlist will not be available in mapping. As a side note, the NON NETWORK channels for the 2nd city are available.  Is there a naming conflict (CBS NY and CBS LA just show up as CBS in Xteve and therefore Xteve only shows the first one it sees?)

**Comment by wouterdebie** [comment]
As the author of locast2dvr I'm interested in this issue. If I can do anything to help, let me know. I've been exploring some remapping schemes with another user, but I'm not sure if remapping channels in locast2dvr is the way to go.

**Comment by mar-mei** [comment]
I see duplicate channel names, if the source M3U does not have unique IDs for the streams, the channel name is used for identification at the Mapping menu. Then no duplicate channel names may exist.

**Comment by wouterdebie** [comment]
@eqpaisley how do you run locast2dvr? Are you using the multiplex (-m) option? Have you tried remap (-r)?

**Comment by eqpaisley** [comment]
@wouterdebie  I'm using zipcode overrides in my config "11215, 91605"

**Comment by eqpaisley** [comment]
Looks like adding the `multiplex `and `remap `flags to locast2dvr allowed xteve to see that CBS LA and CBS NY were not the same channel.  Issue is solved. Not sure if there's anything xteve can do to differentiate in the future. 

![image](https://user-images.githubusercontent.com/5481431/107407850-2e779080-6ad8-11eb-8da9-6f1fe4ab783c.png)
