### ISSUE TITLE
2.0.3 Unable to set up Plex tuner

### ISSUE THREAD

**Issue by bmwtalenti** [xteve-project/xTeVe#22]
After update to 2.0.3 running on macOS, after executing xteve and get "Ready to use", when setting up tuner in "Live TV and DVR" on Plex launching "Scan channels" produce that channels are not found. Trying to do "Continue", it is unable to finish since Plex shows "Unknown status". 

I tried to remove every xteve file and starting from scratch. 
First attempt to set up the tuner in Plex was successful. Trying to make a second one after few changes  in channels filter on xteve, but not starting xteve from scratch, Plex does not manage to set up the tuner, as described above. 

Everything was so smooth on 2.0.2 which I've been using for around 15 days up to now. 
I do not understand also why, if I try to use the old 2.0.2 executable I backed up, it always try to update so then it runs 2.0.3. So every time there is an update, if there is a bug you are at dead end.

**Comment by mar-mei** [comment]
In version 2.0.3 nothing has changed what has to do with Plex.
The Scan Channels button in Plex has no function for xTeVe.
Plex has a bug when loading the xteve.xml file via the HTTP link.
https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/troubleshooting.md#plex-dvr-can-not-be-set-up-or-channels-are-missing

The update function can be deactivated in the xTeVe settings.

**Comment by bmwtalenti** [comment]
I know it does not affect xteve, but it signals it does not “broadcast” channels.
About the guide, I knew, I always set up with local path.

Strangely enough, however, now Plex manages to complete setup of the tuner BUT the guide which xteve is generating has all the channels but no programs!

By the way, thank you very much for your work.

**Comment by mar-mei** [comment]
Restart Plex and wait until the guide has been reloaded by Plex. Then reload the Plex web interface.

**Comment by bmwtalenti** [comment]
Sorry, maybe I did not describe last issue correctly.
xTeve guide is empty, just channels no programs. I read it with textedit. It is not a Plex issue.

**Comment by mar-mei** [comment]
If only the channels are included in the xteve.xml file then the program information is missing in the provider XMLTV file.
What happens if you use the xTeVe Dummy in the Mapping?

**Comment by bmwtalenti** [comment]
No it is not missing in the provider's file because xTeve indicates number of programs in that file. Plus I checked that file with textedit. It is the file generated by xteve which has this flaw.

**Comment by mar-mei** [comment]
Start `./xteve -info` post the output and the xteve.xml file

**Comment by bmwtalenti** [comment]
./xteve -info returns "No such file or directory" even if I can see it hidden in my home directory
I started xteve again and now xteve.xml file does not even have channels inside (see attached).
The provider's guide is fine (see xteve screenshot)

![Schermata 2019-09-08 alle 12 29 06](https://user-images.githubusercontent.com/55034855/64486949-518f7800-d234-11e9-964a-3ff202e02d59.png)
[xteve.xml.zip](https://github.com/xteve-project/xTeVe/files/3587514/xteve.xml.zip)

Look...the thing is...2.0.2 was the first one I used and was so smooth, I did just follow instructions and worked, whatever subsequent changes I made it kept working. Now it's just a mess I'm into hard debugging after 10 years being on a Mac...
It's for sure the new version to be blaimed because I didn't make any change in the last week, I was just starting it once a day and then it stopped working. Then I discovered it had autoupdated.
I just would like to downgrade to the old one. It is impossible because even if I remove everything and start from scratch, first time xteve execute it force the update to 2.0.3. Then, it lets me choose to disable autoupdate. I was wrong to enable autoupdate in the first place. 
Can you provide me with 2.0.2 that does not autoupdate?

**Comment by mar-mei** [comment]
The source code is here on GitHub. If you want 2.0.2, you have to build it yourself. I can not do a separate version for everyone.

You have to execute the command where the xTeVe binary is located.

The providers change their files every day.

xTeVe has 83 error messages with you, I would first look there what is going on.

**Comment by bmwtalenti** [comment]
The message is related to the fact that no channels were mapped, because they were inactive, but as I said, when I activate them, xteve does not build a new xml. The screenshot was taken before activating the channels, was just meant to show you that xteve reads correctly the provider's file.

Can you give me a link to instructions on how to build a version on Mac? I noticed that 2.0.2 here is beta(build 0024) not the the old master one. 

Sorry to bother you but and thanks for your immediate replies.

**Comment by mar-mei** [comment]
If your provider has changed so much, 2.0.2 will not help.
Perhaps you'll be lucky:
https://github.com/xteve-project/xTeVe/archive/2.0.2.0020.zip

https://github.com/xteve-project/xTeVe#build-from-source-code-go--golang
