### ISSUE TITLE
I can't filter channels.  I don't see a Group Title

### ISSUE THREAD

**Issue by fredericrous** [xteve-project/xTeVe#220]
**Describe the bug**
I can't filter channels.  I don't see a Group Title. (idk if it's a bug, surely an issue with my config? I'm new to xteve)

**Server (please complete the following information):**
- OS => Docker alturismo/xteve
- xTeVe Version and Build =>  2.1.2 Build: 0121

**To Reproduce**

xTeve tells me there are too many of channels, which is a good thing, that means channels were imported, aren't they?

```
2021-02-15 11:09:05 [xTeVe] [WARNING] xTeVe has loaded more than 480 streams. Use the filter to reduce the number of streams.
```

Here is a preview of the m3e file:

```
#EXTM3U
#EXTINF:0,2 - France 2 (auto)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201
#EXTINF:0,2 - France 2 (HD)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=hd
#EXTINF:0,2 - France 2 (standard)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=sd
```

here are the 2 different xmltv files I tried:

- http://allfrtv.fr.ht/xmltv/xmltv.xml
- http://xmltvfree.free.fr/xmltv.xml ( this one I downloaded, changed the encoding to utf-8 and imported it as a local file)

When I create a filter, I don't get a m3u group filter, the dropdown "Group Title:" has no option to select.

**Expected behavior**
I would expect a group title to be available

**Screenshots**
I'm seeing this red output at the right corner of the app. Because it's red, I believe there is an issue? there are no error in the logs.
![image](https://user-images.githubusercontent.com/702227/107936176-3cb32a00-6f7a-11eb-9086-75c78758a181.png)

**Comment by mar-mei** [comment]
Your M3U does not contain any groups **(group-title="some group")**. The group filter is only possible with an m3u plus file.
```
#EXTM3U
#EXTINF:-1 CUID="1000" tvg-id="news.channel.1" tvg-name="News Channel 1" tvg-logo="http://example.com/logo1.jpg" group-title="UK: News",News Channel 1 HD
http://example.com/stream1.ts
```

**Comment by fredericrous** [comment]
Thank you @mar-mei ! I created a custom filter with `{(HD)}` and I could get most of the channels, I'm gonna refine the filter and create others
