### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by tgillespie** [xteve-project/xTeVe#24]
Getting an error when I try to update my XMLTV.

`XML syntax error on line 314: Unexpected EOF`

**Comment by mar-mei** [comment]
There is a syntax error in your XMLTV file. The file can not be processed then.

**Comment by alpe12** [comment]
@mar-mei @xteve-project This is my xml. Can any of you tell me what is wrong with it so I can fix it? Thanks.
[iptv-epg.xml.gz](https://github.com/xteve-project/xTeVe/files/7859756/iptv-epg.xml.gz)
