### ISSUE TITLE
Make "GREEN" mappings sticky

### ISSUE THREAD

**Issue by gavinmcnair** [xteve-project/xTeVe#247]
**Is your feature request related to a problem? Please describe.**
If I set up channel mappings a change to the filter causes them to disappear

**Describe the solution you'd like**
I would like to be able to set up multiple mappings. Each of which adds a subset of matching channels. Once those channels are mapped to a guide (and goes green) i'd like that channel to be sticky in nature so that i can delete the filters again. This will make it easier to maintain the channel list.

**Describe alternatives you've considered**
Fixing the mappings.  The mappings seem to conflict with each other and do not appear to stack as expected.

**Additional context**
No please ask for more info. I just want to make settings things up simpler and more fault tolerant.

**Comment by winguru** [comment]
You can set up multiple M3U group filters, each selecting a subset of the channels for mapping, but deleting a filter is intended to also delete the respective channel mappings.  If it didn't work that way, there would be no way to remove channels mappings once created.

I'm not 100% clear on what you are looking to accomplish, but could it be that an M3U editor may be helpful in your use case?  xTeVe is great at proxying M3U files, but it's not designed to be as full featured as an M3U editor.

Hopefully that helps...

**Comment by gavinmcnair** [comment]
i see what you mean. An m3u editor might work well though I find only my first filter works properly. I  guess that's what I'm trying to work around.

**Comment by gavinmcnair** [comment]
I'll close this and possily raise another more relevant issue later
