### ISSUE TITLE
Remove/suppress 480 stream warning

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#261]
**Is your feature request related to a problem? Please describe.**

xTeVe continously warns that Plex cannot handle more than 480 streams. I believe this was an old limitation that Plex had, that no longer exists. I have close to 600 streams in Plex without any problem today.

**Describe the solution you'd like**

Possible ideas:
- Allow suppression of the warning
- Allow user to change the limit at which the warning occurs
- Don't have any warning at all considering the limit is not real

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/42013603/130518592-36f63ea8-d5d6-4a45-baa7-0eac60e0a738.png)

**Comment by MCTyler** [comment]
It doesn't hurt anything but I will ask Dev if he can remove it.
