### ISSUE TITLE
Have xteve respect tvg-chno from m3u

### ISSUE THREAD

**Issue by ReenigneArcher** [xteve-project/xTeVe#269]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to manually enter the channel numbers that already exist in my m3u lists.

**Describe the solution you'd like**

1. Have a bool option to enable or disable using channel numbers from the m3u (only if they are present)
2. When importing an m3u look for the tvg-chno and attemp to use the same number. If the number was not used before then assign it. If it was used before then assign it and a subchannel, like 100.1, 100.2, etc.

Alternative idea:
Allow searching channels using the API and re-assign the number. For example user could search for channel name, playlist, group title, etc... then be able to assign a number if there's a match.

**Describe alternatives you've considered**

**Additional context**

**Comment by glat** [comment]
+1

**Comment by MCTyler** [comment]
> +1

Dev Retired. Check a "active" fork.
