### ISSUE TITLE
Adding Network: metadata to the stream if buffer is on

### ISSUE THREAD

**Issue by jstorgaard** [xteve-project/xTeVe#29]
**Is your feature request related to a problem? Please describe.**
Post processing often makes use of metadata from the stream for identifying what kind of processing to do for which streams.

**Describe the solution you'd like**
"Network:" metadata to be added to the stream with the channel name.
I'm aware that this would only be possible when xTeVe is set with buffering enabled.

**Comment by mar-mei** [comment]
What exactly do you mean?
xTeVe does not use a video framework to read or modify metadata.

**Comment by jstorgaard** [comment]
Oh, I thought the buffering feature were treating the stream using ffmpeg or so?
How is the buffering feature provided?

**Comment by mar-mei** [comment]
The data is cached and forwarded to the client when the buffer size is reached. All client connections are monitored to allow re-streaming.

**Comment by jstorgaard** [comment]
I see. So no possibility to modify the stream adding metadata?

**Comment by mar-mei** [comment]
No, xTeVe does not even know what a video stream is.
