### ISSUE TITLE
M3U group specific URL not working when two or more words in group title

### ISSUE THREAD

**Issue by shanelord01** [xteve-project/xTeVe#291]
**Describe the bug**
Feed has group title as “Sports ESPN+” - when M3U URL has this added with specific group-title added no channels are found in player.

**Server (please complete the following information):**
Linux - Ubuntu]
Intel 64 Bit
xTeVe Version and Build: 2.2.0 Build: 0200

**To Reproduce**
Have a group with title Sports ESPN+ and try and create a group specific URL. ie:

http://192.168.1.250:34400/m3u/xteve.m3u?group-title=Sports ESPN+

**Expected behavior**
Channels should load

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
Would be great if the option for a specific URL based on filter would be available too. ie:

http://192.168.1.250:34400/m3u/xteve.m3u?filter-name=ESPN

**Comment by joshjryan** [comment]
@shanelord01 have you tried URL encoding your group title? e.g. http://192.168.1.250:34400/m3u/xteve.m3u?group-title=Sports%20ESPN%2B

**Comment by shanelord01** [comment]
> @shanelord01 have you tried URL encoding your group title? e.g. http://192.168.1.250:34400/m3u/xteve.m3u?group-title=Sports%20ESPN%2B

That worked. Thanks!
