### ISSUE TITLE
Can't get both IPTV and HDHomeRun working with same buffer setting.

### ISSUE THREAD

**Issue by flyize** [xteve-project/xTeVe#295]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I have a HDHomeRun and an IPTV service. I cannot find a buffer setting where both of them will work. List as follows:

- None: HDHomeRun works. IPTV does not (obviously no errors in log)
- xTeVe: HDHomeRun works. IPTV error `2022-01-31 16:33:13 [xTeVe] [ERROR] Streaming error (Server sends an incompatible content-type) - EC: 4003`
- FFMPEG: HDHomeRun works. IPTV error `2022-01-31 16:35:04 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204`
- VLC: IPTV works. HDHomeRun error `2022-01-31 16:36:01 [xTeVe] VLC log:                [0000154f983afa30] vlcpulse audio output error: PulseAudio server connection failure: Connection refused`

**Server (please complete the following information):**
- OS: Alpine Linux via Docker (https://github.com/alturismo/xteve_guide2go)
- Arch: amd64
- xTeVe Version: 2.2.0

**Expected behavior**
A single setting that will allow both HDHomeRun and IPTV

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge
 - Version Latest

**Comment by alturismo** [comment]
Alternative's discussed and sorted in unraid forums, can be closed ;)

**Comment by flyize** [comment]
Yes, thanks @alturismo

**Comment by adsoccer5** [comment]
Hi, hope you guys can help me. I'm encountering "FFMPEG: HDHomeRun works. IPTV error 2022-01-31 16:35:04 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204" and really haven't found much solutions. Im running plex and xTeVe on windows. Any suggestions would really help! Thanks in advance.

**Comment by pumacustom0c** [comment]
For anyone finding this in the future, this magical FFMPEG incantation (which I don't understand) worked for both IPTV and my HDHomerun:

` -hide_banner -loglevel error -i [URL] -c:a libmp3lame -vcodec copy -f mpegts pipe:1`

Now I can have IPTV Backups for my OTA channels (using Threadfin).
