### ISSUE TITLE
Image Caching needs a complete rehaul

### ISSUE THREAD

**Issue by buroa** [xteve-project/xTeVe#297]
**Is your feature request related to a problem? Please describe.**
Image caching is buggy, sometimes it downloads images, sometimes it doesn't. Sometimes it deletes a ton of cached images for no apparent reason and then re downloads them. This is **not** acceptable.

**Describe the solution you'd like**
Image caching should be transparent and only happen if a client requests a particular image. If the image is not cached, xTeVe will download it and serve it to the client. On any subsequent requests, it can serve the cached image. It should not download the image unless a client requested it. This is different from the current solution, which downloads all images inside the XMLTV guide regardless if they are ever viewed/used. A complete waste of resources/bandwidth.

**Describe alternatives you've considered**
N/A

**Additional context**
Schedulesdirect.org has a 5,000 images request limit in a 24 hour period, which with about 100 channels... xTeVe is hammering this limit and then downloads blank images. This can also be true for other EPG providers, which is why this solution would help all of them.

**Comment by alturismo** [comment]
> **Describe the solution you'd like**
> Image caching should be transparent and only happen if a client requests a particular image.

i guess this would make caching "obsolete" ... so you may should consider to just turn it off, then you have the load when needed ... but of course anytime you will load it again and again, but actually this shouldnt happen too often ...



> Schedulesdirect.org has a 5,000 images request limit in a 24 hour period, which with about 100 channels...

as workaround, split the lineups and let the run in 24 hours steps, so after x days you are done, afterwards they only update image's ... here with 108 channels ~ 100 - 500 images / day

**Comment by buroa** [comment]
I wish I could turn it off. My users that load the images are not within the same IP as my homelab (which, is in a datacenter anyways). Schedules Direct whitelists your IP for 6~ hours when you login and grab a token, which allows images to download. I have a cronjob that logs in every 6 hours just to make sure it's always whitelisted.

Since my Channels DVR users are outside of the IP (even I am), I have to cache the images using xTeVe since that IP is whitelisted to download from Schedules Direct.

The later workaround is still downloading unnecessary images. That is what I'm trying to _not_ do. This is very much a better feature, as it will help users that are outside of the home IP address load images.

**Comment by alturismo** [comment]
> The later workaround is still downloading unnecessary images. That is what I'm trying to _not_ do. This is very much a better feature, as it will help users that are outside of the home IP address load images.

sorry to say but no, the "normal" private usecase (what its designed for" if foe instant image loading, not for loading "on demand", thats the default behaviour ... no caching, in terms u use a more "buisness" like setup you may should look for alternatives in this user scenario or rewrite the part,  its open source ...

and as mentioned, daily updates will end into small slices of updates ...

2022-02-01 18:14:40 [xTeVe] Image Caching:          Images are cached (85)
2022-02-02 04:46:20 [xTeVe] Image Caching:          Images are cached (506)
...
