### ISSUE TITLE
XML syntax - invalid character entity & (no semicolon) - 

### ISSUE THREAD

**Issue by scarri** [xteve-project/xTeVe#30]
Hi
I tried with this version : 1.4.4 and V2. 
I get this error when I save the XMLTV file :
[xTeVe] [ERROR] XML syntax error on line 36: invalid character entity & (no semicolon) - 
if we find this character &, I get the error.

In order to do a test, I downloaded the m3u file and I minutely removed all the lines having an & (title or URL), all with the same result.

I tried this browser : Chrome, Edge and FireFox.
thanks

**Comment by MCTyler** [comment]
XML and m3u are two different things.

**Comment by scarri** [comment]
You're right. Thanks

**Comment by siaox** [comment]
Ran into the same issue - would be great if xTeve accepted the special characters. If it were possible.
