### ISSUE TITLE
Drag And Drop Support for Channel Order

### ISSUE THREAD

**Issue by sixshooterz** [xteve-project/xTeVe#31]
**Describe the solution you'd like**
The ability to drag and drop for channels on the mapping page would make ordering channels quite a bit easier than trying to assign numbers, especially when channels get added from the XML provider.

**Comment by mar-mei** [comment]
Drag and drop is not really usable with 1000 channels and scrolling

**Comment by sixshooterz** [comment]
I was more thinking for fine tuning but I understand. Thanks!
