### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by BastionNtB** [xteve-project/xTeVe#313]
Sorry, I know this isn't the right way to do this probably, but I don't know another way to ask.

Shows last commit was March of 2021.

But there are still active issues, with people that have committed to this project still commenting...

Just want to know if it's still alive and well or if there's a new project somewhere with continual work being committed.

Thanks.

**Comment by jaylex32** [comment]
> Sorry, I know this isn't the right way to do this probably, but I don't know another way to ask.
> 
> Shows last commit was March of 2021.
> 
> But there are still active issues, with people that have committed to this project still commenting...
> 
> Just want to know if it's still alive and well or if there's a new project somewhere with continual work being committed.
> 
> Thanks.

This project died long time ago.

**Comment by BastionNtB** [comment]
> 

Anything else like it? Or is there a replacement for it?

**Comment by deku-m** [comment]
I saw that SCP002 is putting in a lot of effort.
https://github.com/SCP002/xTeVe

**Comment by Write** [comment]
> I saw that SCP002 is putting in a lot of effort. https://github.com/SCP002/xTeVe

Why is it archived though

**Comment by deku-m** [comment]
> > I saw that SCP002 is putting in a lot of effort. https://github.com/SCP002/xTeVe
> 
> Why is it archived though

I dont know he did put effort in it but i tried his docker it still has a bug with updating database as it get stuck.
Hope someone will continue this as the app is good.

**Comment by Write** [comment]
Yeah, i use his version now, work great for me. I had indeed an issue were pressing save didn't worked but it seems that trying multiple time make it work after a while, so thats enough for me. 
This is the only version usable for me, the official one has way too many bug.

**Comment by deku-m** [comment]
> Yeah, i use his version now, work great for me. I had indeed an issue were pressing save didn't worked but it seems that trying multiple time make it work after a while, so thats enough for me.
> This is the only version usable for me, the official one has way too many bug.

What do you mean with pressing save multiple times?

**Comment by Write** [comment]
Well, when re-doing the mapping sometimes Save button didn't worked. I tought you talked about that

**Comment by deku-m** [comment]
Well i have the problem in the docker. And when launching the webgui you need to configure the tuner after the XMLTV is stays at Updating database

**Comment by michaelkrieger** [comment]
> > > I saw that SCP002 is putting in a lot of effort. https://github.com/SCP002/xTeVe
> > 
> > 
> > Why is it archived though
> 
> I dont know he did put effort in it but i tried his docker it still has a bug with updating database as it get stuck. Hope someone will continue this as the app is good.

Per [this issue](https://github.com/SCP002/xTeVe/pull/44#issuecomment-1118341930) SCP002 says...

> Now, I don't plan any futurer changes into the actual source code. The only things will be updated are dockerfile and readme's (#36), but not xTeVe's internals.
> After docker version is out, planning to archivate this repository.
> 
> ...
> 
> As I've told before, it's time to switch to another project for me. And I absolutely dont mind if you fork this fork 🙃, rewire it the way you like, replace all occurences of SCP002 with Fyb3roptik and make your own build. As well as your own Docker image if you'ld like.

**Comment by michaelkrieger** [comment]
> after the XMLTV is stays at Updating database
Going to assume you have a massive M3U/XMLTV file.

It works fine with smaller files, but yes- seems to spin endlessly at 100% CPU adding a M3U file of any size as it adds them all, not utilizing a filter by default.  Add something small from https://github.com/iptv-org/iptv and https://github.com/iptv-org/epg then add a filter which filters everything but "DUMMYFILTER" and then add your M3U and XMLTV file.

**Comment by SenexCrenshaw** [comment]
Check out my fork:
[https://github.com/SenexCrenshaw/xTeVe](https://github.com/SenexCrenshaw/xTeVe)

**Comment by MCTyler** [comment]
xTeVe is very much Alive, just no revision needed.

**Comment by SenexCrenshaw** [comment]
> Sorry, I know this isn't the right way to do this probably, but I don't know another way to ask.
> 
> Shows last commit was March of 2021.
> 
> But there are still active issues, with people that have committed to this project still commenting...
> 
> Just want to know if it's still alive and well or if there's a new project somewhere with continual work being committed.
> 
> Thanks.

This has had multiple updates. 
[https://github.com/SenexCrenshaw/xTeVe](https://github.com/SenexCrenshaw/xTeVe)

**Comment by Write** [comment]
> xTeVe is very much Alive, just no revision needed.

This must be some sort of joke of an answer ?

**Comment by MCTyler** [comment]
> > xTeVe is very much Alive, just no revision needed.
> 
> This must be some sort of joke of an answer ?

So what exactly do you think needs revised?

**Comment by BastionNtB** [comment]
> > > xTeVe is very much Alive, just no revision needed.
> > 
> > 
> > This must be some sort of joke of an answer ?
> 
> So what exactly do you think needs revised?

I mean, not to be bashful or anything... But there is 143 currently open issues for this repo... I would venture to say at least some of them are things people would like to see changed.

**Comment by MCTyler** [comment]
> > > > xTeVe is very much Alive, just no revision needed.
> > > 
> > > 
> > > This must be some sort of joke of an answer ?
> > 
> > 
> > So what exactly do you think needs revised?
> 
> I mean, not to be bashful or anything... But there is 143 currently open issues for this repo... I would venture to say at least some of them are things people would like to see changed.

I've went thru a lot of those, most can be solved by following instructions.

**Comment by MCTyler** [comment]
Unless you have anything specific to add, you can close this. Ultimately, it's up to Marmei to accept push's.

**Comment by BastionNtB** [comment]
> Unless you have anything specific to add, you can close this. Ultimately, it's up to Marmei to accept push's.

I mean, you're not wrong. I'll go ahead and close it. I think the question was answered anyway.

**Comment by Write** [comment]
Oh okay, weirdly I never had this issue (docker too)

**Comment by M1noa** [comment]
threadfin https://github.com/Threadfin/Threadfin/
