### ISSUE TITLE
Stream Buffer causes massive stuttering with .ts m3u8

### ISSUE THREAD

**Issue by sardon-boop** [xteve-project/xTeVe#33]
**Describe the bug**
m3u8 streams that just hold .ts files lag/stutter every 1-2 seconds forever when using the Stream Buffer option. This is in VLC as well as in Plex. If I turn off Stream Buffer the stream will not play in Plex but runs perfect in VLC. So I need stream buffer to work in Plex though, even though the stream delivers .ts files because it's via a m3u8 file. Any recommendations?

**Server (please complete the following information):**
- OS Win10
- Arch 64bit
- xTeVe Version and Build 2.0.3

**To Reproduce**
Stream URL available on request

**Comment by MCTyler** [comment]
Is another Media Player besides Plex a option?

**Comment by alturismo** [comment]
may try latest beta with vlc and/or ffmpeg remux option for buffering

**Comment by alszaitsev** [comment]
Have the same issue. Tried FFMpeg, VLC as a buffer. Changed buffer size etc. No unusual log events.

**Comment by MCTyler** [comment]
Try this setting for FFMpeg.....
`ffmpeg -i [URL] -acodec aac -vcodec copy -f mpegts pipe:1`

**Comment by alszaitsev** [comment]
> Try this setting for FFMpeg.....
> `ffmpeg -i [URL] -acodec aac -vcodec copy -f mpegts pipe:1`

Still stuttering

**Comment by alszaitsev** [comment]
2020/02/29 22:54:02 [xTeVe] Streaming Status:      Channel: МАТЧ ПРЕМЬЕР HD (Clients: 0)
2020/02/29 22:54:08 [xTeVe] Streaming Status:      Channel: МАТЧ ПРЕМЬЕР HD - No client is using this channel anymore. Streaming Server connection has ended
2020/02/29 22:54:08 [xTeVe] Streaming Status:      Playlist: EdemTV - Tuner: 0 / 5
2020/02/29 22:54:08 [xTeVe] Buffer:                true [ffmpeg]
2020/02/29 22:54:08 [xTeVe] Buffer Size:           1024 KB
2020/02/29 22:54:08 [xTeVe] Channel Name:          МАТЧ ПРЕМЬЕР HD
2020/02/29 22:54:08 [xTeVe] Client User-Agent:     Lavf/58.27.104
2020/02/29 22:54:08 [xTeVe] Streaming Status:      Playlist: EdemTV - Tuner: 1 / 5
2020/02/29 22:54:09 [xTeVe] FFMPEG path:           G:\TV\ffmpeg\bin\ffmpeg.exe
2020/02/29 22:54:09 [xTeVe] Streaming URL:         http://XXXXXXXXXXX/iptv/XXXXXXXXXXXX/220/index.m3u8
2020/02/29 22:54:09 [xTeVe] FFMPEG:                Processing data
2020/02/29 22:54:09 [xTeVe] Streaming Status:      Receive data from FFMPEG
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            ffmpeg version git-2020-01-31-62d92a8 Copyright (c) 2000-2020 the FFmpeg developers
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            built with gcc 9.2.1 (GCC) 20200122
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            libavutil      56. 38.100 / 56. 38.100
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            libavcodec     58. 67.100 / 58. 67.100
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            libavformat    58. 37.100 / 58. 37.100
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            libavdevice    58.  9.103 / 58.  9.103
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            libavfilter     7. 72.100 /  7. 72.100
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            libswscale      5.  6.100 /  5.  6.100
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            libswresample   3.  6.100 /  3.  6.100
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            libpostproc    55.  6.100 / 55.  6.100
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            [hls @ 000002992cc69200] Skip ('#EXT-X-VERSION:3')
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            [hls @ 000002992cc69200] Opening 'http://92.119.88.98/iptv/XXXXXXXXXX/220/1583006026000.ts' for reading
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            [hls @ 000002992cc69200] Opening 'http://92.119.88.66/iptv/XXXXXXXXXX/220/1583006036000.ts' for reading
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            [NULL @ 000002992cc9b240] non-existing SPS 0 referenced in buffering period
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            [NULL @ 000002992cc9b240] SPS unavailable in decode_picture_timing
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            [h264 @ 000002992cc9d040] non-existing SPS 0 referenced in buffering period
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            [h264 @ 000002992cc9d040] SPS unavailable in decode_picture_timing
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            Input #0, hls, from 'http://9561d56b.kazaktelekom.com/iptv/DCBPHVCQ8C377M/220/index.m3u8':
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            Duration: N/A, start: 67972.013933, bitrate: N/A
2020/02/29 22:54:09 [xTeVe] FFMPEG log:            Program 0
2020/02/29 22:54:09 [xTeVe] Streaming Status:      Buffering data from FFMPEG

**Comment by alturismo** [comment]
does the stream play fine in vlc, cause this is more a plex thing with your stream.

can be alot, codec, etc ... so not really anything we can do about it, check your plex logs and take a look at their forums to find a solution.

**Comment by mkanet** [comment]
> > Try this setting for FFMpeg.....
> > `ffmpeg -i [URL] -acodec aac -vcodec copy -f mpegts pipe:1`
> 
> Still stuttering. The problem is relevant while using Plex on AppleTV and Plex on iOS

It took me several hours of troubleshooting to figure out that some Plex clients can't handle aac properly; even when re-encoded by ffmpeg as acc.  If you re-encode the audio to MP3 with the below flags, all weird stuttering issues and dropped connections were resolved.  This is also mentioned in the original xteve documentation.

`-hide_banner -loglevel error -i [URL] -c:a libmp3lame -vcodec copy -f mpegts pipe:1`

**Comment by guru69** [comment]
> > > Try this setting for FFMpeg.....
> > > `ffmpeg -i [URL] -acodec aac -vcodec copy -f mpegts pipe:1`
> > 
> > 
> > Still stuttering. The problem is relevant while using Plex on AppleTV and Plex on iOS
> 
> It took me several hours of troubleshooting to figure out that some Plex clients can't handle aac properly; even when re-encoded by ffmpeg as acc. If you re-encode the audio to MP3 with the below flags, all weird stuttering issues and dropped connections were resolved. This is also mentioned in the original xteve documentation.
> 
> `-hide_banner -loglevel error -i [URL] -c:a libmp3lame -vcodec copy -f mpegts pipe:1`

This seems to have solved my studdering issue! Thanks for this

**Comment by mkanet** [comment]
@guru69 you're weclome.  BTW:  Xteve isn't in development anymore.  It should get archived soon 
 
There is a fork of Xteve called [Threadfin](https://github.com/Threadfin/Threadfin) which is actively being developed.  It can even buffer ffmpeg/VLC using RAM instead of unnecessarily swapping to disk.  Lots of new useful features.  I think you would like it even better than Xteve.  The developer is a nice guy that's also an enthusiast just like us.

**Comment by guru69** [comment]
> @guru69 you're weclome. BTW: Xteve isn't in development anymore. It should get archived soon
> 
> There is a fork of Xteve called [Threadfin](https://github.com/Threadfin/Threadfin) which is actively being developed. It can even buffer ffmpeg/VLC using RAM instead of unnecessarily swapping to disk. Lots of new useful features. I think you would like it even better than Xteve. The developer is a nice guy that's also an enthusiast just like us.

Wow that's awesome. Thanks! I was able to stand up Threadfin on my server and replaced Xteve. I switched it to ffmpeg and left the default ffmpeg line and most defaults for now. Have you changed this to use libmp3lame on your Threadfin? I haven't seen any playback issues so far.

**Comment by mkanet** [comment]
@guru69 You're welcome!  Yes, I'm using the same command to execute ffmpeg:

`
-hide_banner -loglevel error -i [URL] -c:a libmp3lame -vcodec copy -f mpegts pipe:1
`
As soon as I changed it to use mp3 audio, all the stuttering stopped.

**Comment by guru69** [comment]
Ok great, I'll use your command. Just noticed the "Backup Streams" option, cool!  I have to try that :-)
