### ISSUE TITLE
Any one know wich is the latest Plex version with m3u working with xteve?

### ISSUE THREAD

**Issue by martinorob** [xteve-project/xTeVe#337]
it’s seems that Plex broke m3u streaming with latest update.
I need to know the previous plex version with m3u streaming working.

Thanks

**Comment by MCTyler** [comment]
This is xTeVe, not Plex. Go to https://forums.plex.tv

**Comment by martinorob** [comment]
and no one here that use xTeve on plex can help me?

**Comment by MCTyler** [comment]
Plex is a PAID App, Why wouldn't you use their support?

**Comment by martinorob** [comment]
your answer are very usefull.

**Comment by MCTyler** [comment]
Come over to Discord, there are a few Plex users there..... https://discord.gg/2eRWypU8
