### ISSUE TITLE
API is just nowhere to be found?

### ISSUE THREAD

**Issue by SirRob24** [xteve-project/xTeVe#359]
Shot in the dark here but, no matter what way I try to install or run Xteve, there doesn't seem to be any API folder/files so when I go to http://[xteve.ip]:[port]/api/ all I get is a 404 error. API access is turned on in the settings. I've restarted Xteve. I've tried it on the master and on the beta. I've also tried using the pre-build windows exe and I've also installed a bunch of random docker images or various different Xteve builds but there is just no API to found. What am I doing wrong here?

Thanks!

**Comment by MCTyler** [comment]
https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/configuration.md#api

**Comment by SirRob24** [comment]
Figured it out. It's because I was using /api/ instead of /API/. So it needed to be in all caps. It works now.

**Comment by SirRob24** [comment]
Actually I lied. I spoke too soon. Having /API/ just returns an xml that looks like this

`<root xmlns="urn:schemas-upnp-org:device-1-0">
<URLBase>http://[XTEVE.IP:PORT]</URLBase>
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
<friendlyName>xTeVe</friendlyName>
<manufacturer>Silicondust</manufacturer>
<modelName>HDTC-2US</modelName>
<modelNumber>HDTC-2US</modelNumber>
<serialNumber/>
<UDN>uuid:xteve:10</UDN>
</device>
</root>`

If I do lowercase /api/ then I just get "Not Found [404]". If I turn off api access in the xteve settings then I get "Locked [423]" instead.

**Comment by SirRob24** [comment]
Oh man. Never mind, AGAIN. So Didn't change anything. Same code, same attempt same everything and it just works now... So... I got no idea. Any way, this is actually closed now. For real this time. Promise.
