### ISSUE TITLE
Web browser playback not working.

### ISSUE THREAD

**Issue by Distearth** [xteve-project/xTeVe#37]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Plex Live TV Streams play fine on all devices but not in the web browser player.

**Server (please complete the following information):**
- OS [Windows Server 2016]
- Arch [Intel 64 Bit]
- xTeVe Version and Build [2.1.0 Build: 0100]

**To Reproduce**
Play on phone app or Roku the stream loads and plays without error.

Play in any web browser it endlessly spins a loading icon.

**Expected behavior**
Play in web browser with web player.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, edge]
 - Version [77,]

**Additional context**
I have heard from others that they are having the same issue.
All streams are fine in VLC and apps just not a browser.
I have tried using VLC as buffer with same result.
I have tried changing the user agent to "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
with same result.
xTeVe always displays "Lavf/58.27.103" as Client User-Agent. Not sure if this is a bug or even related.

**Comment by mar-mei** [comment]
xTeVe only forwards the stream to Plex. If 9 out of 10 clients can play the stream, it's not an xTeVe issue.
In the Plex forum some have this problem with Plex version 1.17.xxx.
Downgrading to version 1.16.xxx has helped them.
https://forums.plex.tv/t/xteve-iptv-for-plex-dvr/278500/1328

Everything that connects to xTeVe is a client. If the log is a Client User-Agent, it means the client connecting to xTeVe. The user agent you enter in xTeVe uses xTeVe to connect to your provider.

**Comment by Distearth** [comment]
You're absolutely right. I'm sorry. I thought I had thought of everything...
I may have upgraded and forgot because everything was fine one day and then xTeVe updated to 2.x.x and I thought it broke around the same time. I love the new VLC and ffmpeg options, just need to figure out how to transcode on the fly to try and reduce the .ts stream size;) Thank you!
