### ISSUE TITLE
Fails on second startup

### ISSUE THREAD

**Issue by Sc0th** [xteve-project/xTeVe#38]
Been using xTeVe for a while now, it's excellent, many thanks!

However, migrating to a k8s cluster, when I restart xteve for the second time I am seeing the following and the container fails;

2019/10/13 18:35:31 [xTeVe] Version:               2.0.3 Build: 0030
2019/10/13 18:35:31 [xTeVe] Database Version:      2.0.0
2019/10/13 18:35:31 [xTeVe] System IP Addresses:   IPv4: 2 | IPv6: 0
2019/10/13 18:35:31 [xTeVe] Hostname:              xteve-599fc57849-l2sbq
2019/10/13 18:35:31 [xTeVe] System Folder:         /root/.xteve/
2019/10/13 18:35:31 [xTeVe] Load Settings:         /root/.xteve/settings.json
2019/10/13 18:35:31 [xTeVe] [ERROR] json: cannot unmarshal string into Go struct field SettingsStrcut.buffer of type bool () - EC: 0
2019/10/13 18:35:31 [xTeVe] [ERROR] json: cannot unmarshal string into Go struct field SettingsStrcut.buffer of type bool () - EC: 0

If I remove settings.json and fire it up it works fine, I make no changes, stop the pod and restart the error appears again and the container will not run?

All suggestions much appreciated!

**Comment by mar-mei** [comment]
Update to version 2.1.0

**Comment by Sc0th** [comment]
Yup, thanks that did the trick, will get back in my box.
