### ISSUE TITLE
Fallback to next stream of same channel.

### ISSUE THREAD

**Issue by Distearth** [xteve-project/xTeVe#39]
**Is your feature request related to a problem? Please describe.**
Some channels are offline but have a backup

**Describe the solution you'd like**
If first stream is unavailable, move to the next one

**Describe alternatives you've considered**
The tvheadend software does this but I don't think Plex works with it.

**Additional context**

**Comment by mar-mei** [comment]
The topic has already been discussed here.
https://github.com/xteve-project/xTeVe/issues/12
As long as the providers do not support unique IDs, this is not possible.
