### ISSUE TITLE
Remote Users have full access

### ISSUE THREAD

**Issue by Distearth** [xteve-project/xTeVe#40]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I have set up users but I can still access everything. http://mypublicip:34400/xmltv/xteve.xml is accessible by anyone.

**Server (please complete the following information):**
- OS [Windows 10]
- Arch [Intel 64 Bit]
- xTeVe Version and Build [2.1.0 Build: 0100]

**To Reproduce**
1. Go to 'http://myip:34400/xmltv/xteve.xml'

**Expected behavior**
User could not access the xml file without adding user & pass to the url

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [77]

**Additional context**
The folder is not shared.

**Comment by mar-mei** [comment]
![image](https://user-images.githubusercontent.com/43099631/66716555-31248180-edcf-11e9-8db0-7353dd37a70f.png)
Did you enable user authentication for the XMLTV file?

![image](https://user-images.githubusercontent.com/43099631/66716561-587b4e80-edcf-11e9-82db-7342de9c4d1a.png)

**Comment by Distearth** [comment]
That was it. I'm sorry I'm so stupid. This software is amazing, is there a reddit or forum where I could ask the community for help before thinking it's a bug... 

Plex does not seem to like loading an xml from an http: link, though. Gotta figure out how to map that so it looks local, I guess. I swear i'm going to donate soon!
