### ISSUE TITLE
Add .ts onto the end of the stream url

### ISSUE THREAD

**Issue by smurfster** [xteve-project/xTeVe#41]
**Is your feature request related to a problem? Please describe.**
I use Tvheadend with xteve. When I use my m3u url direct from the supplier it tvheadend, it works. When I setup xteve to use the m3u url and then configure tvheadend to use the xteve url. It wont work. 

**Describe the solution you'd like**
I've been told its because the new m3u produced by xteve contains streams without the ".ts" extension on the end.

e.g. 
provided m3u has http://myiptvsupplieraddress/channel/bbc1.ts
xteve m3u has http://xteveaddress/stream/05d6d8940311154f967b9b5b3fe61217

Cheers

**Comment by jstorgaard** [comment]
I got problems playing links in Jellyfin. Jellyfin log says Unknown profile.
I was also notified that links with .ts should help.

**Comment by mar-mei** [comment]
xTeVe generates an ID as a URL for each stream. This is also a valid URL. 
The same goes for the HDHomeRun tuner.
HDHomeRun tuner example URL:
`http://192.168.1.7:8080/auto/v422`

Fritz tuner example URL:
`rtsp://192.168.1.6:554/?avm=1&freq=554&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,99,1023,1027`

I also can not just use .ts as a file extension. Not every stream is a TS stream. The VLC and FFmpeg options allow users to transcode the stream into any other format.

I also do not know where the problem would be at xTeVe. Plex, Emby, VLC and just about every IPTV app works with xTeVe.

**Comment by smurfster** [comment]
When I use either xteve or ffmpeg buffer. The stream wont work in tvheadend, but when xteve is set to passthrough it does work. Any ideas?

**Comment by mar-mei** [comment]
No idea what makes TVHeadend with the streams differently than Plex or Emby.

Why do not you load the streams with TVHeadend and then transfer them to xTeVe?

**Comment by alturismo** [comment]
just tested here xteve m3u url's in tvheadend, working fine.

**Comment by alturismo** [comment]
i dont use any buffer cause here its senseless, i use tvheadend as backend, xteve as client to tvheadend ... not vice verse like you do. just did a test to see what happens, and yes, with buffer on it doesnt work, no input detected to tvheadend.

but, just adding a .ts wont solve this issue, you can test this yourself by editing the link yourself, u wont get any input anymore (with or without buffer) cause xteve cant interprete the link then anymore ...

why tvheadend cant read the input after xteve remuxing is the question you should ask tvheadend after u analysed how your streams are interpreted then ... then u can ask in their forum (which is good) why ...

but may consider your setup, when u already have tvheadend, put your sources there and let xteve use the tvheadend as backend (as its supposed to be) ... xteve is then the proxy for "Plex" as sample cause Plex cant use tvheadend as DVR source.

**Comment by smurfster** [comment]
I use xteve as its sorting function is far easier to manage (filters). Its also on a hosted server. My tvheadend is on a synology in my house, I use a hdhomerun and xteve in my tvh. The reason xteve is hosted is due to sharing with family and i have 2 connections max (hence using buffer). 
tvheadend pretty much bombs out with the amount of channels in the iptv m3u. So xteve filtering allows me to provide a subset of all channels im interested in.

**Comment by smurfster** [comment]
checkde out the difference between buffered and direct using wireshark.

it seems direct just has 1 connection and streams using that.
buffered looks like it creates lots of connections 1 after another feeding what looks like 1mb of data in each. wireshark refers to them as continuations.

This looks like the reason why tvheadend doesnt support it.

**Comment by ibishop100** [comment]
Sorry for hijacking this ticket, hopefully my comment here doesn't reopen it or something...

@smurfster Hi, I'm trying to do what you're describing here.  My hope is that the xteve remuxing will help make discontinuous recordings usable in tvheadend/kodi.  Did you ever find a solution?

**Comment by MCTyler** [comment]
@ibishop100 Why would you want discontinuous Recordings? or maybe this didn't translate right...
![image](https://user-images.githubusercontent.com/6390898/93659483-190ba800-fa0b-11ea-8b03-7de2dd40c56d.png)

**Comment by ibishop100** [comment]
I don't want them, but my provider and I think most providers aren't able to provide a fully reliable stream.  What I've found is if you have a small gap where the stream cuts out then the PVR never recovers.

I've tried TVHeadend, xteve/plex, xteve/mythtv in attempts to find a solution that can gracefully continue when the stream has a missing bit but nothing has worked so far.  I don't know if I need to tune one of the solutions to better handle the streams, or if there's a solution at all.

**Comment by alturismo** [comment]
to use buffered from xteve in txheadend, easy solution, ffmpeg pipe in tvheadend

sample url how this would look like in tvheadend

pipe:///usr/bin/ffmpeg -loglevel fatal -i http://192.168.1.67:34400/stream/af1c2ce8b0bbfbe20705a30dfbee5b34 -vcodec copy -acodec copy -metadata service_provider=STRING

like this you get the buffered stream from xteve into tvheadend for further usage, but ... this will not solve your issues if you have a bad connection to your provider.

live streams need steady, good streams, its a live stream, so no client (xteve, tveadend, ...) can preload, they can buffer a little, but as soon the buffer is reached (1mb buffer ~ 1 second bad connection) and you back again where every dropout will kill the stream ...
