### ISSUE TITLE
xTeVe frontend behind nginx proxy

### ISSUE THREAD

**Issue by Nicras** [xteve-project/xTeVe#42]
Hi,

first of all I wanna say thank you for this awesome piece of software. It works like a charm in my plex --> tvheadend environment.

And I have more of a question, than a feature request:

Would it be possible for you to provide a working Nginx Reverse Proxy configuration for xTeVe?

I tried a lot of ways to get the websocket connection running but it doesn't.

Thanks in advance and greetings from Germany
Sven

**Comment by mar-mei** [comment]
Take a look at Pull Request #36.
Unfortunately, I have not received any answer from him yet.
If you were able to compile a binary with the change, I would appreciate feedback.

**Comment by Strap1** [comment]
Hi, I'm also still struggling getting a reverse proxy going for Xteve frontend in Nginx. Redacted config:

```
upstream websocket {
    server localhost:34400;
}
server {
    location /xteve/ {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location /xteve/ui {
        proxy_pass http://websocket/web/;
    }
}
```
Visiting: https://myurl.net/xteve/ returns 
![image](https://user-images.githubusercontent.com/6105839/71577020-e0c9df80-2af2-11ea-805c-56e8bcc97a42.png)

and visiting https://myurl.net/xteve/ui inexplicably redirects to https://myurl.net/web which returns a 404.

Anybody had any luck with this?

**Comment by aegie** [comment]
I managed to do it in docker, but I have an issue with the DVR IP. But that's another story. Here is my reverse config as a starting point, this is used with subdomain with letsencrypt docker. 

The content of my xteve.subdomain.conf hope it helps you. So I can successfully access https://xteve.mydomain.com/web

```
#Make sure that your dns has a cname set for xteve

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name xteve.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    #enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        #enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        #enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_xteve xteve;
        proxy_pass http://192.168.1.151:34400;
		
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by Strap1** [comment]
Thanks for your help. I tried to incorporate bits of your .conf but no luck. I'm currently using my main domain myurl.net/xteve but maybe I'll have a look into going the subdomain route like you with xteve.myurl.net, and see if I have any success there.

**Comment by iWangJiaxiang** [comment]
Meet same issut, too~

My conf :

```
server {
    listen 443 ssl;
    server_name xteve.*;
    # using global ssl cert
#    ssl_certificate /etc/letsencrypt/live/DOMAIN_NAME/fullchain.pem;
#    ssl_certificate_key /etc/letsencrypt/live/DOMAIN_NAME/privkey.pem;
#    include /etc/letsencrypt/options-ssl-nginx.conf;
#    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    add_header Strict-Transport-Security "max-age=31536000" always;
#    ssl_trusted_certificate /etc/letsencrypt/live/DOMAIN_NAME/chain.pem;
    ssl_stapling on;
    ssl_stapling_verify on;

    auth_basic           “auth;
    auth_basic_user_file /etc/nginx/conf.d/htpasswd;
    location / {
        # Proxy main xteve traffic
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto $scheme;
#        proxy_set_header X-Forwarded-Protocol $scheme;
#        proxy_set_header X-Forwarded-Host $http_host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
#        proxy_buffering off;
        proxy_pass http://127.0.0.1:34401;
    }
}
```

**Comment by romainrbr** [comment]
Got it working without issue with a conf looking like this :

`server {
  server_name my_dns;
  listen 443 ssl;
  ssl                  on;
  ssl_prefer_server_ciphers       On;
  ssl_protocols                   TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers                     'AES256+EECDH:AES256+EDH:!aNULL';
  ssl_stapling                    off;
  resolver                        8.8.8.8 8.8.4.4 valid=300s;
  resolver_timeout                5s;
  access_log /var/log/nginx/xteve.access.log;
  error_log  /var/log/nginx/xteve.error.log;
  ssl_certificate [...];
  ssl_certificate_key [...];
  keepalive_timeout               180;

  location / {
                proxy_pass http://217.182.42.154:34400;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-for $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $remote_addr;
                proxy_set_header X-Forwarded-Protocol $scheme;
                proxy_redirect off;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

  }
}
`

**Comment by romainrbr** [comment]
Got it working with a conf looking like this :+1: 

```
server {
  server_name my_dns;
  listen 443 ssl;
  ssl                  on;
  ssl_prefer_server_ciphers       On;
  ssl_protocols                   TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers                     'AES256+EECDH:AES256+EDH:!aNULL';
  ssl_stapling                    off;
  resolver                        8.8.8.8 8.8.4.4 valid=300s;
  resolver_timeout                5s;
  access_log /var/log/nginx/xteve.access.log;
  error_log  /var/log/nginx/xteve.error.log;
  ssl_certificate [...];
  ssl_certificate_key [...];
  keepalive_timeout               180;

  location / {
                proxy_pass http://xx.xx.xx.xx:34400;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-for $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $remote_addr;
                proxy_set_header X-Forwarded-Protocol $scheme;
                proxy_redirect off;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

  }
}
```

**Comment by dotsam** [comment]
For anyone else coming across this issue and trying to access xteve via a nginx reverse-proxy at a subfolder rather than a subdomain, you'll need to do a rewrite, and even modify a javascript file in flight to have the right URL for the websocket. But this all works to access the frontend. I'm still connecting to the native port on 127.0.0.1 for the tuner itself.

```
location /xteve/ {
  sub_filter_types application/javascript;
  sub_filter 'window.location.port + "/data/"' 'window.location.port + "/xteve/data/"';
  sub_filter_once on;

  proxy_cookie_path / /xteve/;
  proxy_redirect / /xteve/;
  proxy_pass http://xteve;

  rewrite ^/xteve(.*) $1 break;
}
```

Obviously all of the other usual proxy settings apply, but this is everything xteve-specific.

**Comment by jaylex32** [comment]
> For anyone else coming across this issue and trying to access xteve via a nginx reverse-proxy at a subfolder rather than a subdomain, you'll need to do a rewrite, and even modify a javascript file in flight to have the right URL for the websocket. But this all works to access the frontend. I'm still connecting to the native port on 127.0.0.1 for the tuner itself.
> 
> ```
> location /xteve/ {
>   sub_filter_types application/javascript;
>   sub_filter 'window.location.port + "/data/"' 'window.location.port + "/xteve/data/"';
>   sub_filter_once on;
> 
>   proxy_cookie_path / /xteve/;
>   proxy_redirect / /xteve/;
>   proxy_pass http://xteve;
> 
>   rewrite ^/xteve(.*) $1 break;
> }
> ```
> 
> Obviously all of the other usual proxy settings apply, but this is everything xteve-specific.

Can you please show me your complete xteve setup with your IP redacted? Thanks in advance.

**Comment by Smartway2Mike** [comment]
add this
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade

from this site here

**Comment by mkanet** [comment]
Thank you guys.  I was able to get this to work!
 
**URL:  https://xteve.mydomain.com**


```
    server {
            listen 443 ssl http2; 
            listen [::]:443 ssl http2;
            ssl_certificate     ./ssl/fullchain.cer;
            ssl_certificate_key ./ssl/cert.key;
            server_name  xteve.mydomain.com;
            location / {
                proxy_pass http://192.168.1.2:34400/web/;
                proxy_cookie_path / /xteve/;
                proxy_redirect / /xteve/;
                rewrite ^/xteve(.*) $1 break;
                proxy_set_header Accept-Encoding "";
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
                sub_filter_types application/javascript;
                sub_filter 'window.location.port + "/data/"' 'window.location.port + "/xteve/data/"';
                sub_filter_once on;
            }
    }

```

I also tried:
   
 `proxy_pass http://192.168.1.2:34400;`

**Comment by mkanet** [comment]
> I managed to do it in docker, but I have an issue with the DVR IP. But that's another story. Here is my reverse config as a starting point, this is used with subdomain with letsencrypt docker.
> 
> The content of my xteve.subdomain.conf hope it helps you. So I can successfully access https://xteve.mydomain.com/web
> 
> ```
> #Make sure that your dns has a cname set for xteve
> 
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
> 
>     server_name xteve.*;
> 
>     include /config/nginx/ssl.conf;
> 
>     client_max_body_size 0;
> 
>     #enable for ldap auth, fill in ldap details in ldap.conf
>     #include /config/nginx/ldap.conf;
> 
>     location / {
>         #enable the next two lines for http auth
>         #auth_basic "Restricted";
>         #auth_basic_user_file /config/nginx/.htpasswd;
> 
>         #enable the next two lines for ldap auth
>         #auth_request /auth;
>         #error_page 401 =200 /login;
> 
>         include /config/nginx/proxy.conf;
>         resolver 127.0.0.11 valid=30s;
>         set $upstream_xteve xteve;
>         proxy_pass http://192.168.1.151:34400;
> 		
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>     }
> }
> ```

@aegie I really hope you're still following this issue.  Any idea how to get this to also work with Web Authentication enabled?  Currently, your config causes a "session expired" after enabling Web Authentication and trying to login with a username and password.

**Comment by mkanet** [comment]
> I managed to do it in docker, but I have an issue with the DVR IP. But that's another story. Here is my reverse config as a starting point, this is used with subdomain with letsencrypt docker.
> 
> The content of my xteve.subdomain.conf hope it helps you. So I can successfully access https://xteve.mydomain.com/web
> 
> ```
> #Make sure that your dns has a cname set for xteve
> 
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
> 
>     server_name xteve.*;
> 
>     include /config/nginx/ssl.conf;
> 
>     client_max_body_size 0;
> 
>     #enable for ldap auth, fill in ldap details in ldap.conf
>     #include /config/nginx/ldap.conf;
> 
>     location / {
>         #enable the next two lines for http auth
>         #auth_basic "Restricted";
>         #auth_basic_user_file /config/nginx/.htpasswd;
> 
>         #enable the next two lines for ldap auth
>         #auth_request /auth;
>         #error_page 401 =200 /login;
> 
>         include /config/nginx/proxy.conf;
>         resolver 127.0.0.11 valid=30s;
>         set $upstream_xteve xteve;
>         proxy_pass http://192.168.1.151:34400;
> 		
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>     }
> }
> ```

@aegie After I enable "Web authentication" in xTeVe settings and add a user/password,.. when I try to login, I get the error message "Session has Expired".

Any idea how to configure nginx to support xTeVe's builtin web authentication?

**Comment by mkanet** [comment]
> For anyone else coming across this issue and trying to access xteve via a nginx reverse-proxy at a subfolder rather than a subdomain, you'll need to do a rewrite, and even modify a javascript file in flight to have the right URL for the websocket. But this all works to access the frontend. I'm still connecting to the native port on 127.0.0.1 for the tuner itself.
> 
> ```
> location /xteve/ {
>   sub_filter_types application/javascript;
>   sub_filter 'window.location.port + "/data/"' 'window.location.port + "/xteve/data/"';
>   sub_filter_once on;
> 
>   proxy_cookie_path / /xteve/;
>   proxy_redirect / /xteve/;
>   proxy_pass http://xteve;
> 
>   rewrite ^/xteve(.*) $1 break;
> }
> ```
> 
> Obviously all of the other usual proxy settings apply, but this is everything xteve-specific.

Thank you so much for this.  I got it all working thanks to you.  However, if I enable **xTeVe's Web Authentication setting** and try to login to the web interface with my xTeVe username/password, , I get prompted with "Session has expired".  Do you mind taking a look at what I have below to see what I'm missing?

```
    server {
            listen 443 ssl http2; 
            listen [::]:443 ssl http2;
            ssl_certificate     ./ssl/fullchain.cer;
            ssl_certificate_key ./ssl/cert.key;
            server_name  xteve.mydomain.com;
            location / {
                proxy_pass http://192.168.1.2:34400/web/;
                proxy_cookie_path / /xteve/;
                proxy_redirect / /xteve/;
                rewrite ^/xteve(.*) $1 break;
                proxy_set_header Accept-Encoding "";
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
                sub_filter_types application/javascript;
                sub_filter 'window.location.port + "/data/"' 'window.location.port + "/xteve/data/"';
                sub_filter_once on;
            }
    }
```

I also created a new issue asking for help here:
https://github.com/xteve-project/xTeVe/issues/279

**Comment by GameEnder** [comment]
How do you get the generated m3u file and EPG to have the reverse proxy address for the stream and image file location instead of the local address?

**Comment by mkanet** [comment]
> How do you get the generated m3u file and EPG to have the reverse proxy address for the stream and image file location instead of the local address?

I don't. I use IPTV Boss to generate my m3u and EPG xml files locally; and point xteve to them locally.

**Comment by GameEnder** [comment]
Ahh, ok. I guess xteve just don't work like that. Was trying to host xteve external, and receive all the files in via encrypted traffic.

**Comment by gdomod** [comment]
I got authentification to work, but the last one is the generated m3u file
there are static "http" sheme inside the config.go

i run xteve behind basic auth and custom port , with custom path like
https://username:password@EXAMPLE.COM:12345/xteve/web

```
location /xteve {
        proxy_pass http://DOCKERCONTAINERNAME:34401/web/;
        proxy_cookie_path / /xteve/;
        proxy_redirect / /xteve/;
        rewrite ^/xteve(.*) $1 break;
        proxy_set_header Accept-Encoding "";
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        sub_filter_types application/javascript;
        sub_filter 'window.location.port + "/data/"' 'window.location.port + "/xteve/data/"';
        sub_filter_once on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $host/xteve;
        proxy_set_header X-Forwarded-Proto https;
 }



location /xteve/data {
        proxy_pass http://DOCKERCONTAINERNAME:34401/data;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

}
```

**Comment by mkanet** [comment]
@gdomod thank you so much.  I just tried what you posted (modifying it a tiny bit for subdomain and SSL support):
https://xteve.mydomain.com

Unfortunately, I'm still getting the below error after enabling Xteve authentication and entering my username/password at the Authentication prompt.  
**Session has expired** 

Any ideas what I'm doing wrong?  All I want is for xteve's authentication to work.  Maybe I'm doing something wrong on the second part below?  I am able to use authentication correctly if I go to the private url directly from within my network:  http://192.168.1.2:34400/web/


```
    server {
            listen 443 ssl http2; 
            listen [::]:443 ssl http2;
            ssl_certificate     ./ssl/fullchain.cer;
            ssl_certificate_key ./ssl/cert.key;
            ssl_prefer_server_ciphers on;
            server_name  xteve.mydomain.com;
            location / {
                proxy_pass http://192.168.1.2:34400/web/;
                proxy_cookie_path / /xteve/;
                proxy_redirect / /xteve/;
                rewrite ^/xteve(.*) $1 break;
                proxy_set_header Accept-Encoding "";
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Host $host/xteve;
                proxy_set_header X-Forwarded-Proto https;
                sub_filter_types application/javascript;
                sub_filter 'window.location.port + "/data/"' 'window.location.port + "/xteve/data/"';
                sub_filter_once on;
            }

            location /xteve/data {
                proxy_pass http://192.168.1.2:34400/data;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                # WebSocket support
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
    }
```
EDIT:  Oops...I go so excited thinking you figured out how to use xteve's builtin authentication with nginx.  It looks like you're just using basic web auth (avoiding xteve's authentication completely).  If you or anyone else figures out how to do this, please post here.
