### ISSUE TITLE
Using official docker container, how to add VLC and/or FFMPEG?

### ISSUE THREAD

**Issue by relink2013** [xteve-project/xTeVe#43]
I am using the official xteve docker on an unRAID system. What is the proper way to go about adding the VLC and/or FFMPEG binaries?

**Comment by mar-mei** [comment]
There is no official Docker image. Recommended are:
https://github.com/xteve-project/xTeVe#recommended-docker-image-linux-64-bit

VLC and FFmpeg is included.

**Comment by relink2013** [comment]
I'm using the image at https://hub.docker.com/r/alturismo/xteve

When I tried to change the buffer to VLC or ffmpeg I got an error telling me that it couldn't find the binary. 

However I just tried again and it worked just fine. But thank you for letting me know its included, that's what prompted me to try again. I don't know why it didn't work the first time.
