### ISSUE TITLE
ARM Docker for Raspberry Pi

### ISSUE THREAD

**Issue by stefangries** [xteve-project/xTeVe#47]
**Is your feature request related to a problem? Please describe.**

There are Docker Images available for x86 and x64. These do not run on a Raspberry Pi, as this is an ARM device. Many users use a Pi as home server.

**Describe the solution you'd like**

A ARM-compatible docker image, running on Raspberry Pi.

**Comment by mar-mei** [comment]
All Docker images were created by other people. If you need a Docker image for ARM, you have to create it yourself. Binary and source code is available.
