### ISSUE TITLE
"slave stream"

### ISSUE THREAD

**Issue by purfier** [xteve-project/xTeVe#50]
When using only 1 tuner the first client to make decision on what to watch, that all good most of the time but the second client will then need to go trough all the channels to find the one in use.
 
Would be awesome with a m3u list that is pure slave, meaning that it only have 1 channel and that is whatever the master is showing.
For DVR its not needed as you also get the information in on what is being watched but for m3u streams it would be perfect.

**Comment by mar-mei** [comment]
That does not make sense to me.
Why should the second client always see the same stream as the first one?

Then the second client would have to update the M3U file every few seconds to see which stream the first client is watching.

**Comment by purfier** [comment]
hi,
When you are using a stream with 1 single tuner the leaving room is the master, so its ok for my kids to watch tv but I control the channel. What they now need to do is scroll down 180 channels to find the one the master is watching. 
So i was thinking a slave m3u where that does not need to be update, that points to a generic stream, that is redirected on the server side to the current stream.

**Comment by mar-mei** [comment]
I'm sorry, but that does not make sense to me.
