### ISSUE TITLE
Multi Edit Titles

### ISSUE THREAD

**Issue by isriam** [xteve-project/xTeVe#54]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to bulk edit titles.  Strip USA | from all titles or such.
**Describe the solution you'd like**
Ability to bulk edit titles to remove string like US, USA, etc.
**Describe alternatives you've considered**

**Additional context**

**Comment by MCTyler** [comment]
Not in the Scope of xTeVe. You can edit your m3u with any Text editor. Not sure how easy it would be to implement this but there are plenty of alternatives. Your asking xTeVe to fix something your Provider/Source has control over.

**Comment by isriam** [comment]
totally get it, but you already allow editing tvg info and individual channel names.  it would really make xteve a one stop shop instead of having to hack up m3u's.  I import 5 m3u's to xteve and then i can make all my channels line up in the xml as a single entity.  I'm tired of having USA | AMC, AMC, AMC West, AMC East, US: AMC, AMC - USA......

just a suggestion though, you guys own the app and i love it for what it does.

**Comment by MCTyler** [comment]
Important thought, So the editing would have to be done before Filtering and Mapping to get it to Match the EPG. I can actually see where this would be useful!

**Comment by isriam** [comment]
Yea i was thinking a few options, one being after the m3u is processed via the mapping page.  Then you could say sort channels via name, instead of number.  My problem is adding 2 m3u's and then it adds them sequentil

**Comment by isriam** [comment]
after importing multiple m3u's i was thinking a few different options as well.  I can explain the problems i come across then i'm open to any solutions to fix them.

1.  When i import multiple m3u's the mapping simply runs through them sequentially and adds them.  So I have m3u list #1 first, and then m3u list #2 second.  So if both lists have AMC, they aren't in order aphabetical, but in order of how the processing works.  Even if I sort via name, the channel numbers are still off and thats how most players like plex sort channels.  Maybe redo channels by alpha instead of order put into mapping?

2. Names that contain prefixes or suffixes throw off the alpha and sorting in mapping.  If a m3u has AMC, and a second m3u has USA: AMC then they aren't treated as the same channel.  I was thinking like bulk edit names on m3u so that when xteve processes them they are seen as the same channel.

**Comment by MCTyler** [comment]
This sounds more like a forum discussion rather than feature request, Please visit us on Discord.....
https://discord.gg/KD2jy5V

**Comment by mar-mei** [comment]
Bulk Edit allows you to make identical settings for multiple channels.

What you want would be search and replace. That's not easy to implement. Each editor has this function, the whole mapping is in the xepg.json. Open this file with an editor and then you can quickly remove words. xTeVe should be closed and make a backup before.

Everyone has and wants a different system to sort the channels.
Sort by categories, countries, alphabetically, etc. For the guide to look good in Plex, channel numbers must be present.
Therefore it was obvious to use channel numbers when developing the mapping. So everyone has the freedom to set their own order. In the mapping you can sort the channels by name and quickly jump to the next field for the channel number with the Tab key.

**Comment by adelatour11** [comment]
I've developed some scripts using jq to automate channel metadata updates, let me know if you want some details on that

**Comment by adelatour11** [comment]
> Bulk Edit allows you to make identical settings for multiple channels.
> 
> What you want would be search and replace. That's not easy to implement. Each editor has this function, the whole mapping is in the xepg.json. Open this file with an editor and then you can quickly remove words. xTeVe should be closed and make a backup before.
> 
> Everyone has and wants a different system to sort the channels.
> Sort by categories, countries, alphabetically, etc. For the guide to look good in Plex, channel numbers must be present.
> Therefore it was obvious to use channel numbers when developing the mapping. So everyone has the freedom to set their own order. In the mapping you can sort the channels by name and quickly jump to the next field for the channel number with the Tab key.

A simple solution would be to include renumbering id with bulk edit, we could set the first value and iterate from that value for all channels selected

**Comment by isriam** [comment]
thanks for the comments on these.  a few things i've noticed is that my filters actually go in order of application.  so if i pull in filter "network tv" and then "premium tv" they order based on that.  It seems a "renumber channels based on current sort" would solve this problem.  I also see this happen with multiple m3u's that are imported, it parses them in order and then numbers them in that order, instead of alphabetical.
