### ISSUE TITLE
Simple Restart/Shutdown buttons

### ISSUE THREAD

**Issue by soulvoid86** [xteve-project/xTeVe#55]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Just simple Restart/Shutdown buttons to restart or shutdown xTeVe. I'm having issues with my sources guide and found there was no easy way to shutdown or restart xTeVe for troubleshooting. The server I rent doesn't allow elevated privileges because it's shared.

**Describe alternatives you've considered**
CLI commands but they are not allowed.

**Additional context**

**Comment by MCTyler** [comment]
`ctrl +c` Doesn't work?

**Comment by mar-mei** [comment]
That will lead to problems. xTeVe is started on most servers / Docker images via a script. Many scripts have the ability to monitor the process. If xTeVe had a restart / shutdown button, in the worst case, the scripts would start xTeVe again.

No idea what you do with the server, but maybe you should click on a VServer. You get it for less than $ 5 and have full access.
