### ISSUE TITLE
Unable to filter out the VOD channels.

### ISSUE THREAD

**Issue by yurividal** [xteve-project/xTeVe#57]
I have been trying to use xteve to filter out the VOD channels from my lists. But, aparently it does not seem to be very straight forward. 
I have tried creating a filter like this !{Filmes,Series} , because these 2 words are in all my VOD groups, but when i do this, xteve just hangs in the updating database, forever.

**Comment by mar-mei** [comment]
Hard to say without seeing the playlist. I have just tested that with mine and everything works.

The idea of the filter is actually to filter the channels you want to have and not to say which channels you do not want.

**Comment by MCTyler** [comment]
Join us on Discord, We have a Pinned Python Script that will do just what you need before ever being loaded into xteve.

**Comment by isriam** [comment]
you can also use m3u4u.com and filter your m3u then push that as a playlist into xteve.
