### ISSUE TITLE
Wrong url for m3u when using Xteve behind reverse proxy

### ISSUE THREAD

**Issue by adelatour11** [xteve-project/xTeVe#58]
I use xteve behind a reverse proxy. When i login to xteve using https the M3U and EPG url provided are not correct as they are still based on http

- OS : Linux
- Arch Intel 
- xTeVe Version 2.1.0 (0101)

**Comment by mar-mei** [comment]
Update to version 2.1.0 (0104)
The first HTTP / HTTPS request will rewrite the URL in the file.
If that does not work, I need the log in debug mode 2, this lines would be interesting:

```
2019/11/15 20:40:28 [DEBUG] Web Server Request:    Path: /lineup.json
2019/11/15 20:40:28 [DEBUG] Web Server Request:    URL: http://localhost:34400/lineup.json
2019/11/15 20:40:28 [DEBUG] Web Server Request:    Scheme: http
```

**Comment by adelatour11** [comment]
I've just tested it, the xteve m3u  is correct so I can retrieve the list of urls for each stream in vlc but now each stream url is changed to https, the stream url should not change

**Comment by adelatour11** [comment]
It works now thanks!

**Comment by adelatour11** [comment]
In fact I still have the same issue, when I want to stream locally using http, vlc is using https urls

**Comment by mar-mei** [comment]
I need the log in debug mode 2 when VLC downloads the xteve.m3u

**Comment by adelatour11** [comment]
I think i understood the issue, it depends on the way i am logged in xteve web interface

When i open xteve web interface through my proxy using https, the url used is https

```
2019/11/17 12:03:02 [DEBUG] Web Server Request:    URL: http://192.168.1.10:34400/web/
2019/11/17 12:03:02 [DEBUG] Web Server Request:    Scheme: https
2019/11/17 12:03:02 [DEBUG] Web Server Request:    Path: /favicon.ico
```
when i use VLC then i can see that the url used is https

then when i log in using http (local address) i can see that the scheme used is http

```
2019/11/17 12:03:02 [DEBUG] Web Server Request:    URL: http://192.168.1.10:34400/web/
2019/11/17 12:03:02 [DEBUG] Web Server Request:    Scheme: http
2019/11/17 12:03:02 [DEBUG] Web Server Request:    Path: /favicon.ico
```
then if log in again using https, etc.

```
2019/11/17 12:15:05 [DEBUG] Web Server Request:    URL: https://xteve.hidea.synology.me/web/
2019/11/17 12:15:05 [DEBUG] Web Server Request:    Scheme: https
```

So xteve will behave differently depending on the scheme and last log in
If i log in using my local address, my local vlc will work, but if i login using https and proxy, the stream url will change.

**Comment by mar-mei** [comment]
M3U request HTTP header:
```
GET /m3u/xteve.m3u HTTP/1.1 1 1 map[Accept:[*/*] Accept-Language:[de] Range:[bytes=0-] User-Agent:[VLC/3.0.8 LibVLC/3.0.8]] {} <nil> 0 [] false localhost:34400 map[] map[] <nil> map[] [::1]:63466 /m3u/xteve.m3u <nil> <nil> <nil> 0xc001dc4480
```

Web request HTTP header:
```
GET /favicon.ico HTTP/1.1 1 1 map[Accept:[image/webp,image/apng,image/*,*/*;q=0.8] Accept-Encoding:[gzip, deflate, br] Accept-Language:[de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7] Cache-Control:[no-cache] Connection:[keep-alive] Pragma:[no-cache] Referer:[http://localhost:34400/web/] Sec-Fetch-Mode:[no-cors] Sec-Fetch-Site:[same-origin] User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36]] {} <nil> 0 [] false localhost:34400 map[] map[] <nil> map[] [::1]:63477 /favicon.ico <nil> <nil> <nil> 0xc001cf4280
```

xTeVe evaluates Referer:
Referer:[http://localhost:34400/web/]

If the value is missing, the files can not be rewritten.

**Comment by adelatour11** [comment]
Thanks for your feedback, i did not get it, how is it fixed? Am I supposed to do something to test a fix?

**Comment by mar-mei** [comment]
Since it is not possible to detect whether the download was done via HTTP or HTTPS, I will undo my recent changes.

But I will give the possibility to define this in the settings.json file (if HTTP or HTTPS should be generated for the URLs)

**Comment by adelatour11** [comment]
actually it is working fine now if i login locally or remotely before on the web interface, it switches the scheme and the stream works

**Comment by adelatour11** [comment]
The issue is back, when i am logged using https, the blue wheel keeps spinning and there is an issue : No websocket connection to xTeVe could be established. Check your network configuration.

**Comment by adelatour11** [comment]
seems to be related to my synology settings, it is fixed now

**Comment by monnolo** [comment]
> seems to be related to my synology settings, it is fixed now

Hi, you mind clarifying how you managed to solve this ? Thanks !
