### ISSUE TITLE
Doesn't seem to work behind a proxy

### ISSUE THREAD

**Issue by clarkd** [xteve-project/xTeVe#59]
My IPTV provider is only accessible via a proxy - this is configured in the system settings but could also be configured manually with xTeVe if that option is available (I use this for Jackett).

Windows 64-bit, latest version of xTeVe.

Is it possible to specify the proxy URL or get xTeVe to use the system proxy?

**Comment by MCTyler** [comment]
You on Beta? I think this has been fixed.....

**Comment by clarkd** [comment]
I downloaded the latest release from the xTeVe website: 2.1.0. Is there a
later release?

**Comment by MCTyler** [comment]
There is...It's Beta
Change your settings.json from master ---> beta

**Comment by clarkd** [comment]
Let me try that and get back to you, thanks for your quick responses!

**Comment by MCTyler** [comment]
Silence is Golden...Must of worked!

**Comment by clarkd** [comment]
I *think* it worked - in the end I ended up setting up OpenVPN so all network traffic is forced through that but either way, it is all working. The software looks great, thank you!
