### ISSUE TITLE
Base64-Logos

### ISSUE THREAD

**Issue by acuntex** [xteve-project/xTeVe#60]
Some providers have a mess when it comes to logos.
They put in links in the tvg-logo which is handled by xteve (caching) but some are also base64-images like:

> data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkG...

Since some players can't handle base64-images, it would be nice, if xteve could cache these images and give it out like the other cached images.

Maybe with an option in the settings.

**Comment by mar-mei** [comment]
Base64 in tvg-logo? 🤦
Tell your Provide, he should enter a link there. That also saves him a lot of traffic.

tvg-logo is also used only as a fallback. Priority has the logo from the XMLTV file.
You can change the logo in the mapping and also upload your own.

**Comment by acuntex** [comment]
@mar-mei In a reasonable world I would agree with you.
Most providers (> 90% probably) are either resellers and/or have no technical clue and use a third party software they can't modify.

You will probably never get to the perfect data quality from providers, that why you have to post-process the data to incease the data quality.

**Comment by mar-mei** [comment]
The problem was solved by EPG providers.
Schedules Direct, webGrab + or zap2it

xTeVe allows you to use multiple XMLTV files for better metadata.

**Comment by acuntex** [comment]
But isn't that a Plex/Emby-Only feature?

**Comment by mar-mei** [comment]
No, you load your XMLTV files in xTeVe and in the mapping you edit your channels.
![image](https://user-images.githubusercontent.com/43099631/69008071-785ddf00-0946-11ea-97c5-b4be547e5570.png)

**Comment by acuntex** [comment]
Ah I see now what Guide2Go is for...

I'm still on the bl0m1/xtevedocker image, will check out dnsforge/xteve which also has the providers included.

Thanks
