### ISSUE TITLE
Filter-Option: Replace strings in channel names

### ISSUE THREAD

**Issue by acuntex** [xteve-project/xTeVe#61]
**Is your feature request related to a problem? Please describe.**
Some IPTV-Providers have strange names or even buggy names.

e.g.:

> US: ...

In this case it would be nice, if a user could define replace-options in the Filter dialog, so that the user could e.g. remove the "US: " from the beginning of the name. Maybe even with regexes.

**Comment by mar-mei** [comment]
That will not be possible. xTeVe needs the original channel name for the mapping.

With each editor you can open the xepg.json file and change the channel name there with replace it. xTeVe should be closed and make a backup before.

xepg.json - cahnel name:
```JSON
"x-name": "Channe Name",
```

**Comment by acuntex** [comment]
@mar-mei xTeVe can still save the original name internally and use it for the mapping.

But in the m3u and in the UI you show the display name, which is a modified name.

This seems far away from not possible.

**Comment by mar-mei** [comment]
I will not implement a Find / Replace function. That just makes everything more complicated. You can change the channel name in the UI or edit the xepg.json file with an editor.
