### ISSUE TITLE
Move Hardcoded DVRConfig Limit to modifiable config

### ISSUE THREAD

**Issue by robertwary** [xteve-project/xTeVe#63]
With the count of channels provided from IPTV providers, even filtered down it passes the hard coded limit. I've done manual builds to get around this. 
System.DVRLimit = 480

It would be ideal if this was modifiable within one of the config files or the UI.

**Comment by mar-mei** [comment]
xTeVe it does not matter if you exceed the value, it is only a warning and affects only Plex.
90% of all problems concern Plex, if I make this value changeable, there are more problems with Plex.
