### ISSUE TITLE
Disable user-agent option unless buffer set to "xTeVe" as Buffer and Buffer is activated

### ISSUE THREAD

**Issue by MCTyler** [xteve-project/xTeVe#64]
Pretty much what the title says to avoid confusion. I realize now that user-agent has no effect unless "xTeVe" is set as the buffer and the buffer is activated....But they may help with the confusion of `user-agent`
![image](https://user-images.githubusercontent.com/6390898/69260599-c4e32d80-0b85-11ea-8199-dcad5d6d2beb.png)

**Comment by mar-mei** [comment]
For every HTTP(S) connection, the user agent is set in the HTTP header.
If the provider wants, he can evaluate this value.

When does the provider see the user agent?
1. When xTeVe downloads the M3U file
2. If xTeVe downloads the XMLTV file
3. When the buffer is set to xTeVe.

Download examples, the server of the provider sees only the components that are written in **bold**:
Buffer set to xTeVe:
SERVER <---> **xTeVe** <---> [Plex / Emby / M3U Player]

Buffer set to FFmpeg:
SERVER <---> **FFmpeg** <---> xTeVe <---> [Plex / Emby / M3U Player]

Buffer set to VLC:
SERVER <---> **VLC** <---> xTeVe <---> [Plex / Emby / M3U Player]

> Since with VLC or FFmpeg xTeVe does not connect to the server of the provider, this sees not the user agent of xTeVe, but of FFmpeg / VLC.

Buffer off:
SERVER  <---> **[Plex / Emby / M3U Player]**

**Comment by MCTyler** [comment]
I understand that (kind of) but that doesn't change the fact that the user-agent setting gives users the sense that they are indeed effecting the Streams by changing user agent in xTeVe no matter what their Buffer settings are. 
As it stands, it's far too complicated for the average user (like me) to know when/what user-agent is being used and this setting, as misunderstood thinking it will effect the quality of streams. 
It took you a complete page to explain it, when it can simply be grayed out to avoid confusion when it will not effect the streams in any way.

**Comment by mar-mei** [comment]
I'll take a look at VLC and FFmpeg more closely, maybe there can change the user agent synonymous, then everything would be consistent.
