### ISSUE TITLE
Combine Dupes for Seamless Failover

### ISSUE THREAD

**Issue by nayrnet** [xteve-project/xTeVe#66]
**Is your feature request related to a problem? Please describe.**
With multiple tuners or m3us, you may end up with redundant channels with varying levels of quality and sources.. If one goes offline you have to manually find the next dupe if you didnt remove dupes to keep within channel limits.

**Describe the solution you'd like**
I would like a solution to assign multiple channels to the same number, with some indicator for priority.. ie, 10 = Primary, 10A = Secondary, 10B = Tertiary

When using the xTeVe buffer, the m3u would only contain channel 10, not the sub channels and if the primary stream fails to load, it should automatically try the secondary stream, and so on until its exhausted all options.  

**Describe alternatives you've considered**
Duplicate Channels are confusing, and a hassle if you start getting multiple provider sources, also plex has a limit on channels so low bandwith streams and varying upstream sources are likely to be deactivated, and would require manual activation.. thats a clunky work around at best.

**Additional context**
Also should failover if the source runs out of streams but a backup has some available.. So instead of getting multiple streams from one provider you could instead get single streams from multiple providers.. or multiple accounts from one provider if they dont provide an adequate number of streams.

I understand that this functionality would require use of the buffer, and that is perfectly fine.

**Comment by MCTyler** [comment]
Have you tried 10, 10.1, 10.2? ...or is decimals not a option?

**Comment by nayrnet** [comment]
I also have a HDHR mapped in w/digital sub-channels so that would not be consistent.. right now I just have the channel listed multiple times in a row but if you search for something you get multiple channels and little indication what stream is preferable. 

I dont think it would of been that feasible to implement failover prior to the new ffmpeg/vlc buffers, but since they now exit w/an error code if it cant load the stream for whatever reason it seems the effort now would be much less.. if exit code != 0 then try next stream.

**Comment by mar-mei** [comment]
That would only work reasonably if the streams in the M3U all have an ID. #12

**Comment by nayrnet** [comment]
it would work if M3U didnt have an ID as is if you can stack them by channel numbers manually. 

Mebe a check box on a channel that says: stacked, and then sub channels like .1, .2, .3, .4 get condensed.. this would allow both OTA style numbering, and alternate streams both use floats.

**Comment by mar-mei** [comment]
M3U playlists change regularly. Every change has an effect on the channel number. As long as the streams in the M3U have no ID, the backup channels would have to be re-established with each M3U update.

**Comment by nayrnet** [comment]
Ive got 4 ESPN's all right after eachother numbered how I wanted em and the m3u's been updating just fine for months.. I'm not sure why you think these would not survive a m3u update but I dont see things moving around much. 

I'm able to maintain custom numbering just fine w/xteve and changes to the playlist dont wreak havoc on it.. mebe because I'm filtering out all but the basics which havent been changing?

**Comment by GroupMaster** [comment]
It sounds like nayrnet is talking about pooling streams. I haven't found anything that can do this so I am in mid-development on a php file that uses sql and does just that. It works as the holder of all the actual URLs, so it works along side of xteve. When a stream is requested, the php program gets a list of possible streams in order of preference from the db. It tests one stream at a time and forwards the client to the first stream that works. One fault of this is the initial setup, all the channels and streams need to be entered into the db before it can be useful. All changes thereafter are done by replacing stream URL references. A work in progress..
