### ISSUE TITLE
Restream m3u playlist

### ISSUE THREAD

**Issue by XanXus96** [xteve-project/xTeVe#67]
Hello, if anyone can help me, can i use this software to restream my m3u playlist working for only one user to my friends? if yes how?

**Comment by MCTyler** [comment]
Like with a Media Player? Plex/Emby

**Comment by XanXus96** [comment]
> Like with a Media Player? Plex/Emby If you mean more connections than your allowed, Yes, with Buffer but only 1 channel.

Yes that s what i mean, can u help me please with the full procedure knowing that what i have in hand now is only the plylist

**Comment by MCTyler** [comment]
This is more for issues rather than a help forum, please join us on Discord......https://discord.gg/uBTCeJ
