### ISSUE TITLE
Premiere tag stripped out of EPG

### ISSUE THREAD

**Issue by pcm2a** [xteve-project/xTeVe#68]
**Describe the bug**
XMLTV epg data that has `<premiere />` tags are stripped out by XteVE

**To Reproduce**
1. Import a xmltv guide that has `<premiere />` tags
2. Download the XteVE xml guide
3. `<premiere />` tags are gone

**Expected behavior**
Expect that <premiere /> tags remain so DVR applications know it is a new episode.

**Screenshots**
Before:
```
<programme start="20191125020000 +0100" stop="20191125030000 +0100" channel="Showtime.us">
    <title lang="en">Ray Donovan</title>
    <sub-title lang="en">A Good Man is Hard to Find</sub-title>
    <desc lang="en">Ray must find a new way to get Detective Perry off his trail while reckoning with a personal loss. When Bunchy's pharmacy is under attack, he takes matters into his own hands and is catapulted into the public spotlight</desc>
    <credits>
      <actor>Liev Schreiber</actor>
      <actor>Eddie Marsan</actor>
      <actor>Dash Mihok</actor>
    </credits>
    <category lang="en">Drama</category>
    <icon src="cdn.tvpassport.com/image/show/960x540/57809.jpg"/>
    **<premiere/>**
    <rating system="US">
      <value>TVMA</value>
    </rating>
</programme>
```
  
After:
```
<programme channel="1027" start="20191125010000 +0100" stop="20191125020000 +0100">
          <title lang="en">Ray Donovan</title>
          <sub-title lang="en">Faith. Hope. Love. Luck.</sub-title>
          <desc lang="en">Ray brings Mickey to the FBI to turn himself in. Four months later when one of the police officers&#39; heads turns up and Ray and his family are implicated in the murder, Ray finds his work with his therapist threatening to unravel</desc>
          <category lang="en">Drama</category>
          <icon height="" src="cdn.tvpassport.com/image/show/960x540/57809.jpg" width=""></icon>
          <video></video>
          <date></date>
</programme>
```

**Comment by MCTyler** [comment]
Not a standard <TAG>, Marmei will have to see if interested in adding support for this.

**Comment by pcm2a** [comment]
Thanks for that info, I did not know that. Emby, Plex, and TV Mosaic all support the premier tag to know if a show is new. Maybe they look for a new tag as well.

Maybe there could be an option that just keeps extra tags, that you could toggle on?

**Comment by mar-mei** [comment]
I do not know the premiere day. I know only the new tag. Plex needs the new tag and an episode system, Emby also uses the live tag. I will test the premiere tag with Plex and Emby. If everything works, I implement it.

**Comment by pcm2a** [comment]
Great! I've been using Emby for a while and iptv-epg outputs the premiere tag. I recently switched to TV Mosaic with xTeVE and I had no "new" shows until I switched back to my other guide. Let me know if you need a xmltv with it as an example.

**Comment by mar-mei** [comment]
You can use the current beta (v2.1.0.0105-beta):
https://github.com/xteve-project/xTeVe/blob/master/changelog-beta.md
