### ISSUE TITLE
Error trying to install linux arm 

### ISSUE THREAD

**Issue by dmota13** [xteve-project/xTeVe#69]
Hi,

I am trying to install this on asus ac5300 running Merlin and entware. When i run command ./xteve i get the following error. 

 ./xteve: line 3: syntax error: unexpected "("

Please advise

**Comment by MCTyler** [comment]
You need to include a lot more information.....How did you get to the point of running `./xteve` ?

**Comment by dmota13** [comment]
I followed the directions on main page. 
1)Wget the file. 
2)unzip it
3)chmod it
4)run ./xteve 
5) error code

**Comment by MCTyler** [comment]
Never tried running xTeVe on a Router, so I'm out of ideas...Sry

**Comment by dmota13** [comment]
Can you please point me in right direction to make/try custom build

**Comment by alturismo** [comment]
your merlin is setted for x64 ?

![image](https://user-images.githubusercontent.com/8406490/73598860-91396200-453d-11ea-8aba-cdacd647db71.png)
