### ISSUE TITLE
Backing up settings while using SSH port forwarding

### ISSUE THREAD

**Issue by thomashw** [xteve-project/xTeVe#7]
If I remotely connect to my server using SSH port forwarding:
`ssh -L 34400:localhost:34400 user@server`

I can remotely browse xTeVe in a browser by visiting `localhost:34400/web`.

If I try to make a backup (Settings -> Backup), xTeVe tries to automatically download the backup using the server's local IP (192.168.1.67) which fails because it's not local in this case. Downloading using `localhost` succeeds.

Running xTeVe 2.0.0.0001 on Ubuntu 18.04.2 LTS.

**Comment by mar-mei** [comment]
Fixed in v2.0.1
