### ISSUE TITLE
Issue with Exported XML

### ISSUE THREAD

**Issue by nick-harper** [xteve-project/xTeVe#70]
Hi

The XML file only seems to go up to midnight of that day so it means I can't see the listings for tomorrow within Plex.

Is there a way to change this to export more listings for the future?

**Comment by mar-mei** [comment]
you have to ask your provider, xTeVe only copies the contents of the XMLTV files.

**Comment by MCTyler** [comment]
Or use a Secondary EPG like Schedules Direct or Zap2Xml. Those both have 14 days of Data (if configured that way)

**Comment by daving** [comment]
Hi,
I have the same problem, but I verified my provider XML has a full EPG, and that's not showing in the xteve output xml. Any ideas?

[xmltv files.zip](https://github.com/xteve-project/xTeVe/files/4089162/xmltv.files.zip)

**Comment by GroupMaster** [comment]
There is an option to update on startup as well as an update schedule which by default triggers at midnight.

How did you verify that there is more than one day of epg from your provider?  I made an epg checker with PHP and I have noticed some of the IPTV providers have bad guide data. The one example I can remember clearly was on most nights, around midnight, a small 15 minute show was included with a particular channel's XML but the XML was already complete, causing an overlapping program. I would suggest the root cause is likely your EPG provider.

**Comment by daving** [comment]
I used an online XMLTV parser to compare the two, and the files in the zip I included shows the clear difference. After a while (maybe a day or two) i check plex and it has updated, but something is definitely wrong. If you see a reason why the 2 XMLs would be different please let me know, I'm stumped.

**Comment by alturismo** [comment]
may check your update settings and your data path, u have the downloaded xml and the updated xteve.xml there ... and some logs would be helpful if there are errors, otherwise, checked here and all my xml´s (5) are as expected.

**Comment by daving** [comment]
So I realized that my xmls at some point grow from ~10MB to over 20MB (hit the plex limit). I purged and let xteve redownload the XMLs, and they went back to ~10MB and all was fine again. So I will continue to monitor the issue, not sure why that happened. When I get time I'll parse the offended xml to see if it had crazy duplicates or something.

**Comment by alturismo** [comment]
use the file path instead http link to load the epg in plex, then u dont have this limit.
btw, i have 14 day epg with ~ 100 channels, running daily updates and the size is always ~ 40 mb.
also this, u can compare the downloaded xml in your data folder.

**Comment by MCTyler** [comment]
My Direct TV Guide is 80Mb, this is Normal for 14 days of data....Just confirming what Alt has said, nothing wrong with your Guide...
![image](https://user-images.githubusercontent.com/6390898/73605281-0323a280-4562-11ea-9d44-3db858d32a40.png)
