### ISSUE TITLE
Custom Desc for channel with Xteve_dummy 

### ISSUE THREAD

**Issue by NH-Networks** [xteve-project/xTeVe#71]
would it be possible to add a option to specify a custom desc per channel when using xteve_dummy? 

it looks nicer, even if there is no epg data for that channel to seen a nice desc with info over that channel. 

thanks in advanced.

**Comment by mar-mei** [comment]
Can you describe something more precisely. What should be displayed in the dummy EPG?

**Comment by NH-Networks** [comment]
for example 

This wil now be display in epg for channel **NL: BNR TV** when settings epg to xteve-dummy (60 Minutes)

it would be great if there is a extra "text field" under the xteve-dummy (60 Minutes) dropdown menu, where you can set a custom description for that channel. 

so the final epg looks like this: 

`      <programme channel="1036" start="20191210000000 +0100" stop="20191210010000 +0100">
          <title lang="en">NL: BNR TV (Tu. 00:00 - 01:00)</title>
          <desc lang="en">**This is my description of this wonderfull channel, a channel about local news in a region of The Netherlands**</desc>
          <episode-num system="original-air-date">2019-12-10 00:00:00</episode-num>
          <icon height="" src="icon.png""></icon>
          <video></video>
          <date></date>
          <new></new>
      </programme>`

**Comment by MCTyler** [comment]
It looks like you want to add EPG info to a channel that has no EPG at all? Please explain where this data you have above comes from for a channel without this data. `<programme channel="1036" start="20191210000000`

**Comment by mar-mei** [comment]
He wants to have a channel description in the xteve.xml. This will then be displayed in the DVR client.
I think the idea is good for the dummy because the channel name should not be too long.

![image](https://user-images.githubusercontent.com/43099631/70731334-d348e300-1d06-11ea-832f-074f53c6810e.png)

**Comment by MCTyler** [comment]
Description...ok....As long as it doesn't hurt the current CUID PPV Sports Channels, Please :)

**Comment by mar-mei** [comment]
Do not worry, the name will not be changed. In the next few days comes an update.

![image](https://user-images.githubusercontent.com/43099631/70738197-8d931700-1d14-11ea-9616-b6f036a83b34.png)

**Comment by NH-Networks** [comment]
> Do not worry, the name will not be changed. In the next few days comes an update.
> 
> ![image](https://user-images.githubusercontent.com/43099631/70738197-8d931700-1d14-11ea-9616-b6f036a83b34.png)

Thank you! thats exactly what i mean.. :)

**Comment by mar-mei** [comment]
No problem.
