### ISSUE TITLE
Incorrect parcing is happening for my m3u.

### ISSUE THREAD

**Issue by bulzipke** [xteve-project/xTeVe#72]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
1. All channel names appear as AAA
2. My CUID is ignored and the channel starts from 1000

**Server (please complete the following information):**
- OS [Linux - Unraid - docker]
- Arch [Intel 64 Bit]
- xTeVe Version and Build [2.1.1 Build: 0112]

**To Reproduce**
1. Go to 'XMLTV - NEW - TXMLTV File - Save'
This is my m3u file
> #EXTM3U
> #EXTINF:-1 CUID="13.1" tvg-id="" tvg-name="AAA" tvg-logo="http://mylocalhost/logo/13.1.png"
http://mylocalhost:5004/auto/ch789000000-1
> 
> #EXTINF:-1 CUID="13.2" tvg-id="" tvg-name="BBB" tvg-logo="http://mylocalhost/logo/13.2.png"
> http://mylocalhost:5004/auto/ch789000000-2
> 
> #EXTINF:-1 CUID="7.1" tvg-id="" tvg-name="CCC" tvg-logo="http://mylocalhost/logo/7.1.png"
> http://mylocalhost:5004/auto/ch783000000-2

**Expected behavior**
My CUID is displayed as channel, and tvg-name is displayed as channel name.

**Screenshots**
![image](https://user-images.githubusercontent.com/15259720/70865751-520e7c00-1fa4-11ea-9b2b-e8288e9d4d18.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [78.0.3904.108]

**Additional context**
I tried https://github.com/xteve-project/xTeVe/blob/master/src/internal/m3u-parser/test_list_1.m3u but it didn't help.

**Comment by mar-mei** [comment]
1. Your M3U playlist is incorrectly formatted.
It should look like this:
```
#EXTM3U
#EXTINF:-1 CUID="13.1" tvg-id="" tvg-name="AAA" tvg-logo="http://mylocalhost/logo/13.1.png", AAA
http://mylocalhost:5004/auto/ch789000000-1

#EXTINF:-1 CUID="13.2" tvg-id="" tvg-name="BBB" tvg-logo="http://mylocalhost/logo/13.2.png", BBB
http://mylocalhost:5004/auto/ch789000000-2
```

2. Every new channel got the first free channel number from 1000. CUID is used as unique stream ID, not as the channel number.
Channel numbers are ignored because they can appear twice when using multiple playlists.

**Comment by bulzipke** [comment]
> 1. Your M3U playlist is incorrectly formatted.
>    It should look like this:
> 
> ```
> #EXTM3U
> #EXTINF:-1 CUID="13.1" tvg-id="" tvg-name="AAA" tvg-logo="http://mylocalhost/logo/13.1.png", AAA
> http://mylocalhost:5004/auto/ch789000000-1
> 
> #EXTINF:-1 CUID="13.2" tvg-id="" tvg-name="BBB" tvg-logo="http://mylocalhost/logo/13.2.png", BBB
> http://mylocalhost:5004/auto/ch789000000-2
> ```
> 
> 1. Every new channel got the first free channel number from 1000. CUID is used as unique stream ID, not as the channel number.
>    Channel numbers are ignored because they can appear twice when using multiple playlists.

Oh, I see. Thank you for Xteve and you.
