### ISSUE TITLE
Channel mapping is not automatic

### ISSUE THREAD

**Issue by bulzipke** [xteve-project/xTeVe#73]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Channel mapping is not automatic. in spite of the following setting
> tvg-id (M3U) == channel id (XMLTV)

**Server (please complete the following information):**
- OS [Linux - Unraid - docker]
- Arch [Intel 64 Bit]
- xTeVe Version and Build [2.1.1 Build: 0112]

**To Reproduce**
1. Playlist - New - M3U - my file path to M3U File - Save
2. XMLTV - New - my file path to XMLTV File - Save
3. Mapping -> Everything looks red. There's no green.

**Expected behavior**
The Playlist and XMLTV are mapped automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/15259720/70878736-01c80600-2006-11ea-93fb-9bb80eae39aa.png)

**Desktop (please complete the following information):**
- OS: [Windows]
- Browser [chrome]
- Version [78.0.3904.108]

**Additional context**
These are sample of my Playlist and XMLTV.
> #EXTM3U
> #EXTINF:-1 tvg-id="13.1" tvg-name="EBS1" tvg-logo="http://myserver/logo/13.1.png", EBS1
> http://myserver/auto/ch789000000-1

>`<tv generator-info-name="epg_maker">`
>`  <channel id="13.1">`
>`    <display-name>EBS1</display-name>`
>`    <display-name>BBB</display-name>`
>`    <display-name>CCC</display-name>`
>`    <display-name>EBS1</display-name>`
>`    <icon src="myserver/logo/13.1.png"/>`
>`  </channel>`

**Comment by mar-mei** [comment]
Only new channels are assigned automatically.
If you first enter the XML and then the M3U file, it works.

![image](https://user-images.githubusercontent.com/43099631/70931544-f988be80-2037-11ea-94bb-5ad6319780ba.png)

**Comment by MCTyler** [comment]
That seems backwards with how a new setup is.....Isn't it M3U First, then it asks you for XML Link? Mine has always auto-mapped.

**Comment by bulzipke** [comment]
> Only new channels are assigned automatically.
> If you first enter the XML and then the M3U file, it works.
> 
> ![image](https://user-images.githubusercontent.com/43099631/70931544-f988be80-2037-11ea-94bb-5ad6319780ba.png)



> That seems backwards with how a new setup is.....Isn't it M3U Link First, then it asks you for XML Link? Mine has always auto-mapped though.....Not sure what the real issue is here....
> 
> Here's the way my m3u and xml link....
> 
> `tvg-ID="space.ca" ----- m3u`
> `channel id="space.ca" ---- xml`


This is my full plain m3u & xml link
https://cloud.bulzipke.com/s/92kY8J9NBP3r5Zw
Thank you for your kindness.

**Comment by mar-mei** [comment]
Works as expected
![image](https://user-images.githubusercontent.com/43099631/71015621-3619f000-20f4-11ea-878e-ac7e2cf5e8b4.png)

**Comment by bulzipke** [comment]
I think there was something wrong with me.
It works out well for me to do it again. Thanks again for your hard work T_T
