### ISSUE TITLE
Ability to Specify Listen IP Address

### ISSUE THREAD

**Issue by bobey6** [xteve-project/xTeVe#74]
Hello,

It'd be really nice to be able to specify an specific IP address when starting xTeVe. Although xTeVe listens & serves on all interfaces, if you use xTeVe to generate your XEPG file then the XML file created will use whatever IP address xTeVe picked as the primary interface to populate the URL for images within the XML file. For me, xTeVe picks my VPN interface, So when I try to configure a new DVR in my local network, the XML file has the VPN interface IP address and no images will download for the guide as it's not reachable.  My work around for now is to use sed to replace the IP address in the XEPG file with one that is reachable and then serve that file via Apache instead.

```
<programme channel="1060" start="20191219203000 -0500" stop="20191219210000 -0500">
          <title lang="">TV Show</title>
          <desc lang="">My Favorite TV Show.</desc>
          <icon height="" src="http://10.0.0.1:34400/images/ab5bd084ca0825c7467d0c79bf4fb8cf.png" width=""></icon>
          <video></video>
          <date></date>
      </programme>
```

**Comment by mar-mei** [comment]
This will lead to many issues with DHCP or IPv6.
When starting xTeVe uses the last IP address of your OS, in your case that of your VPN interface.

With any HTTP request, xTeVe recognizes via which IP or domain the request was made. Except for downloading the xteve.xml, the URLs are generated immediately. (M3U, DVR lineup). The XML file can take several seconds to create, so the URLs in the XML are not changed immediately. The next time the xteve.xml file is created, the new URL will be taken into account

But that works with the xTeVe API
With the API function **update.xepg** you can create the xteve.xml and xteve.m3u file with with a specific IP address or domain.

Example with curl (IP 10.10.0.10):
`curl -X POST -H "Content-Type: application/json" -d '{"cmd":"update.xepg"}' http://10.10.0.10:34400/api/`

xteve.xml:
```XML
  <tv generator-info-name="xTeVe" source-info-name="xTeVe - 2.1.1">
      <channel id="1105">
          <display-name>Bunny HD 1</display-name>
          <icon src="http://10.10.0.10:34400/images/0485a5651a59142f0a0d6edfe8069f54.png"></icon>
      </channel>
  </tv>
```


Example with curl (domain mbp.local):
`curl -X POST -H "Content-Type: application/json" -d '{"cmd":"update.xepg"}' http://mbp.local:34400/api/`

xteve.xml:
```XML
  <tv generator-info-name="xTeVe" source-info-name="xTeVe - 2.1.1">
      <channel id="1105">
          <display-name>Bunny HD 1</display-name>
          <icon src="http://mbp.local:34400/images/0485a5651a59142f0a0d6edfe8069f54.png"></icon>
      </channel>
  </tv>
```

**Comment by bobey6** [comment]
While I appreciate the reply, I'm not sure how being able to specify a specific IP address to listen on could possibly lead to issues with DHCP or IPv6. The default behavior would still be to listen on all interfaces, but add a configuration option to allow you to specify just a single interface. I'm honestly hard pressed to think of any other software that won't let you do this and was a bit surprised when I discovered you couldn't. I'll look into patching it myself, wish me luck :)

**Comment by OneCyrus** [comment]
this issue really blocks me from using it. on windows it takes always a random IP from those available. with 7 IPs on this machine it is almost impossible to get the right one. most of the time it takes the docker IPs and so it won't work. binding it to a fixed IP would come a long way.

**Comment by MCTyler** [comment]
xTeVe uses a Docker IP when it's ran outside of Docker? I find this behavior very strange.

**Comment by mar-mei** [comment]
An API (update.xepg) call after starting xTeVe solves the issue.

No idea if this works with Docker, my FreeBSD server also has several IP addresses, but the jail (similar to Docker) in which xTeVe runs has only one IP address from the server.

ifcofig server:
```
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e527bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether d0:50:99:xx:xx:11
	inet 192.168.178.1 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.2 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.3 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.4 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.5 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.6 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.7 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.8 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.10 netmask 0xffffff00 broadcast 192.168.178.255
	inet 192.168.178.9 netmask 0xffffffff broadcast 192.168.178.9
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

ifconfig xTeVe Jail:
```
igb0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e527bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether d0:50:99:xx:xx:11
	inet 192.168.178.3 netmask 0xffffff00 broadcast 192.168.178.255
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
```

**Comment by OneCyrus** [comment]
> xTeVe uses a Docker IP when it's ran outside of Docker? I find this behavior very strange.

not a container IP. it's binding to the host IP of the docker NAT interface.

**Comment by alturismo** [comment]
may i ask where the issue is ?

u call xteve via 192.168.1.2 as sample and the ip in the m3u will be 192.168.1.2 ...
u call xteve via domain behind reverse proxy and m3u will be generated via the domain.

so i wonder where there could be any issue ?

native on host, u use the host ip to connect to xteve
in docker in host/bridge mode, u map the port from host to docker, u use the ip from docker host
behind reverse proxy, upper steps, then map reverse to xteve, u se the domain from reverse

all checked and 100 % working here ... so may please leave a real life scenario where it aint work ?

**Comment by OneCyrus** [comment]
i have this issue here: https://github.com/xteve-project/xTeVe/issues/84 and it only works again when xteve starts up with the same interface again. not sure what's going on.

**Comment by MCTyler** [comment]
https://raw.githubusercontent.com/xteve-repo/images/master/xteve-plex-device-not-found.png

**Comment by jzahraoui** [comment]
I will really enjoy if its possible restrict the listening to a single IP address. I don't really want to listen on ipv6 address and make xTeVe available from the internet.
In may case plex and xTeVe are on the same machine, so listening on 127.0.0.1 address will be enough for me.
as we can specify a listening port we can specify an ip don't you think so ?

**Comment by alturismo** [comment]
just dont open the port, then its not available outside your LAN.

in the end there is no benefit to bind the ip to one specific ... next step would be if you run xteve through a VPN and still want to be able to connect locally ...

so may describe what is really the point to bind to a specific ip ?

**Comment by jzahraoui** [comment]
You totally right, but I just want to have the choice. most of users will use default that will be listening on all IP (0.0.0.0 or ::), but some other users will want to change it, and will be be happy if they can :)

for example, "binding to the host IP of the docker NAT interface" and broadcasting on this interface do not make sense for me.

sometimes when you troubleshooting, you need to make the things clear by disabling unnecessary workload, traffic flows, etc.
