### ISSUE TITLE
Stream buffer with FFmpeg does not allow more than one connection

### ISSUE THREAD

**Issue by raface** [xteve-project/xTeVe#75]
**Describe the bug**
I have setup Xteve with my provider and I set both the M3U and Xteve settings with 5 tuners. However, when I open Plex in more than one client I can see the FFmpeg uses only one thread and it's is buffering only the latest channel I choose.
That is causing all the previously open channels on the other clients to freeze.

**Server (please complete the following information):**
- OS Ubuntu Server
- Arch ARM64
- xTeVe 2.1.1
**To Reproduce**
1. Add a M3U playlist
2. Set the number of turners to more than 1
3. Enable buffer choose FFmpeg, choose the number of turners to more than 1 and leave everything else as default.
4. Open multiple Plex clients and access the live tv guide and choose different channels
5. Open a terminal and filter the FFmpeg threads, you should see that just one is open with the latest channel you choose.

**Expected behavior**
If multiple clients access live tv all of them should be able to play.

**Comment by mar-mei** [comment]
Works for me with Plex, Emby and M3U player
![image](https://user-images.githubusercontent.com/43099631/71380871-45f07300-25d1-11ea-827f-84bbe116271d.png)

**Comment by bobslaede** [comment]
I have the same issue. Only one instance of ffmpeg is running.

**Comment by bobslaede** [comment]
Also, if Im using xteve as buffer. If I then try to tune in two channels they will just start to loop for the buffer size apparently.
Both will just loop, until one client disconnects, and then the one left will start to stream again.

**Comment by redbone75** [comment]
Same issue.  Using xteve as the stream buffer I can stream more than one connection.

using ffmpeg or vlc will not let me stream more than one.  


2020/02/01 10:25:17 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204
2020/02/01 10:25:18 [xTeVe] Streaming Status:      Buffering data from FFMPEG
2020/02/01 10:25:51 [xTeVe] [ERROR] FFMPEG error () - EC: 0


The issue can be recreated by opening up vlc twice and launching the same network stream.  Playing two streams in each instance of vlc.

**Comment by mar-mei** [comment]
I would look for the error in the FFmpeg log. xTeVe passes the URL and the parameters to FFmpeg and waits until FFmpeg provides the stream. For testing, I always use VLC or IINA, even with multiple streams. All my tests with the default FFmpeg parameters in xTeVe.

**Comment by redbone75** [comment]
> I would look for the error in the FFmpeg log. xTeVe passes the URL and the parameters to FFmpeg and waits until FFmpeg provides the stream. For testing, I always use VLC or IINA, even with multiple streams. All my tests with the default FFmpeg parameters in xTeVe.

All I know at this moment is that it works with xteve as the Stream Buffer.  When I use VLC or FFmpeg, one stream dies when I try to play a stream on the other instance of VLC, Kodi, or anything.

Is it possible that I'm not allowed more than 1 stream, but somehow xteve buffer is getting around it somehow?

**Comment by redbone75** [comment]
when the other stream kicks up, i see this in the xteve log window.

2020/02/01 11:45:24 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204

However I didn't click stop on any of the streams.  ffmpeg.exe dies.  another ffmpeg.exe lauches.  It's back and forth... 2 ffmpeg.exe will not run, but the error in the log window is listed above.

Again... doesn't happen with xteve stream buffer.

**Comment by mar-mei** [comment]
It's not magic what xTeVe does with FFmpeg, it's just FFmpeg CLI commands. All FFmpeg processes are then managed by the OS.

Here again a test with FFmpeg, the two players above show the same stream, the lower one another.

![image](https://user-images.githubusercontent.com/43099631/73596596-b15c2780-4523-11ea-9443-ec74929b8e97.png)

**Comment by redbone75** [comment]
I'm in windows.  Maybe that's the issue.

What are your ffmpeg switches?

I've even tried using another login account and running xteve twice and renaming ffmpeg.exe to ffmpeg2.exe.  I'm connecting to 34400 on one vlc and 34401 on the other vlc.  Same issue occurs.  I can watch task manager be running ffmpeg.exe and then die when i launch a stream using ffmpeg2.exe

Is there anything special about xteve stream buffer?  What is is's underlying stream buffer?  Weird it works with xteve and not ffmpeg/vlc.  THe only reason i'm wanting to use ffmpeg is it seems like backwards skipping doesn't happen with ffmpeg on some channels like it does with xteve

**Comment by redbone75** [comment]
One thing I have noticed is that xteve appears to be duplicating playlists and tuners?

2020/02/01 12:31:46 [xTeVe] Streaming Status:      Playlist:  - Tuner: 0 / 2
2020/02/01 12:31:47 [xTeVe] Streaming Status:      Playlist:  - Tuner: 1 / 2

Using xteve as a stream buffer, it doesn't look like this.

**Comment by MCTyler** [comment]
I never configured anything in xTeVe or renamed anything in Windows for Buffer...I just activated Buffer and pointed xTeVe to the path of ffmpeg.exe and it worked. I think your making things more complicated than they need to be.   
![image](https://user-images.githubusercontent.com/6390898/73597412-5578ab00-44f1-11ea-9c7e-0a23bf9cefc8.png)

Those are all default settings besides the Path which can be acheived by leaving them blank and allow xTeVe to auto-fill.

**Comment by MCTyler** [comment]
Seems your other error is running 2 versions of xTeVe and using the same settings.json file.

**Comment by raface** [comment]
I don't think this is a windows problem. I use Ubuntu 18.04 and I am having the same problem when using docker and installing direct on the system.

**Comment by MCTyler** [comment]
I was responding to redbone75, I don't know how docker works in accessing resources outside the container...See Docker wiki.

**Comment by MCTyler** [comment]
There are some Docker experts on Discord for Docker related help......https://discord.gg/GUzuWv

**Comment by raface** [comment]
> I was responding to redbone75
I was answering him too, that it is not a Windows problem since I have the same issue on Linux with or without Docker.
I also didn't change anything besides choosing FFMPEG and/or VLC as the buffer.

**Comment by mar-mei** [comment]
@redbone75 
The xTeVe buffer does not start a new process, all streams are processed by xTeVe. FFmpeg and VLC start their own process, a new process for each new stream.

![image](https://user-images.githubusercontent.com/43099631/73598230-dfe2fe00-4535-11ea-8149-5894db1751d8.png)

**Comment by MCTyler** [comment]
Can't Duplicate this issue, Seems more ffmpeg, VLC or System Related...Sry

**Comment by alturismo** [comment]
here on docker with ffmpeg as buffer, 2 streams, 2 instances.
working on my docker alturismo/xteve, pretty sure also working on dnsforge, so no issue

![image](https://user-images.githubusercontent.com/8406490/73598599-b678a100-453a-11ea-8484-a87fdac591c7.png)

**Comment by MCTyler** [comment]
> here on docker with ffmpeg as buffer, 2 streams, 2 instances.
> working on my docker alturismo/xteve, pretty sure also working on dnsforge, so no issue
> 
> ![image](https://user-images.githubusercontent.com/8406490/73598599-b678a100-453a-11ea-8484-a87fdac591c7.png)

Windows too.......

**Comment by redbone75** [comment]
Thanks.  This helps me in my conclusion.  After much testing, I've come to the conclusion that xteve works around providers that only give 1 stream.  If your provider gives you multiple streams, this issue I was describing is not experienced in ffmpeg and vlc.

**Comment by dnsforge-repo** [comment]
Yes, you will need a minimum of (2) lines from your provider to do this.  The streaming server will simply drop any connecting past (1) connection otherwise.

**Comment by MCTyler** [comment]
Unfortunately, I have seen a lot who thinks they can "hack" more lines from Provider like this :(

**Comment by raface** [comment]
I think that might clarify what is happening.
However, I thought that the buffering option would allow you to have multiple Plex clients connecting to live tv even if your provider allows only one connection. Did I misunderstood the idea behind buffering? If so what is the use case for the buffering settings?

**Comment by mar-mei** [comment]
![image](https://user-images.githubusercontent.com/43099631/73607821-6beb3900-45bb-11ea-97f8-b64d8268ef0e.png)

How do you get this idea? If your source only allows one connection, then only one connection should be set at Tuner. My TV tuner allows 2 connections, so I set 2. With every new connection to the source, xTeVe checks whether the tuner limit has been reached, if so there is an error message and no older stream is ended.
You can find more detailed information in the documentation:

https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/configuration.md

**Comment by raface** [comment]
Thanks, for taking the time to help me.

I got from this `xTeVe monitors all client connections and allows re-streaming, so that multiple clients can request the same stream and it is only one connection to the provider.`
I think my mistake was that I should set the tuner number for the number of simultaneous connection I was expecting that list to have.

But I still don't understand the mentioned text above. Does it means that when buffering is enable if client A is watching channel 1 and client B start to watch channel 1 the provider will only see 1 connection? Or that if client A is watching channel 1 and client B is watching channel 2 the provider will se only one connection?

**Comment by alturismo** [comment]
this is no issue and there is nothing to help.
make it short, u can ONLY restream as many DEFFERENT channels as the amount u can get from your provider.
@mar-mei issue can be closed
