### ISSUE TITLE
Using xteve with redundant guide providers.

### ISSUE THREAD

**Issue by GroupMaster** [xteve-project/xTeVe#78]
I would like clarification on how xteve deals with duplicate epg ids when loading more than 1 xml file.  Each of the xml files contains mostly the same set of channels as the other files, channels that may or may not use the same actual tvg-id. Upon importing a provider's xml file, xteve uses the tvg-id of each channel in the playlist and matches it to one among all the loaded xml. Since the point of my scenario is redundancy, duplicate tvg-id are expected. Is there a way to specify from the m3u, which provider to use the tvg-id from? I know I can manually set them up in xteve but I am looking to do it at time of loading the m3u automatically. I can easily supply additional tags or even modify the existing tvg-id tag to a "provider:tvg-id" nomenclature within the original m3u given to xteve. Any help would be much appreciated.

**Comment by mar-mei** [comment]
With every new channel, the tvg-id is checked with all XMLTV channels, with the first match the link between M3U and XMLTV is created. If you have multiple XMLTV files with the same channels, it is a coincidence which is mapped.
There is no XMLTV fallback.

If you want good and reliable EPG, then take a look at the following alternatives:
`zap2it, webgrab+, Schedules Direct.`
This EPG data must then be mapped manually.

**Comment by GroupMaster** [comment]
I have evaluated several guide providers and I can say Schedules Direct is the best. However, due to how they manage the many channels makes it impossible (on a single account) to get guide data from very many other regions. They are structured to supply for geographic regions and not mix-and-match. IPTV-EPG has fair guide data but they cover many channels and they will provide xml to match your playlist in a mix-and-match. With both, it covers %99 of the streams. 

So the kicker is Scheduled Direct clearly states that Plex is NOT an allowed app and violates their terms. I suppose this is due to the multi-app accessibility aspect. Included are any programs that are not listed on the list of approved apps list.

**Comment by MCTyler** [comment]
Free is always Best..... Also no Disclaimer on Zap2Xml ;)
