### ISSUE TITLE
Option to build xteve.m3u with direct links to streams

### ISSUE THREAD

**Issue by walrusone** [xteve-project/xTeVe#8]
**Is your feature request related to a problem? Please describe.**
I'm just coming from 1.4.4, however I haven't quite been using xteve fully as intended. I've fallen in love with the editing and epg functions of xteve, but didn't like the plex or emby interface. So, up to this point I've been using xteve to create a custom m3u and xml that I use as a source in tivimate. I basically run xteve in a dropbox folder and use dropbox links to the xteve.m3u and xteve.xml in my iptv player.  I've just updated to 2.0.1 and was amazed by how much snappier the interface was, however I was quickly disappointed to see that the custom m3u's are no longer usable in other players as they now use hashcodes which link to the urls.json instead of the direct links to the steams. 

**Describe the solution you'd like**
I'd love an option in the settings to have the m3u saved with the direct stream links instead of the new hashed stream links. 

**Describe alternatives you've considered**
A possibility to connect to xteve remotely without using plex or emby.
Or maybe you would consider a xteve editor fork that contains all the m3u editing functions without the plex/emby server support. 

**Additional context**
I completely understand if this is something that can't be done due to the fact that I'm using xteve in a unintended way. However, xteve is a powerful m3u editor and can fully compete with xtream editor online (in fact, being able to draw from mulitple epgs and assign epgs is much better than what xtream editor has online). I was actually planning to write a how-to guide for people who wanted to use xteve as a powerful m3u and epg editor.

**Comment by xteve-project** [comment]
In v1 the DVR function and xteve.m3u were processed differently. In v2 it is now consistent.
This was also necessary to enable the new buffer function for the xteve.m3u as well.

Why are you using Dropbox and not the xteve.m3u link in your client?

I'm sorry, but a switch to write the original URL to the xteve.m3u will not be implemented.

**Comment by walrusone** [comment]
Ok, thanks for your feedback. The reason I'm using a dropbox link for my player is because the player (tivimate) is running in both my house and my cabin which are on different networks so I had to be able to remotely get the m3u and xml since I'm not using a Plex or Emby client. I've created a fork for now that does what I want. Thanks for the great work!
