### ISSUE TITLE
URL protocol modification for DVR IP

### ISSUE THREAD

**Issue by aegie** [xteve-project/xTeVe#80]
Hello,

After successfully managing to create a reverse proxy in docker using letsencrypt image with the below config, I would also like an option to modify URL protocol from "http" into "https" in DVR IP address.
In settings, we have already the option to modify protocols for both xteve.m3u and xteve.xml, but not for the DVR IP, this leading to 400 errors in plex:

`(ERROR - [Transcoder] http://xteve.redacted.net:443/stream/859d138ecc3b6c0dacf9beeafa73dd22: Server returned 400 Bad Request)`

I tried and specified my DVR in plex when adding it with https protocol, still it errors out and cannot open any streams due to the 400 errors.

![xxxx](https://user-images.githubusercontent.com/30295068/72202317-8e7bad80-3466-11ea-81de-f74040ba2112.jpg)

My working reverse proxy config, in case someone needs it:
```

#Make sure that your dns has a cname set for xteve

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name xteve.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    #enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        #enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        #enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_xteve xteve;
        proxy_pass http://192.168.1.151:34400;
		
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```
Or, if there is a workaround to already modify, please suggest.
Thank you for you hard work!

**Comment by mar-mei** [comment]
The protocol setting will be removed in the next version.

The protocol setting has the disadvantage that xTeVe cannot be used locally and remotely at the same time.

With an HTTP -> HTTPS redirect in your proxy, everything works.
Here is an nginx example configuration:

```

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

```
