### ISSUE TITLE
since 2.1.1 xteve does not stream udp multicast

### ISSUE THREAD

**Issue by HolgerAusB** [xteve-project/xTeVe#82]
**Describe the bug**
I can watch TV streams with Multicast URLs available only for customers of my internet provider (Deutsche Telekom). Example-URL is udp://@232.0.20.35:10000?sources=87.141.215.251

Since xteve 2.1.1 and last two Plex-Versions these links are not working anymore. Plex rises an error immidiately. So I downgraded to 2.1.0 and have no problems.

Common http-Streams are not affected and work without problems with 2.1.1. So maybe its on the unescaped ? or = from the URL

Buffer is set to ffmpeg with standard options

And by the way: ffmpeg does not even have a user-agent option

**Server (please complete the following information):**
- OS Linux Debian Buster, both for xTeVe and PMS
- Arch Intel 64 Bit
- xTeVe Version and Build 2.1.1 Build: 0112

**Additional context**
see the log: [xteve-log.txt](https://github.com/xteve-project/xTeVe/files/4060537/xteve-log.txt)

**Comment by mar-mei** [comment]
What do you have as a user agent?
Perhaps the Telekom is blocking the registered user agent.

The only difference between 2.1.0 and 2.1.1 is that the User Agent is now also used for FFmpeg and VLC.

**Comment by HolgerAusB** [comment]
As far as I have researched,ffmpeg does not have a user-agent option at all. From the logifile in first post:
`FFMPEG log: Option user-agent not found.`

The user-agent field in xTeVe settings is empty. The problem occurs only when using the udp multicast-url, so its very myterious.

I thought it could be one of the special characters in the url: @ or ? or =

**Comment by HolgerAusB** [comment]
I tested some more and startet xteve 2.1.1 while im /tmp and added a -report to ffmpeg settings and changed loglevel to verose. So from ffmpeg's report I figured out how xteve is starting ffmpeg:
`/usr/bin/ffmpeg -user-agent  -hide_banner -loglevel verbose -report -i "udp://@232.0.20.35:10000?sources=87.141.215.251" -c copy -f mpegts pipe:1` 
Now I took this line and changed the pipe:1 to file.ts and tried that directly on the prompt. I got the error "Option user-agent not found", even when I set "-user-agent xTeVe -hide-banner..." or any othe user-agent like "Mozilla" or "Chinchilla". Ffmpeg stops working immediately. When I strip the user-agent option that line works fine and the stream is recorded to /tmp/file.ts

see the ffmpeg report.log:
[ffmpeg.log](https://github.com/xteve-project/xTeVe/files/4086845/ffmpeg.log)

**Comment by mar-mei** [comment]
Which FFmpeg version do you use?
I use:
```
ffmpeg -version
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
```

Switch to xTeVe beta (2.1.1.0116-beta)
https://github.com/xteve-project/xTeVe#xteve-beta-branch
If the user agent is not specified in xTeVe, the default of FFmpeg or VLC is used.
Then FFmpeg and VLC behave like version 2.1.0

**Comment by HolgerAusB** [comment]
ffmpeg is from deb-multimedia.org for Debian Buster:

`ffmpeg --version
ffmpeg version 4.1.5 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)`

`sudo apt show ffmpeg
Package: ffmpeg
Version: 10:4.1.5-dmo1+deb10u1`

Beta 0116 works fine now. I set no user-agent and it works. When setting any user-agent just for test it does not work.

Thanks for your help

CU Holger

**Comment by mar-mei** [comment]
Maybe your FFmpeg version doesn't support a user agent. The FFmpeg parameters that xTeVe uses are all from the FFmpeg documentation.
