### ISSUE TITLE
Automatically use the dummy EPG guide for new/current channel's with no epg

### ISSUE THREAD

**Issue by smurfster** [xteve-project/xTeVe#83]
My provider constantly adds/changes available channel's. Sometimes the new channel doesn't have any EPG. Can we have a option to use the dummy guide in these situations so I can still see and use the channel

Cheers

**Comment by mar-mei** [comment]
The idea of xTeVe is to have a complete EPG.
Automatic assignment of the dummy as EPG does not help much, all new channels must first be activated in Plex.

If your provider used unique IDs for the streams, you wouldn't have the problem.

Unique ID: Streams that have a unique ID can be assigned more reliably, even if the channel name changes. Helpful for streams where the channel name changes regularly. How this ID works is similar to a Database ID.
There is no official parameter for it, in most cases the parameter is CUID="1234", channel-id="abcd".
xTeVe analyzes each stream to find an ID, even if the parameter is different.
If the stream does not contain this ID, the channel name is used for channel assignment. If the channel name changes during an update, this is a new channel for xTeVe and the old one will be deleted.
