### ISSUE TITLE
cannot manage device in plex: Device not found

### ISSUE THREAD

**Issue by OneCyrus** [xteve-project/xTeVe#84]
**Describe the bug**
intial config and tuning in plex works quite well. but i can't change the settings in plex as xTeVe is not recognized/found in the plex after first setup.

this is how it looks

![image](https://user-images.githubusercontent.com/7747800/72682714-6cbaa000-3ad0-11ea-9bd9-f94344b02281.png)

though it should look like this with the gear icon to edit settings: 
![image](https://user-images.githubusercontent.com/7747800/72682760-f2d6e680-3ad0-11ea-8bab-b293007771cb.png)

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
- Arch [e.g. Intel 64 Bit]
- xTeVe Version and Build [to be found in the xTeVe log]

**To Reproduce**
1. Go to Plex > Settings > Manage: Live TV & DVR
2. the Tuner is listed as not found. it should be listed without errors.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Chrome
 - Version: 79
 - Plex Version: 1.18.4.2171

**Comment by OneCyrus** [comment]
hmm ok looks like this is just a bit flaky in plex. after restarts it reports as online again.

**Comment by mar-mei** [comment]
Is described in the documentation:
https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/troubleshooting.md#plex

**Comment by alturismo** [comment]
> hmm ok looks like this is just a bit flaky in plex. after restarts it reports as online again.

sorry, but this is not a xteve issue, this is either your network (something is disturbung, dlna, ...) or a plex issue.

can be closed
