### ISSUE TITLE
Dummy as EPG breaks other EPG

### ISSUE THREAD

**Issue by goldcougar** [xteve-project/xTeVe#85]
**Describe the bug**
After assigning a channel to the dummy EPG, when Plex refreshes, only the dummy channels are shown in the EPG. In the Plex DVR settings area, it shows I have 318 channels enabled, yet only the only ones that show in the plex epg are the 3 assigned to dummy channels. 

**Server (please complete the following information):**
- Windows 10 64 bit
- Plex 1.18.4.2171
- xTeVe 2.1.1 Build: 0112

![IMG_20200119_173713](https://user-images.githubusercontent.com/10157914/72689769-0428ee80-3ae3-11ea-9b8f-a0924fb9a24a.jpg)
![IMG_20200119_173736](https://user-images.githubusercontent.com/10157914/72689773-0c812980-3ae3-11ea-8eca-33fad77d0274.jpg)

**Comment by mar-mei** [comment]
Plex has an XML bug on large files.  You have to enter the local path of the xteve.xml file.  Plex also only shows current EPG data

https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/troubleshooting.md#dvr-guide-is-suddenly-empty


https://forums.plex.tv/t/bug-20mb-xmltv-file-size-limit/411395
