### ISSUE TITLE
Custom Channel Mapping Plex

### ISSUE THREAD

**Issue by s1mb4-rawr** [xteve-project/xTeVe#86]
**Describe the bug**
Plex does not display the channel if it's channel number is changed in xTeVe

**Server (please complete the following information):**
- Linux - Ubuntu
- Intel 64 Bit
- 2.1.1 Build: 0112

**To Reproduce**
1. Change channel number for a channel in xTeVe
2. Add the dvr to Plex

**Expected behavior**
Channels in plex should have the same channel numbers as XteVe

**Screenshots**
<img width="1731" alt="Screen Shot 2020-01-28 at 1 07 30 PM" src="https://user-images.githubusercontent.com/6494923/73292552-3e277e00-41d0-11ea-802b-d69165cb5415.png">
<img width="733" alt="Screen Shot 2020-01-28 at 1 07 21 PM" src="https://user-images.githubusercontent.com/6494923/73292531-349e1600-41d0-11ea-8d74-5b10d68048d9.png">
<img width="426" alt="Screen Shot 2020-01-28 at 1 08 58 PM" src="https://user-images.githubusercontent.com/6494923/73292596-50092100-41d0-11ea-881d-0d6a05b69a8c.png">
<img width="327" alt="Screen Shot 2020-01-28 at 1 10 12 PM" src="https://user-images.githubusercontent.com/6494923/73292604-51d2e480-41d0-11ea-9de6-5bbc1ed675e6.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 79.x

**Additional context**
The channel number appears correctly everywhere except for the Plex guide. On xTeVe mapping it shows correctly, in xTeVe XML is shows correctly, in the Plex config for DVR it shows correctly. In the guide is shows 1 less channel (356) than anticipated (357) - and does not show the custom mapped channel. This is the exact same issue as #62 but there was never any comment added to that closed ticket for how to resolve this.

**Comment by mar-mei** [comment]
check the lineup.json if the channel numbers are correct there, it is a plex bug.
http://xteve.ip:34400/lineup.json


Since the channel numbers in the DVR setup are correct, I suspect a plex issue.

**Comment by GroupMaster** [comment]
Can sorta confirm. The only way I have gotten a modified lineup to work properly in plex is to remove xteve from plex and re-add it. So only "from scratch".

**Comment by s1mb4-rawr** [comment]
@mar-mei i checked the liineup.json and confirmed. Just as you said, it's most likely a Plex issue.

There is some weird behaviour going on. The channel I mapped to Channel 1 (CP24), I tried changing it to 2,3,4,5..etc and removing DVR, re-adding it back and on Channel 24 it worked.

Any idea why or how this would work? If i try 25, channel disappears again from the guide.

**Comment by GroupMaster** [comment]
So you have a stream that you mapped to channel 1 and it didn't work. So you cleared the plex dvr, edited the mapping in xteve and clean loaded the new dvr in plex. You repeated this until you got to plex channel 24 where it finially worked. You then did the process 1 more time to channel 25 and the outcome was the same negative outcome as the first 23?

Also, did you have other channels in the lineup, or only the 1?

**Comment by MCTyler** [comment]
Plex Issue: Should be closed
