### ISSUE TITLE
Adding time zone to xmltv file

### ISSUE THREAD

**Issue by dodepier** [xteve-project/xTeVe#88]
**Is your feature request related to a problem? Please describe.**
My source xmltv file does not have a time zone added to the start and stop time in the xml. Now the guide of Plex is 1 hour of since it assumes it is UTC (the Netherlands is +1). See more info:
https://forums.plex.tv/t/tv-guide-1-hour-off/536012

xmltv
http://d52255a1.static.ziggozakelijk.nl/xmltv.xml

**Describe the solution you'd like**
Edit or add a timezone to a channel or source xmltv file. This can be done with something like this:

```
$xml_ziggo  = simplexml_load_file('http://d52255a1.static.ziggozakelijk.nl/xmltv.xml');

foreach ( $xml_ziggo->programme as $programme ) {
    $programme['start'] = $programme['start'].' -0100';
    $programme['stop'] = $programme['stop'].' -0100';
}
echo $xml_ziggo->asXML();
```
(source: https://stackoverflow.com/questions/49217566/add-time-offset-in-epg-xmltv-file)

**Comment by MCTyler** [comment]
xTeVe reads the "clock" on the device it's installed on...If you change this you are accomplishing the same result.

**Comment by MCTyler** [comment]
I downloaded your EPG, it does have start and stop times in it........
`
![image](https://user-images.githubusercontent.com/6390898/73611064-a3e68200-45a3-11ea-94f7-25c77b6caf3e.png)`

**Comment by dodepier** [comment]
Yes it is sloppy. I fixed it by running a stript on my server which copies the EPG xml file (once a day) and creates a new one with the time zone ' +0100':

```
<?php

$xml_ziggo  = simplexml_load_file('http://d52255a1.static.ziggozakelijk.nl/xmltv.xml');

foreach ( $xml_ziggo->programme as $programme ) {
    $programme['start'] = $programme['start'].' +0100';
    $programme['stop'] = $programme['stop'].' +0100';
}

$xml_ziggo->saveXML('/tmp/ZiggoXMLTV.xml');
?>

```

**Comment by MCTyler** [comment]
We discussed it on Discord, might be something we could add to xTeVe like Simple client in Kodi does....
https://cdn.discordapp.com/attachments/465980714278715412/673567316289650698/unknown.png

**Comment by mar-mei** [comment]
xTeVe should not have the task of fixing errors that the provider makes. The XMLTV specification stipulates that the time zone must be specified.

http://wiki.xmltv.org/index.php/XMLTVFormat
