### ISSUE TITLE
Plex won't play channels without epg?

### ISSUE THREAD

**Issue by helpman** [xteve-project/xTeVe#89]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I matched all channels with their epg, for channels without it, I used xteve's dummys.
Plex loads all channels, but some of the channels that do have their own epg are missing the channel info. They just show as if there were no epg at all.
Channels with EPG or with xteve dummys are working fine. But if they lack any program guide, plex just tells me the channel is not broadcasting. (same channels work fine on VLC)

maybe xteve could use dummys by default, then if epg data is found, overwrite it when updating?
this way even with a failure on the external xml there would be dummys and plex would accept all channels...

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
- Arch [e.g. Intel 64 Bit]
- xTeVe Version and Build [to be found in the xTeVe log]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mar-mei** [comment]
Plex requires current EPG data for each channel, without EPG no streaming. With xTeVe Bulk Edit you can assign the Dummy to multiple channels.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by helpman** [comment]
> Plex requires current EPG data for each channel, without EPG no streaming. With xTeVe Bulk Edit you can assign the Dummy to multiple channels.
> 
> Sent with [GitHawk](http://githawk.com)

I know, those channels have epg, but they were not updated by plex, so they show in plex but with no epg data. plex says they're not broadcasting, although they work fine on vlc

**Comment by mar-mei** [comment]
Check whether the EPG data is up to date. Plex does not display old EPG data and then the stream cannot be played. You should report problems with Plex in the Plex forum.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
