### ISSUE TITLE
original-air-date day and time is incorrect

### ISSUE THREAD

**Issue by thomashw** [xteve-project/xTeVe#9]
The original-air-date being populated in the XML file is being populated by the date and time of when the XML file is generated, not when the show is scheduled, which is causing Plex's guide to think all programs with the same title to be the same episode.

I believe the original-air-date should be set to when the show is scheduled to start, much like how version 1.4.4 was doing it.

**Version 2.0.1**
Note - was generated August 16th at 7:49am.
Notice the discrepancy between the "start" time (August 18th 7:30pm) and the original-air-date (August 16th 7:49am).

`<programme channel="1044" start="20190818193000 +0100" stop="2019081823000
0 +0100">
          <title lang="en">Live PGA Tour Golf</title>
          <sub-title lang="en">2019 BMW Championship: Day Four</sub-title>
          <desc lang="en">The BMW Championship. Coverage of the fourth and final
 day of the second FedEx Cup play-off, held at Medinah Country Club in Illinois(
n)</desc>
          <category lang="en">Series</category>
          <episode-num system="original-air-date">2019-08-16  07:49:38</episode-
num>
          <icon height="" src="https://web.static.nowtv.com/images/NOWTV_2017/02
_TV_Passes/03_Sport/Sky_Sports_Rebrand/Sports_channels_Main_Event.png" width="">
</icon>
          <video>
              <quality>HDTV</quality>
          </video>
          <date></date>
      </programme>
`

**Version 1.4.4**
Note how the original-air-date and "start" time match.

`<programme channel="3" start="20190818190000 +0100" stop="20190818230000 +
0100">
          <title lang="en">Live PGA Tour Golf</title>
          <sub-title lang="en">2019 BMW Championship: Day Four</sub-title>
          <desc lang="en">The BMW Championship. Coverage of the fourth and final day of the second FedEx Cup play-off, held at Medinah Country Club in Illinois(n)</desc>
          <category lang="">Series</category>
          <episode-num system="original-air-date">2019-08-18 19:00:00</episode-num>
          <icon src="https://www.skymedia.co.uk/wp-content/uploads/2017/07/SkySports-GOLF.png"></icon>
          <language></language>
          <video>
              <present>yes</present>
              <colour>yes</colour>
              <quality>HDTV</quality>
          </video>
          <date></date>
      </programme>
`

Using xTeVe 2.0.1.

**Comment by xteve-project** [comment]
Looks like a bug, I'll take a look.

**Comment by xteve-project** [comment]
Fixed in 2.0.1.0011-beta
