### ISSUE TITLE
ARM 32Bits Version

### ISSUE THREAD

**Issue by marcelobartsch** [xteve-project/xTeVe#91]
**Is your feature request related to a problem? Please describe.**
Is not related to an issue,but would be nice to have a ARM 32bits version available

**Describe the solution you'd like**
32bits ARM Version Available for download

**Describe alternatives you've considered**
Compile in my RPi4 :)

**Additional context**
None

**Comment by mar-mei** [comment]
I'm sorry, but 32 bit has no future. I also don't know if an old Pi 2 has enough power for FFmeg and VLC.
If someone needs 32 bits, the source code is there. Officially, 32 bit is not supported.

**Comment by MCTyler** [comment]
https://github.com/marcelobartsch

Someone uploaded a Copy on our Discord...your welcome to play with it if you find it....

**Comment by MCTyler** [comment]
Please don't ask for Support on this Version.

**Comment by marcelobartsch** [comment]
Don't worry, I have build my own 32bit version for the pi4.
You can close this.

**Comment by MCTyler** [comment]
You can close it as Author too... ;)
