### ISSUE TITLE
TheTVDB Season/Episode lookup from AirDate?

### ISSUE THREAD

**Issue by k0rtina** [xteve-project/xTeVe#92]
**Is your feature request related to a problem?**
As a Plex user, I am disappointed that the 'Air Date' attribute within the EIT (over the air) based EPG is not able to be converted into a Season/Episode value. This makes Plex less useful as a DVR as the content doesn't arrive correctly in folders. 

**Describe the solution you'd like**
Using 'thetvdb' api, use data from the EPG to lookup additional Season/Episode information to enrich the EPG.

**Example of EIT (over the air EPG data) in Australia:**
```
<programme channel="80" start="20200224193000 +1100" stop="20200224210000 +1100">
<title lang="eng">Australian Survivor: All Stars</title>
<sub-title lang="eng">
After Tribe swap, things are a bit shaky for a few tribe members lost without their alliances. Tribe members scramble to show their loyalty, but will the vote be swayed in their favour?
</sub-title>
<desc lang="eng"> . </desc>
<category lang="en">Series</category>
**<episode-num system="original-air-date">2020-02-24 19:30:00</episode-num>**
<icon height="" src="http://192.168.122.1:34400/images/637c2e39cb962b961e8ef438aaccec38.png" width=""/>
<video>
<quality>HDTV</quality>
</video>
<date/>
</programme>
```

Looking at thetvdb: https://www.thetvdb.com/series/australian-survivor

This episode should be identified as Season 7, Episode 10 (based on the air date).

**Describe alternatives you've considered**
Paid EPG services are unreliable and expensive.  EPG providers seem to come and go in Australia.

**Additional context**
Maybe this feature could be an option to turn ON.
Settings/EPG Source/TVDB EPG enrichment

**Comment by mar-mei** [comment]
There will be no function to select providers in xTeVe.

- APIs can change.
- If this provider is supported why not others.
- Someone has to test and maintain this regularly.

Calculating the episode number based on the *original-air-date* goes wrong in sports immediately if 2 games happen at the same time. 

There are enough EPG providers with reliable data
- WebGrab + Plus (free)
- zap2it (free)
- Schedules Direct ($ 25 / year)
