### ISSUE TITLE
Ability to change name of Tuner

### ISSUE THREAD

**Issue by wbilger** [xteve-project/xTeVe#93]
**Is your feature request related to a problem? Please describe.**
I am running 2 instances of Xteve in docker. You can trick Plex to run 2 instance of DVR by opening 2 windows and adding a DVR in each one. It works.
Plex errors our on the 2nd Xteve tuner as it has the same name as the 1st.

**Describe the solution you'd like**
I have accomplished this in telly before, but it allows you to change the tuner name.
I much prefer Xteve.
Add the ability in one of the .json file to change the tuner name.
I tried manually changing the UUID, but doesn't seem to work.

**Comment by xteve-project** [comment]
Do you mean that name?

![Auswahl_003](https://user-images.githubusercontent.com/53275662/75098146-f28ba880-55b2-11ea-90eb-b90fd8dd2c16.png)

**Comment by MCTyler** [comment]
Interesting suggestion....Where does xTeVe get the name for the Tuner? There's that pms.json file....what does that do?

**Comment by wbilger** [comment]
Yes, that name.
I am guessing that is why Plex won't allow me to add 2 DVRs, as they have
the same name from 2 instances of xteve.

**Comment by wbilger** [comment]
This is not needed, I figured it out, so this can be closed.
I tried changing the uuid before but it didn't work, but I only added characters to the end so it must have ignored those. I changed the uuid but kept it the same length, and now it works, I can add 2 tuners. Thanks.
