### ISSUE TITLE
 No response from streaming server

### ISSUE THREAD

**Issue by noviceiii** [xteve-project/xTeVe#94]
**Describe the bug**
I am unable to establish a stream thorugh xTeVe streaming using PLEX nor VLC.
However xTeVe starts successfully, shows the configuration UI and PLEX loads EPG and channels.
It also works for VLC, if direct streaming is enabled.

If one trys to connect to a channel, below message appears continiously in log and terminal window.
`[xTeVe] [ERROR] No response from streaming server () - EC: 0`

```
2020/02/25 14:27:40 [xTeVe] Streaming Status:      Playlist:  - Tuner: 0 / 1
2020/02/25 14:27:40 [xTeVe] Buffer:                true [xteve]
2020/02/25 14:27:40 [xTeVe] Buffer Size:           1024 KB
2020/02/25 14:27:40 [xTeVe] Channel Name:           ITV 2
2020/02/25 14:27:40 [xTeVe] Client User-Agent:     VLC/3.0.8 LibVLC/3.0.8
2020/02/25 14:27:41 [xTeVe] Streaming Status:      Playlist:  - Tuner: 1 / 1
2020/02/25 14:27:41 [xTeVe] Streaming Type:        [TS]
2020/02/25 14:27:41 [xTeVe] Streaming URL:         udp://@239.77.3.14:5000
Current URL: udp://@239.77.3.14:5000
```

**Server (please complete the following information):**
- OS: Ubuntu 18.04 4.15.0-88-generic (headless)
- Arch: 64 bit
- xTeVe: 2.1.2

**To Reproduce**

1. Setup xTeVe
   - Stream xTeVe (xTeVe connects to streaming server) - same behaviour with FFMPEG and VLC - 
2. Download xteve m3u file

**Expected behavior**
A particular stream should be established using xTeVe as a proxy.

**Additional information**
The streams I like to see are UDP multicast streams.

**Comment by noviceiii** [comment]
for further debugging: is there a way to bind xTeVe to a particular network interface?

.. can it handle UDP streams at all?

**Comment by noviceiii** [comment]
I have meanwhile installed it on another server in the same network. I still get the same error.

```
2020/02/25 20:38:41 [xTeVe] Buffer:                true [xteve]
2020/02/25 20:38:41 [xTeVe] Buffer Size:           1024 KB
2020/02/25 20:38:41 [xTeVe] Channel Name:           SRFzwei HD
2020/02/25 20:38:41 [xTeVe] Client User-Agent:     VLC/3.0.8 LibVLC/3.0.8
2020/02/25 20:38:41 [xTeVe] Streaming Status:      Playlist: M3U - Tuner: 1 / 1
2020/02/25 20:38:41 [xTeVe] Streaming Type:        [TS]
2020/02/25 20:38:41 [xTeVe] Streaming URL:         udp://@239.77.0.78:5000
Current URL: udp://@239.77.0.78:5000
2020/02/25 20:38:41 [xTeVe] [ERROR] No response from streaming server () - EC: 0
```

**Comment by xteve-project** [comment]
The xTeVe Buffer only supports HTTP streams, try FFmpeg or VLC.

**Comment by noviceiii** [comment]
Thank you. I thought so. However, I wasn't able to do it with FFMPEG nor VLC.

However, I have found a way to use xTeVe. It now streams rather quick and serves a very good picture.

I was able to fix it by installing udpxy.
In brief, for whom it may concern:

(Debian/ Ubuntu)
**- Install udpxy**
- Start Udpxy with `/usr/local/bin/udpxy -S -H 5 -c 10 -p 40200`
- You should now be able to browse to the status page
   http://[YOURSERVER]:40200/status

**- Prepare the m3u playlist from your provider.** 
   It needs to proxy to the server udpxy is running (above)
- `curl https://[PROVIDER_URL]/tvchannels.m3u | sed -E 's/udp\:\/\/@(.*)$/http:\/\/[YOURSERVER]\:40200\/udp\/\1\//' > /YOURLOCAL_STORE/TV7.m3u`
- Your M3U file should now look similar to this:
```
#EXTM3U
#EXTINF:0 tvg-logo="https://[PROVIDER_URL]/media/logos/SRF1HD_300x300px.png" tvg-name="SRF1.ch" group-title="chde", SRF1 HD
http://[YOURSERVER]:40200/udp/239.77.0.77:5000
```

**- Install/ Start xTeVe**
- Number of tuners (optional): something between 3 and 100
- Settings: Streabuffer xTeVe
- Set the remaining entries as required
