### ISSUE TITLE
Scheduled scripts

### ISSUE THREAD

**Issue by noviceiii** [xteve-project/xTeVe#97]
xTeVe can read files (e.g m3u) at specific times.

In a few settings, those file need to be downloaded and converted first. This is usualy done by a script.

It would be handy, if one could tell xTeVe the path to particular scripts to be executed by xTeVe (maybe checked?) before the m3u update runs.

**Comment by MCTyler** [comment]
This can easily be accomplished by using the clock....Have your script run at 8:45 Have xTeVe update at 8:46.

**Comment by noviceiii** [comment]
Hi MCTyler

By clock you mean crontab? Yes, that can be done.
... buuuuut it would be super convenient to habe it in the GUI :-)

**Comment by xteve-project** [comment]
You can also use the xTeVe API for your own scripts, much more flexible.

**Comment by MCTyler** [comment]
@noviceiii Here's the [link for that.](https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/configuration.md#api)......
