### ISSUE TITLE
Playback Error - Could not tune to channel. Please check your tuner or antenna

### ISSUE THREAD

**Issue by ylafont** [xteve-project/xTeVe#98]
Plex version 1.18.72457 (lasted version as of today)
xteve Version 2.1.2
ubuntu Headless server Version 18.04 Bionic

I think everythign has been properly setup, however i get a "Playback Error - Could not tune to channel. Please check your tuner or antenna"  when i try to tune to any channel. 

xteve does not reports  an error that i can see
![Playback](https://user-images.githubusercontent.com/6156018/75279223-38c25100-57d9-11ea-8436-265eaba2f970.png)

![xteve](https://user-images.githubusercontent.com/6156018/75279230-3b24ab00-57d9-11ea-82ca-de5423cbae2d.png)

Is there anything i can do?

**Comment by xteve-project** [comment]
xTeVe passes the URL to Plex and is no longer involved, Plex connects directly to the streaming server. The Plex Log may help. Issues with Plex are not covered here.

**Comment by ylafont** [comment]
After searching all over the place, I found a posting to change the stream buffer to FFmpeg.

![image](https://user-images.githubusercontent.com/6156018/75294172-bdbb6380-57f5-11ea-8b04-a36fde4917db.png)

and that seem to did the trick.  I hope this helps somelse in the future.   

I wonder what other settings can be applied or changed to maximized performance?

**Comment by OverlordShin** [comment]
Had this exact issue, switching to a stream buffer such as FFmpeg fixed it. Could be that plex assumes there's a buffer already in place and ends up timing out?
