### ISSUE TITLE
Stuttering of the stream

### ISSUE THREAD

**Issue by alszaitsev** [xteve-project/xTeVe#99]
**Describe the bug**
After 20-30 minutes of payback get massive stuttering of the stream (sometimes it rewinds back for 1 min and stucks). Tried to used all buffers - Xteve, FFmpeg, VLC. Played with different Buffer size settings. But still stuttering. Get no errors in log with Xteve and VLC as a buffer, have errors when using FFmpeg after the stream is started 
2020/02/29 22:33:31 [xTeVe] FFMPEG log:            [NULL @ 000002051648d440] non-existing SPS 0 referenced in buffering period
2020/02/29 22:33:31 [xTeVe] FFMPEG log:            [NULL @ 000002051648d440] SPS unavailable in decode_picture_timing
2020/02/29 22:33:31 [xTeVe] FFMPEG log:            [h264 @ 000002051648ee80] non-existing SPS 0 referenced in buffering period
2020/02/29 22:33:31 [xTeVe] FFMPEG log:            [h264 @ 000002051648ee80] SPS unavailable in decode_picture_timing

No such problems with direct playback of the M3U with VLC (or OTT Player). Please help.
Looks like such problem was discussed in https://github.com/xteve-project/xTeVe/issues/33

**Server (please complete the following information):**
- OS Win10
- Arch Intel 64 Bit
- xTeVe Version and Build 2.1.2 Build: 0121
Database Version:      2.1.0

**Comment by xteve-project** [comment]
xTeVe has no influence on FFmpeg. The URL is passed to FFmpeg, the received data is saved by xTeVe and sent to the client.

This can have many causes, poor network connection between FFmpeg / VLC / xTeVe to the source. Packet loss etc.

I test everything with a TV tuner as the source and VLC as the client.

You can start xTeVe in debug level 1, then the whole FFmpeg log will be displayed.

```
~% xteve -h
Usage of xteve:
  -branch string
    	: Git Branch           [master|beta] (default: master)
  -config string
    	: Config Folder        [/path/to/xteve/] (default: /home/marcel/.xteve/)
  -debug int
    	: Debug level          [0 - 3] (default: 0)
  -h	: Show help
  -info
    	: Show system info
  -port string
    	: Server port          [34400] (default: 34400)
  -restore string
    	: Restore from backup  [/path/to/file/xteve_backup.zip]

```
